package spec

import (
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

// allPresets is the closed set the generator ships.
var allPresets = []Preset{PresetLow, PresetMedium, PresetHigh}

// TestPresetsValidateByConstruction is the schema-valid-by-construction
// gate: every embedded preset must pass ValidateBytes (the workflow-v1
// schema) so a preset that drifted out of schema fails the build here,
// not at a user's `fishhawk init`.
func TestPresetsValidateByConstruction(t *testing.T) {
	for _, p := range allPresets {
		p := p
		t.Run(string(p), func(t *testing.T) {
			data, err := PresetBytes(p)
			if err != nil {
				t.Fatalf("PresetBytes(%q): %v", p, err)
			}
			if err := ValidateBytes(data); err != nil {
				t.Fatalf("preset %q does not validate: %v", p, err)
			}
		})
	}
}

// TestGeneratedPresetsAreGeneric is the done-means (behavioral, per
// #1639) assertion: the SHIPPED bytes of every generated preset must
// carry NONE of the fishhawk-repo-specific substrings the ticket names
// (@kuhlman-labs, scripts/dev, scripts/test, localhost:8090) and must
// still pass ValidateBytes. A comment-only / no-op touch of a preset
// that left the maintainer handle or the private test entrypoint in
// place would fail here even though the scope path was touched.
func TestGeneratedPresetsAreGeneric(t *testing.T) {
	forbidden := []string{"@kuhlman-labs", "scripts/dev", "scripts/test", "localhost:8090"}
	for _, p := range allPresets {
		p := p
		t.Run(string(p), func(t *testing.T) {
			data, err := Generate(p, Deltas{})
			if err != nil {
				t.Fatalf("Generate(%q): %v", p, err)
			}
			s := string(data)
			for _, sub := range forbidden {
				if strings.Contains(s, sub) {
					t.Errorf("generated preset %q still contains fishhawk-specific substring %q:\n%s", p, sub, s)
				}
			}
			if err := ValidateBytes(data); err != nil {
				t.Fatalf("generic preset %q does not validate: %v", p, err)
			}
		})
	}
}

// operatorAgentOf decodes generated bytes and returns the
// feature_change workflow's operator_agent block (nil if absent). It
// asserts the bytes are well-formed YAML along the way.
func operatorAgentOf(t *testing.T, data []byte) map[string]any {
	t.Helper()
	var doc struct {
		Workflows map[string]struct {
			OperatorAgent map[string]any `yaml:"operator_agent"`
		} `yaml:"workflows"`
	}
	if err := yaml.Unmarshal(data, &doc); err != nil {
		t.Fatalf("unmarshal generated bytes: %v", err)
	}
	fc, ok := doc.Workflows["feature_change"]
	if !ok {
		t.Fatalf("generated bytes have no feature_change workflow")
	}
	return fc.OperatorAgent
}

// TestGenerateOperatorAgentPerPreset is the done-means (behavioral, per
// #1169) assertion: it pins the SHIPPED operator_agent content of each
// generated preset, so a no-op / comment-only preset edit fails the test
// even though the scope path was touched.
func TestGenerateOperatorAgentPerPreset(t *testing.T) {
	t.Run("low has no operator_agent block", func(t *testing.T) {
		data, err := Generate(PresetLow, Deltas{})
		if err != nil {
			t.Fatalf("Generate(low): %v", err)
		}
		if oa := operatorAgentOf(t, data); oa != nil {
			t.Fatalf("low preset must have no operator_agent block, got %v", oa)
		}
	})

	t.Run("medium has the three delegation knobs + 7 page events, no waive/merge", func(t *testing.T) {
		data, err := Generate(PresetMedium, Deltas{})
		if err != nil {
			t.Fatalf("Generate(medium): %v", err)
		}
		oa := operatorAgentOf(t, data)
		if oa == nil {
			t.Fatal("medium preset must have an operator_agent block")
		}
		if got := oa["may_approve"]; got != "clean_dual_approval" {
			t.Errorf("may_approve = %v, want clean_dual_approval", got)
		}
		if got := oa["may_route_fixup"]; got != "convergent_concerns" {
			t.Errorf("may_route_fixup = %v, want convergent_concerns", got)
		}
		if got := oa["may_retry"]; got != "infra_flake" {
			t.Errorf("may_retry = %v, want infra_flake", got)
		}
		if _, ok := oa["may_waive"]; ok {
			t.Errorf("medium must NOT set may_waive, got %v", oa["may_waive"])
		}
		if _, ok := oa["may_merge"]; ok {
			t.Errorf("medium must NOT set may_merge, got %v", oa["may_merge"])
		}
		wantPage := []string{
			"reviewer_reject", "plan_rejection", "scope_amendment",
			"budget_override", "policy_override", "exception_request",
			"requirement_arbitration",
		}
		assertPageEvents(t, oa, wantPage)
	})

	t.Run("high adds may_waive and may_merge", func(t *testing.T) {
		data, err := Generate(PresetHigh, Deltas{})
		if err != nil {
			t.Fatalf("Generate(high): %v", err)
		}
		oa := operatorAgentOf(t, data)
		if oa == nil {
			t.Fatal("high preset must have an operator_agent block")
		}
		if got := oa["may_approve"]; got != "clean_dual_approval" {
			t.Errorf("may_approve = %v, want clean_dual_approval", got)
		}
		if got := oa["may_route_fixup"]; got != "convergent_concerns" {
			t.Errorf("may_route_fixup = %v, want convergent_concerns", got)
		}
		if got := oa["may_retry"]; got != "infra_flake" {
			t.Errorf("may_retry = %v, want infra_flake", got)
		}
		if got := oa["may_waive"]; got != "solo_low" {
			t.Errorf("may_waive = %v, want solo_low", got)
		}
		if got := oa["may_merge"]; got != "gates_resolved_ci_green" {
			t.Errorf("may_merge = %v, want gates_resolved_ci_green", got)
		}
		assertPageEvents(t, oa, []string{
			"reviewer_reject", "plan_rejection", "scope_amendment",
			"budget_override", "policy_override", "exception_request",
			"requirement_arbitration",
		})
	})
}

func assertPageEvents(t *testing.T, oa map[string]any, want []string) {
	t.Helper()
	raw, ok := oa["must_page_human"].([]any)
	if !ok {
		t.Fatalf("must_page_human is not a list: %T", oa["must_page_human"])
	}
	if len(raw) != len(want) {
		t.Fatalf("must_page_human has %d events, want %d: %v", len(raw), len(want), raw)
	}
	for i, w := range want {
		if raw[i] != w {
			t.Errorf("must_page_human[%d] = %v, want %v", i, raw[i], w)
		}
	}
}

// TestGenerateBudgetCeilingDelta covers the budget-ceiling delta branch:
// the emitted limit_usd changes AND the output still validates.
func TestGenerateBudgetCeilingDelta(t *testing.T) {
	limit := 250
	data, err := Generate(PresetMedium, Deltas{BudgetLimitUSD: &limit})
	if err != nil {
		t.Fatalf("Generate with budget delta: %v", err)
	}
	if err := ValidateBytes(data); err != nil {
		t.Fatalf("budget-delta output does not validate: %v", err)
	}
	got := budgetLimitOf(t, data)
	if got != 250 {
		t.Errorf("limit_usd = %v, want 250", got)
	}
	// And confirm the un-delta'd default really was different, so the
	// assertion above is load-bearing.
	base, err := Generate(PresetMedium, Deltas{})
	if err != nil {
		t.Fatalf("Generate(medium): %v", err)
	}
	if def := budgetLimitOf(t, base); def == 250 {
		t.Fatalf("default limit_usd already 250 — budget delta assertion is not load-bearing")
	}
}

func budgetLimitOf(t *testing.T, data []byte) float64 {
	t.Helper()
	var doc struct {
		Workflows map[string]struct {
			Budgets []struct {
				LimitUSD float64 `yaml:"limit_usd"`
			} `yaml:"budgets"`
		} `yaml:"workflows"`
	}
	if err := yaml.Unmarshal(data, &doc); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	fc := doc.Workflows["feature_change"]
	if len(fc.Budgets) == 0 {
		t.Fatal("no budgets block in generated bytes")
	}
	return fc.Budgets[0].LimitUSD
}

// TestGenerateSingleReviewerDelta covers the single-vs-dual-reviewers
// delta branch: the Codex reviewer is dropped from every stage AND the
// output still validates.
func TestGenerateSingleReviewerDelta(t *testing.T) {
	data, err := Generate(PresetMedium, Deltas{SingleReviewer: true})
	if err != nil {
		t.Fatalf("Generate with single-reviewer delta: %v", err)
	}
	if err := ValidateBytes(data); err != nil {
		t.Fatalf("single-reviewer output does not validate: %v", err)
	}
	if strings.Contains(string(data), "codex") || strings.Contains(string(data), "gpt-5.5") {
		t.Errorf("single-reviewer output still names the codex reviewer:\n%s", data)
	}
	// The Claude reviewer must survive.
	if !strings.Contains(string(data), "claudecode") {
		t.Errorf("single-reviewer output dropped the claude reviewer too:\n%s", data)
	}
	// Structural check: every stage's reviewers.agents has exactly one entry.
	for stageID, agents := range reviewerCountsByStage(t, data) {
		if agents != 1 {
			t.Errorf("stage %q has %d reviewer agents, want 1", stageID, agents)
		}
	}
}

func reviewerCountsByStage(t *testing.T, data []byte) map[string]int {
	t.Helper()
	var doc struct {
		Workflows map[string]struct {
			Stages []struct {
				ID        string `yaml:"id"`
				Reviewers *struct {
					Agents []any `yaml:"agents"`
				} `yaml:"reviewers"`
			} `yaml:"stages"`
		} `yaml:"workflows"`
	}
	if err := yaml.Unmarshal(data, &doc); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	out := map[string]int{}
	for _, s := range doc.Workflows["feature_change"].Stages {
		if s.Reviewers != nil {
			out[s.ID] = len(s.Reviewers.Agents)
		}
	}
	return out
}

// TestGenerateHumanGatesDelta covers the human-gates delta branch:
// naming only the plan stage keeps its gate and removes the review
// stage's gate AND the output still validates.
func TestGenerateHumanGatesDelta(t *testing.T) {
	data, err := Generate(PresetMedium, Deltas{HumanGates: []string{"plan"}})
	if err != nil {
		t.Fatalf("Generate with human-gates delta: %v", err)
	}
	if err := ValidateBytes(data); err != nil {
		t.Fatalf("human-gates output does not validate: %v", err)
	}
	gates := gatesByStage(t, data)
	if !gates["plan"] {
		t.Errorf("plan stage should keep its human gate, got none")
	}
	if gates["review"] {
		t.Errorf("review stage should have its gate removed, still present")
	}
}

func gatesByStage(t *testing.T, data []byte) map[string]bool {
	t.Helper()
	var doc struct {
		Workflows map[string]struct {
			Stages []struct {
				ID    string `yaml:"id"`
				Gates []any  `yaml:"gates"`
			} `yaml:"stages"`
		} `yaml:"workflows"`
	}
	if err := yaml.Unmarshal(data, &doc); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	out := map[string]bool{}
	for _, s := range doc.Workflows["feature_change"].Stages {
		out[s.ID] = len(s.Gates) > 0
	}
	return out
}

// TestGenerateUnknownPreset covers the unknown-preset error branch.
func TestGenerateUnknownPreset(t *testing.T) {
	if _, err := Generate(Preset("bogus"), Deltas{}); err == nil {
		t.Fatal("Generate with unknown preset must error")
	}
	if _, err := PresetBytes(Preset("bogus")); err == nil {
		t.Fatal("PresetBytes with unknown preset must error")
	}
}

// TestGenerateMediumRoundTrip is the round-trip check: generate medium,
// parse it back, and assert its operator_agent + reviewers match the
// current feature_change semantics — against hardcoded expected values,
// not a cross-module read of .fishhawk/workflows.yaml.
func TestGenerateMediumRoundTrip(t *testing.T) {
	data, err := Generate(PresetMedium, Deltas{})
	if err != nil {
		t.Fatalf("Generate(medium): %v", err)
	}
	oa := operatorAgentOf(t, data)
	if oa["may_approve"] != "clean_dual_approval" ||
		oa["may_route_fixup"] != "convergent_concerns" ||
		oa["may_retry"] != "infra_flake" {
		t.Errorf("medium operator_agent knobs drifted from feature_change: %v", oa)
	}
	// Both stages that carry reviewers must run the Claude+Codex pair.
	counts := reviewerCountsByStage(t, data)
	for _, stageID := range []string{"plan", "implement"} {
		if counts[stageID] != 2 {
			t.Errorf("stage %q reviewer agents = %d, want 2 (claude+codex)", stageID, counts[stageID])
		}
	}
}

// TestGenerateBudgetDeltaOnMalformedPreset asserts applyBudgetLimit
// fails loud when the budgets block is missing. Constructed inline
// rather than via an embedded preset, since every shipped preset has a
// budgets block by construction.
func TestApplyBudgetLimitMissingBlock(t *testing.T) {
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte("stages: []\n"), &doc); err != nil {
		t.Fatalf("setup unmarshal: %v", err)
	}
	wf := documentRoot(&doc)
	if wf == nil {
		t.Fatal("setup: expected a mapping root")
	}
	if err := applyBudgetLimit(wf, 100); err == nil {
		t.Fatal("applyBudgetLimit must error when budgets block is absent")
	}
}
