// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package oauthstoredb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OauthAccessToken struct {
	ID                  uuid.UUID          `json:"id"`
	TokenHash           string             `json:"token_hash"`
	Subject             string             `json:"subject"`
	ClientID            string             `json:"client_id"`
	Audience            string             `json:"audience"`
	Scopes              []string           `json:"scopes"`
	Provider            string             `json:"provider"`
	AccountID           *uuid.UUID         `json:"account_id"`
	AuthorizationCodeID uuid.UUID          `json:"authorization_code_id"`
	IssuedAt            pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt          pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
}

type OauthAuthorizationCode struct {
	ID                  uuid.UUID          `json:"id"`
	CodeHash            string             `json:"code_hash"`
	ClientID            string             `json:"client_id"`
	RedirectUri         string             `json:"redirect_uri"`
	CodeChallenge       string             `json:"code_challenge"`
	CodeChallengeMethod string             `json:"code_challenge_method"`
	Scopes              []string           `json:"scopes"`
	Resource            *string            `json:"resource"`
	Subject             string             `json:"subject"`
	Provider            string             `json:"provider"`
	AccountID           *uuid.UUID         `json:"account_id"`
	IssuedAt            pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt          pgtype.Timestamptz `json:"consumed_at"`
}

type OauthClient struct {
	ID                      uuid.UUID          `json:"id"`
	Provider                string             `json:"provider"`
	ClientID                string             `json:"client_id"`
	RedirectUris            []string           `json:"redirect_uris"`
	GrantTypes              []string           `json:"grant_types"`
	ResponseTypes           []string           `json:"response_types"`
	TokenEndpointAuthMethod string             `json:"token_endpoint_auth_method"`
	ClientName              *string            `json:"client_name"`
	ClientUri               *string            `json:"client_uri"`
	LogoUri                 *string            `json:"logo_uri"`
	Scope                   *string            `json:"scope"`
	AccountID               *uuid.UUID         `json:"account_id"`
	FirstSeenAt             pgtype.Timestamptz `json:"first_seen_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type OauthRefreshToken struct {
	ID                  uuid.UUID          `json:"id"`
	TokenHash           string             `json:"token_hash"`
	Subject             string             `json:"subject"`
	ClientID            string             `json:"client_id"`
	Audience            string             `json:"audience"`
	Scopes              []string           `json:"scopes"`
	Provider            string             `json:"provider"`
	AccountID           *uuid.UUID         `json:"account_id"`
	AuthorizationCodeID uuid.UUID          `json:"authorization_code_id"`
	AccessTokenID       uuid.UUID          `json:"access_token_id"`
	ReplacedByID        *uuid.UUID         `json:"replaced_by_id"`
	IssuedAt            pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt          pgtype.Timestamptz `json:"last_used_at"`
	ConsumedAt          pgtype.Timestamptz `json:"consumed_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
}
