// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package oauthstoredb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAuthorizationCode = `-- name: ConsumeAuthorizationCode :one
UPDATE oauth_authorization_codes
   SET consumed_at = $2
 WHERE id = $1
   AND consumed_at IS NULL
RETURNING id, code_hash, client_id, redirect_uri, code_challenge, code_challenge_method, scopes, resource, subject, provider, account_id, issued_at, expires_at, consumed_at
`

type ConsumeAuthorizationCodeParams struct {
	ID         uuid.UUID          `json:"id"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
}

// THE LOAD-BEARING SINGLE-USE CONTROL. `AND consumed_at IS NULL` is what makes
// an authorization code single-use; it still holds if a future caller reaches
// this UPDATE without taking the row lock first. A non-matching predicate
// affects zero rows, which surfaces as pgx.ErrNoRows on this :one and is
// mapped to ErrCodeConsumed.
//
// Pinned DIRECTLY, at this level, by
// TestConsumeAuthorizationCode_PredicateRejectsConsumedRow — which issues this
// query against an already-consumed row on a plain pool connection, with no
// lock and no repository-level check in front of it, so deleting the predicate
// reddens that test. The post-lock consumed check in RedeemAuthorizationCode is
// the REDUNDANT short-circuit, not this.
func (q *Queries) ConsumeAuthorizationCode(ctx context.Context, arg ConsumeAuthorizationCodeParams) (OauthAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, consumeAuthorizationCode, arg.ID, arg.ConsumedAt)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ClientID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Scopes,
		&i.Resource,
		&i.Subject,
		&i.Provider,
		&i.AccountID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const consumeRefreshToken = `-- name: ConsumeRefreshToken :one
UPDATE oauth_refresh_tokens
   SET consumed_at = $2,
       replaced_by_id = $3
 WHERE id = $1
   AND consumed_at IS NULL
RETURNING id, token_hash, subject, client_id, audience, scopes, provider, account_id, authorization_code_id, access_token_id, replaced_by_id, issued_at, expires_at, last_used_at, consumed_at, revoked_at
`

type ConsumeRefreshTokenParams struct {
	ID           uuid.UUID          `json:"id"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	ReplacedByID *uuid.UUID         `json:"replaced_by_id"`
}

// Same load-bearing conditional shape as ConsumeAuthorizationCode: a rotated
// token can be consumed exactly once, and the second consume affects zero rows
// regardless of what checks ran before it. replaced_by_id records the successor,
// forming the OAuth 2.1 rotation chain.
func (q *Queries) ConsumeRefreshToken(ctx context.Context, arg ConsumeRefreshTokenParams) (OauthRefreshToken, error) {
	row := q.db.QueryRow(ctx, consumeRefreshToken, arg.ID, arg.ConsumedAt, arg.ReplacedByID)
	var i OauthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Subject,
		&i.ClientID,
		&i.Audience,
		&i.Scopes,
		&i.Provider,
		&i.AccountID,
		&i.AuthorizationCodeID,
		&i.AccessTokenID,
		&i.ReplacedByID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.ConsumedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createAccessToken = `-- name: CreateAccessToken :one
INSERT INTO oauth_access_tokens (
    id, token_hash, subject, client_id, audience, scopes, provider, account_id,
    authorization_code_id, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, token_hash, subject, client_id, audience, scopes, provider, account_id, authorization_code_id, issued_at, expires_at, last_used_at, revoked_at
`

type CreateAccessTokenParams struct {
	ID                  uuid.UUID          `json:"id"`
	TokenHash           string             `json:"token_hash"`
	Subject             string             `json:"subject"`
	ClientID            string             `json:"client_id"`
	Audience            string             `json:"audience"`
	Scopes              []string           `json:"scopes"`
	Provider            string             `json:"provider"`
	AccountID           *uuid.UUID         `json:"account_id"`
	AuthorizationCodeID uuid.UUID          `json:"authorization_code_id"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
}

// authorization_code_id is NOT NULL at the schema: every v0 token descends from
// an authorization code, which is what makes the whole-lineage revocation sweep
// reachable. On the rotation path the repository DERIVES this value from the
// presented refresh token's row rather than accepting it from the caller.
func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (OauthAccessToken, error) {
	row := q.db.QueryRow(ctx, createAccessToken,
		arg.ID,
		arg.TokenHash,
		arg.Subject,
		arg.ClientID,
		arg.Audience,
		arg.Scopes,
		arg.Provider,
		arg.AccountID,
		arg.AuthorizationCodeID,
		arg.ExpiresAt,
	)
	var i OauthAccessToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Subject,
		&i.ClientID,
		&i.Audience,
		&i.Scopes,
		&i.Provider,
		&i.AccountID,
		&i.AuthorizationCodeID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createAuthorizationCode = `-- name: CreateAuthorizationCode :one
INSERT INTO oauth_authorization_codes (
    id, code_hash, client_id, redirect_uri, code_challenge, code_challenge_method,
    scopes, resource, subject, provider, account_id, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, code_hash, client_id, redirect_uri, code_challenge, code_challenge_method, scopes, resource, subject, provider, account_id, issued_at, expires_at, consumed_at
`

type CreateAuthorizationCodeParams struct {
	ID                  uuid.UUID          `json:"id"`
	CodeHash            string             `json:"code_hash"`
	ClientID            string             `json:"client_id"`
	RedirectUri         string             `json:"redirect_uri"`
	CodeChallenge       string             `json:"code_challenge"`
	CodeChallengeMethod string             `json:"code_challenge_method"`
	Scopes              []string           `json:"scopes"`
	Resource            *string            `json:"resource"`
	Subject             string             `json:"subject"`
	Provider            string             `json:"provider"`
	AccountID           *uuid.UUID         `json:"account_id"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
}

// code_hash is the hex sha256 of the plaintext; the plaintext itself is never
// persisted and is returned to the caller exactly once, here.
func (q *Queries) CreateAuthorizationCode(ctx context.Context, arg CreateAuthorizationCodeParams) (OauthAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, createAuthorizationCode,
		arg.ID,
		arg.CodeHash,
		arg.ClientID,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.Scopes,
		arg.Resource,
		arg.Subject,
		arg.Provider,
		arg.AccountID,
		arg.ExpiresAt,
	)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ClientID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Scopes,
		&i.Resource,
		&i.Subject,
		&i.Provider,
		&i.AccountID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO oauth_refresh_tokens (
    id, token_hash, subject, client_id, audience, scopes, provider, account_id,
    authorization_code_id, access_token_id, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, token_hash, subject, client_id, audience, scopes, provider, account_id, authorization_code_id, access_token_id, replaced_by_id, issued_at, expires_at, last_used_at, consumed_at, revoked_at
`

type CreateRefreshTokenParams struct {
	ID                  uuid.UUID          `json:"id"`
	TokenHash           string             `json:"token_hash"`
	Subject             string             `json:"subject"`
	ClientID            string             `json:"client_id"`
	Audience            string             `json:"audience"`
	Scopes              []string           `json:"scopes"`
	Provider            string             `json:"provider"`
	AccountID           *uuid.UUID         `json:"account_id"`
	AuthorizationCodeID uuid.UUID          `json:"authorization_code_id"`
	AccessTokenID       uuid.UUID          `json:"access_token_id"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
}

// access_token_id pins the sibling access token minted in the same grant;
// authorization_code_id carries the lineage (NOT NULL, derived by the store).
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (OauthRefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.ID,
		arg.TokenHash,
		arg.Subject,
		arg.ClientID,
		arg.Audience,
		arg.Scopes,
		arg.Provider,
		arg.AccountID,
		arg.AuthorizationCodeID,
		arg.AccessTokenID,
		arg.ExpiresAt,
	)
	var i OauthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Subject,
		&i.ClientID,
		&i.Audience,
		&i.Scopes,
		&i.Provider,
		&i.AccountID,
		&i.AuthorizationCodeID,
		&i.AccessTokenID,
		&i.ReplacedByID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.ConsumedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAccessTokenByHash = `-- name: GetAccessTokenByHash :one
SELECT id, token_hash, subject, client_id, audience, scopes, provider, account_id, authorization_code_id, issued_at, expires_at, last_used_at, revoked_at FROM oauth_access_tokens
 WHERE token_hash = $1
`

// UNFILTERED ON revoked_at, DELIBERATELY. The absence of `AND revoked_at IS
// NULL` is the control: it lets the repository classify revoked → ErrRevoked
// instead of collapsing revocation into "no such token". A future
// "optimization" that re-adds that filter is a REGRESSION, not a speedup — the
// token_hash UNIQUE constraint's btree index serves this lookup either way.
// TestAuthenticateAccessToken_RevokedExpiredUnknownAreDistinct fails if the
// three outcomes collapse.
func (q *Queries) GetAccessTokenByHash(ctx context.Context, tokenHash string) (OauthAccessToken, error) {
	row := q.db.QueryRow(ctx, getAccessTokenByHash, tokenHash)
	var i OauthAccessToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Subject,
		&i.ClientID,
		&i.Audience,
		&i.Scopes,
		&i.Provider,
		&i.AccountID,
		&i.AuthorizationCodeID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAuthorizationCodeByHash = `-- name: GetAuthorizationCodeByHash :one
SELECT id, code_hash, client_id, redirect_uri, code_challenge, code_challenge_method, scopes, resource, subject, provider, account_id, issued_at, expires_at, consumed_at FROM oauth_authorization_codes
 WHERE code_hash = $1
`

// READ-ONLY load for verify-before-consume: #2391's token endpoint can
// validate client_id, redirect_uri, PKCE and resource and render a typed
// oauthas error WITHOUT burning the grant. Touches consumed_at never.
// Unfiltered on consumed_at/expires_at so the caller sees the real state.
func (q *Queries) GetAuthorizationCodeByHash(ctx context.Context, codeHash string) (OauthAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, getAuthorizationCodeByHash, codeHash)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ClientID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Scopes,
		&i.Resource,
		&i.Subject,
		&i.Provider,
		&i.AccountID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const getClientByClientID = `-- name: GetClientByClientID :one
SELECT id, provider, client_id, redirect_uris, grant_types, response_types, token_endpoint_auth_method, client_name, client_uri, logo_uri, scope, account_id, first_seen_at, updated_at FROM oauth_clients
 WHERE provider = $1
   AND client_id = $2
`

type GetClientByClientIDParams struct {
	Provider string `json:"provider"`
	ClientID string `json:"client_id"`
}

// Keyed on the forge-scoped composite, so the same CIMD URL under two
// providers is two distinct registrations.
func (q *Queries) GetClientByClientID(ctx context.Context, arg GetClientByClientIDParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getClientByClientID, arg.Provider, arg.ClientID)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ClientID,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.TokenEndpointAuthMethod,
		&i.ClientName,
		&i.ClientUri,
		&i.LogoUri,
		&i.Scope,
		&i.AccountID,
		&i.FirstSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, token_hash, subject, client_id, audience, scopes, provider, account_id, authorization_code_id, access_token_id, replaced_by_id, issued_at, expires_at, last_used_at, consumed_at, revoked_at FROM oauth_refresh_tokens
 WHERE token_hash = $1
`

// UNFILTERED for the same reason as GetAccessTokenByHash: the rotation path
// must distinguish revoked from consumed from nonexistent, and a filter here
// would erase the reuse signal entirely.
func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (OauthRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i OauthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Subject,
		&i.ClientID,
		&i.Audience,
		&i.Scopes,
		&i.Provider,
		&i.AccountID,
		&i.AuthorizationCodeID,
		&i.AccessTokenID,
		&i.ReplacedByID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.ConsumedAt,
		&i.RevokedAt,
	)
	return i, err
}

const lockAuthorizationCodeByHash = `-- name: LockAuthorizationCodeByHash :one
SELECT id, code_hash, client_id, redirect_uri, code_challenge, code_challenge_method, scopes, resource, subject, provider, account_id, issued_at, expires_at, consumed_at FROM oauth_authorization_codes
 WHERE code_hash = $1
   FOR UPDATE
`

// The in-transaction load for RedeemAuthorizationCode. FOR UPDATE serializes
// concurrent redemptions of the same code: under READ COMMITTED the loser
// blocks until the winner commits and then re-evaluates the row at its new
// version, so it observes consumed_at as SET rather than the NULL its pre-lock
// snapshot held.
func (q *Queries) LockAuthorizationCodeByHash(ctx context.Context, codeHash string) (OauthAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, lockAuthorizationCodeByHash, codeHash)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ClientID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Scopes,
		&i.Resource,
		&i.Subject,
		&i.Provider,
		&i.AccountID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const lockAuthorizationCodeByID = `-- name: LockAuthorizationCodeByID :exec
SELECT id FROM oauth_authorization_codes
 WHERE id = $1
   FOR UPDATE
`

// THE LINEAGE LOCK. The authorization-code row is the mutex for its WHOLE
// lineage: RotateRefreshToken and RevokeGrantsForCode both take it FOR UPDATE
// before reading or mutating any descendant, so every rotation and every sweep
// of one lineage is serialized.
//
// Without it the whole-lineage revocation guarantee does NOT hold under
// concurrency. Row locks on the individual token rows are not enough: the sweep
// UPDATEs (`WHERE authorization_code_id = $1`) take their statement snapshot
// when the statement starts, so a rotation that INSERTs a successor pair and
// commits after that instant produces rows the sweep can never see — a usable
// descendant credential surviving reuse detection. Serializing on the code row
// forces one of two safe orders instead: the rotation commits first and the
// sweep's later snapshot includes its successor, or the sweep commits first and
// the rotation's post-lock re-read observes revoked_at set and mints nothing.
//
// Selecting only `id` keeps this a pure lock acquisition. A missing row locks
// nothing and is NOT an error (RevokeGrantsForCode on an unknown code id must
// still revoke zero rows rather than fail), which is why this is :exec.
func (q *Queries) LockAuthorizationCodeByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockAuthorizationCodeByID, id)
	return err
}

const lockRefreshTokenByHash = `-- name: LockRefreshTokenByHash :one
SELECT id, token_hash, subject, client_id, audience, scopes, provider, account_id, authorization_code_id, access_token_id, replaced_by_id, issued_at, expires_at, last_used_at, consumed_at, revoked_at FROM oauth_refresh_tokens
 WHERE token_hash = $1
   FOR UPDATE
`

// The in-transaction load for RotateRefreshToken. Holding this lock is what
// keeps the reuse-detection sweep atomic with the classification that triggers
// it.
func (q *Queries) LockRefreshTokenByHash(ctx context.Context, tokenHash string) (OauthRefreshToken, error) {
	row := q.db.QueryRow(ctx, lockRefreshTokenByHash, tokenHash)
	var i OauthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Subject,
		&i.ClientID,
		&i.Audience,
		&i.Scopes,
		&i.Provider,
		&i.AccountID,
		&i.AuthorizationCodeID,
		&i.AccessTokenID,
		&i.ReplacedByID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.ConsumedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAccessToken = `-- name: RevokeAccessToken :one
UPDATE oauth_access_tokens
   SET revoked_at = COALESCE(revoked_at, $2)
 WHERE id = $1
RETURNING id, token_hash, subject, client_id, audience, scopes, provider, account_id, authorization_code_id, issued_at, expires_at, last_used_at, revoked_at
`

type RevokeAccessTokenParams struct {
	ID        uuid.UUID          `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

// Idempotent via COALESCE (mirroring apitoken's RevokeToken): a second revoke
// returns the existing row with its original revoked_at.
func (q *Queries) RevokeAccessToken(ctx context.Context, arg RevokeAccessTokenParams) (OauthAccessToken, error) {
	row := q.db.QueryRow(ctx, revokeAccessToken, arg.ID, arg.RevokedAt)
	var i OauthAccessToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Subject,
		&i.ClientID,
		&i.Audience,
		&i.Scopes,
		&i.Provider,
		&i.AccountID,
		&i.AuthorizationCodeID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAccessTokensForCode = `-- name: RevokeAccessTokensForCode :execrows
UPDATE oauth_access_tokens
   SET revoked_at = $2
 WHERE authorization_code_id = $1
   AND revoked_at IS NULL
`

type RevokeAccessTokensForCodeParams struct {
	AuthorizationCodeID uuid.UUID          `json:"authorization_code_id"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
}

// Half of the RFC 6749 §4.1.2 replay response: revoke every still-active access
// token descended from one authorization code. Served by
// oauth_access_tokens_authorization_code_id_idx.
func (q *Queries) RevokeAccessTokensForCode(ctx context.Context, arg RevokeAccessTokensForCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAccessTokensForCode, arg.AuthorizationCodeID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :one
UPDATE oauth_refresh_tokens
   SET revoked_at = COALESCE(revoked_at, $2)
 WHERE id = $1
RETURNING id, token_hash, subject, client_id, audience, scopes, provider, account_id, authorization_code_id, access_token_id, replaced_by_id, issued_at, expires_at, last_used_at, consumed_at, revoked_at
`

type RevokeRefreshTokenParams struct {
	ID        uuid.UUID          `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

// Idempotent via COALESCE, as RevokeAccessToken.
func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) (OauthRefreshToken, error) {
	row := q.db.QueryRow(ctx, revokeRefreshToken, arg.ID, arg.RevokedAt)
	var i OauthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Subject,
		&i.ClientID,
		&i.Audience,
		&i.Scopes,
		&i.Provider,
		&i.AccountID,
		&i.AuthorizationCodeID,
		&i.AccessTokenID,
		&i.ReplacedByID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.ConsumedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeRefreshTokensForCode = `-- name: RevokeRefreshTokensForCode :execrows
UPDATE oauth_refresh_tokens
   SET revoked_at = $2
 WHERE authorization_code_id = $1
   AND revoked_at IS NULL
`

type RevokeRefreshTokensForCodeParams struct {
	AuthorizationCodeID uuid.UUID          `json:"authorization_code_id"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
}

// The other half of the §4.1.2 replay response. Served by
// oauth_refresh_tokens_authorization_code_id_idx.
func (q *Queries) RevokeRefreshTokensForCode(ctx context.Context, arg RevokeRefreshTokensForCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokensForCode, arg.AuthorizationCodeID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAccessTokenLastUsed = `-- name: TouchAccessTokenLastUsed :exec
UPDATE oauth_access_tokens
   SET last_used_at = $2
 WHERE id = $1
`

type TouchAccessTokenLastUsedParams struct {
	ID         uuid.UUID          `json:"id"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

// Best-effort stamp on a successful authentication; a failure here does not
// invalidate the auth decision.
func (q *Queries) TouchAccessTokenLastUsed(ctx context.Context, arg TouchAccessTokenLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchAccessTokenLastUsed, arg.ID, arg.LastUsedAt)
	return err
}

const upsertClient = `-- name: UpsertClient :one

INSERT INTO oauth_clients (
    id, provider, client_id, redirect_uris, grant_types, response_types,
    token_endpoint_auth_method, client_name, client_uri, logo_uri, scope, account_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (provider, client_id) DO UPDATE
   SET redirect_uris              = EXCLUDED.redirect_uris,
       grant_types                = EXCLUDED.grant_types,
       response_types             = EXCLUDED.response_types,
       token_endpoint_auth_method = EXCLUDED.token_endpoint_auth_method,
       client_name                = EXCLUDED.client_name,
       client_uri                 = EXCLUDED.client_uri,
       logo_uri                   = EXCLUDED.logo_uri,
       scope                      = EXCLUDED.scope,
       account_id                 = EXCLUDED.account_id,
       updated_at                 = now()
RETURNING id, provider, client_id, redirect_uris, grant_types, response_types, token_endpoint_auth_method, client_name, client_uri, logo_uri, scope, account_id, first_seen_at, updated_at
`

type UpsertClientParams struct {
	ID                      uuid.UUID  `json:"id"`
	Provider                string     `json:"provider"`
	ClientID                string     `json:"client_id"`
	RedirectUris            []string   `json:"redirect_uris"`
	GrantTypes              []string   `json:"grant_types"`
	ResponseTypes           []string   `json:"response_types"`
	TokenEndpointAuthMethod string     `json:"token_endpoint_auth_method"`
	ClientName              *string    `json:"client_name"`
	ClientUri               *string    `json:"client_uri"`
	LogoUri                 *string    `json:"logo_uri"`
	Scope                   *string    `json:"scope"`
	AccountID               *uuid.UUID `json:"account_id"`
}

// OAuth 2.1 authorization-server storage queries (E66.18 / #2433, ADR-076).
// sqlc generates typed Go into ./db per backend/sqlc.yaml. Schema:
// internal/postgres/migrations/0063_oauth_as_storage.up.sql.
//
// Every query below is keyed either on a 256-bit credential hash or on a row
// id. NONE filters on account_id — see 0063's header part (c): ID-based
// operations carry no database-level tenant check today; that authorization
// decision belongs to the already-authenticated caller in #2391.
// REFRESH-ON-FETCH (not pin-at-first-use): a re-fetched CIMD document
// OVERWRITES the persisted metadata columns. The document is authoritative and
// client-controlled by design, so a client that rotates its redirect URIs must
// not be permanently broken by a first-use snapshot; the fetcher's TTL bounds
// staleness. first_seen_at is preserved by the DO UPDATE (it is not in the SET
// list); updated_at moves on every refresh.
func (q *Queries) UpsertClient(ctx context.Context, arg UpsertClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, upsertClient,
		arg.ID,
		arg.Provider,
		arg.ClientID,
		arg.RedirectUris,
		arg.GrantTypes,
		arg.ResponseTypes,
		arg.TokenEndpointAuthMethod,
		arg.ClientName,
		arg.ClientUri,
		arg.LogoUri,
		arg.Scope,
		arg.AccountID,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ClientID,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.TokenEndpointAuthMethod,
		&i.ClientName,
		&i.ClientUri,
		&i.LogoUri,
		&i.Scope,
		&i.AccountID,
		&i.FirstSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}
