-- 0070: stages.progress — the runner's mid-execution stage_progress
-- heartbeat, projected onto the stage row so an operator poll returns
-- last_event / turns / tokens instead of a single 'running' bit (E48.96 /
-- #2541).
--
-- Additive, nullable, no backfill — byte-for-byte the shape migration 0035
-- used for scope_completeness_park: NULL for every stage that has not yet
-- reported a heartbeat, and for every stage on a run that predates this
-- column. The payload is written last-writer-wins by the progress ingest
-- endpoint every ~15s for the life of a running stage and read back by the
-- two stage observability handlers; no code outside the three dedicated
-- progress-only queries touches it, so no existing stages SELECT list or
-- sqlc Stage model changes.
--
-- updated_at SIDE EFFECT + CONSUMER AUDIT (#2541 approval condition 4). The
-- BEFORE-UPDATE trigger stages_set_updated_at (migration 0001) fires on ANY
-- stages UPDATE, so each heartbeat bumps stages.updated_at every ~15s for the
-- life of a running stage. Audited every stages.updated_at reader (queries.sql
-- ORDER BY updated_at: ListStagesAwaitingApproval, ListReviewStagesAwaitingApproval,
-- ListDeployStagesAwaitingDeployment, ListDeployStagesRollbackPending,
-- ListStagesDispatched, ListStagesAwaitingChildren; plus every Stage.UpdatedAt
-- Go read). All but one filter to states in which NO agent runs (awaiting_*,
-- deploy_*), so a heartbeat — which fires only during agent EXECUTION — never
-- touches their rows. The ONE genuine consumer is the dispatch watchdog
-- (backend/internal/dispatchwatchdog): it computes now-UpdatedAt for state=
-- 'dispatched' stages and fails infra-stuck ones (category C). A stage stays
-- 'dispatched' DURING agent execution (trace.go transitions dispatched->running
-- ->terminal only at trace-upload time), so heartbeats DO bump a dispatched
-- stage's updated_at. This is a genuine SEMANTIC CHANGE the reviewer must weigh
-- (a design question, surfaced not absorbed): the watchdog now measures "time
-- since last heartbeat" rather than "time since dispatch". Its PRIMARY purpose
-- is preserved — a truly infra-stuck stage has no runner, emits no heartbeat, so
-- updated_at stays at dispatch time and it still fires — but a legitimately
-- long-running agent that heartbeats no longer trips it. See the run README +
-- the PR body's condition-4 note.
--
-- NOT OPERATOR-ACCEPTED (fix-up). Condition 4 RESERVED this call for the
-- operator ("stop and say so — that is a design question, not something to
-- absorb"). This migration does not decide it: merge is GATED on the operator
-- either explicitly signing off on the tradeoff above OR directing a follow-up
-- that scopes the watchdog off progress-only bumps (e.g. a dedicated heartbeat
-- timestamp instead of relying on the generic stages_set_updated_at trigger).
-- Surfaced here; decided by the operator at the gate.
ALTER TABLE stages ADD COLUMN progress JSONB;
