-- 0070: stages.progress — the runner's mid-execution stage_progress
-- heartbeat, projected onto the stage row so an operator poll returns
-- last_event / turns / tokens instead of a single 'running' bit (E48.96 /
-- #2541).
--
-- Additive, nullable, no backfill — byte-for-byte the shape migration 0035
-- used for scope_completeness_park: NULL for every stage that has not yet
-- reported a heartbeat, and for every stage on a run that predates this
-- column. The payload is written last-writer-wins by the progress ingest
-- endpoint every ~15s for the life of a running stage and read back by the
-- two stage observability handlers; no code outside the three dedicated
-- progress-only queries touches it, so no existing stages SELECT list or
-- sqlc Stage model changes.
--
-- updated_at SIDE EFFECT + CONSUMER AUDIT (#2541 approval condition 4). The
-- BEFORE-UPDATE trigger stages_set_updated_at (migration 0001) fires on ANY
-- stages UPDATE, so each heartbeat bumps stages.updated_at every ~15s for the
-- life of a running stage. Audited every stages.updated_at reader (queries.sql
-- ORDER BY updated_at: ListStagesAwaitingApproval, ListReviewStagesAwaitingApproval,
-- ListDeployStagesAwaitingDeployment, ListDeployStagesRollbackPending,
-- ListStagesDispatched, ListStagesAwaitingChildren; plus every Stage.UpdatedAt
-- Go read). All but one filter to states in which NO agent runs (awaiting_*,
-- deploy_*), so a heartbeat — which fires only during agent EXECUTION — never
-- touches their rows. The ONE genuine consumer is the dispatch watchdog
-- (backend/internal/dispatchwatchdog): it computes now-UpdatedAt for state=
-- 'dispatched' stages and fails infra-stuck ones (category C). A stage stays
-- 'dispatched' DURING agent execution (trace.go transitions dispatched->running
-- ->terminal only at trace-upload time), so heartbeats DO bump a dispatched
-- stage's updated_at. This bump is BY DESIGN and remains — every ~15s the
-- heartbeat writes the progress column and the 0001 trigger stamps updated_at.
--
-- RESOLVED (#2744). The dispatch watchdog NO LONGER reads updated_at, so the
-- heartbeat can no longer suppress it. Migration 0072 (stages.dispatched_at)
-- adds a DEDICATED dispatch timestamp stamped only on the transition INTO
-- 'dispatched' by a transition-keyed trigger; the watchdog measures its deadline
-- from that column, which a progress-only UPDATE cannot advance. What was an
-- accepted tradeoff at #2541 (the watchdog measuring time-since-last-heartbeat)
-- is therefore closed, not merely bounded by the runner's 3600s wall clock. See
-- migration 0072, backend/internal/dispatchwatchdog, and the run README.
ALTER TABLE stages ADD COLUMN progress JSONB;
