// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package scopeamendmentdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countScopeAmendmentsByStage = `-- name: CountScopeAmendmentsByStage :one
SELECT COUNT(*) FROM scope_amendments
 WHERE stage_id = $1
`

// Budget count is status-blind: a denied request still consumed an
// operator interruption.
func (q *Queries) CountScopeAmendmentsByStage(ctx context.Context, stageID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countScopeAmendmentsByStage, stageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScopeAmendment = `-- name: CreateScopeAmendment :one

INSERT INTO scope_amendments (id, run_id, stage_id, paths, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, run_id, stage_id, paths, reason, status, decision_reason, decided_by, requested_at, decided_at
`

type CreateScopeAmendmentParams struct {
	ID      uuid.UUID `json:"id"`
	RunID   uuid.UUID `json:"run_id"`
	StageID uuid.UUID `json:"stage_id"`
	Paths   []byte    `json:"paths"`
	Reason  string    `json:"reason"`
}

// Scope amendment queries (E22.X / #961). sqlc generates typed Go
// into ./db per backend/sqlc.yaml.
func (q *Queries) CreateScopeAmendment(ctx context.Context, arg CreateScopeAmendmentParams) (ScopeAmendment, error) {
	row := q.db.QueryRow(ctx, createScopeAmendment,
		arg.ID,
		arg.RunID,
		arg.StageID,
		arg.Paths,
		arg.Reason,
	)
	var i ScopeAmendment
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StageID,
		&i.Paths,
		&i.Reason,
		&i.Status,
		&i.DecisionReason,
		&i.DecidedBy,
		&i.RequestedAt,
		&i.DecidedAt,
	)
	return i, err
}

const decideScopeAmendment = `-- name: DecideScopeAmendment :one
UPDATE scope_amendments
   SET status = $2,
       decision_reason = $3,
       decided_by = $4,
       decided_at = $5
 WHERE id = $1
   AND status = 'pending'
RETURNING id, run_id, stage_id, paths, reason, status, decision_reason, decided_by, requested_at, decided_at
`

type DecideScopeAmendmentParams struct {
	ID             uuid.UUID          `json:"id"`
	Status         string             `json:"status"`
	DecisionReason *string            `json:"decision_reason"`
	DecidedBy      *string            `json:"decided_by"`
	DecidedAt      pgtype.Timestamptz `json:"decided_at"`
}

// Pending-only guard in the WHERE clause makes the decision
// transition atomic: a second decide matches zero rows and the
// caller maps that to ErrAlreadyDecided (or ErrNotFound).
func (q *Queries) DecideScopeAmendment(ctx context.Context, arg DecideScopeAmendmentParams) (ScopeAmendment, error) {
	row := q.db.QueryRow(ctx, decideScopeAmendment,
		arg.ID,
		arg.Status,
		arg.DecisionReason,
		arg.DecidedBy,
		arg.DecidedAt,
	)
	var i ScopeAmendment
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StageID,
		&i.Paths,
		&i.Reason,
		&i.Status,
		&i.DecisionReason,
		&i.DecidedBy,
		&i.RequestedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getScopeAmendmentByID = `-- name: GetScopeAmendmentByID :one
SELECT id, run_id, stage_id, paths, reason, status, decision_reason, decided_by, requested_at, decided_at FROM scope_amendments
 WHERE id = $1
`

func (q *Queries) GetScopeAmendmentByID(ctx context.Context, id uuid.UUID) (ScopeAmendment, error) {
	row := q.db.QueryRow(ctx, getScopeAmendmentByID, id)
	var i ScopeAmendment
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StageID,
		&i.Paths,
		&i.Reason,
		&i.Status,
		&i.DecisionReason,
		&i.DecidedBy,
		&i.RequestedAt,
		&i.DecidedAt,
	)
	return i, err
}

const listScopeAmendmentsByRun = `-- name: ListScopeAmendmentsByRun :many
SELECT id, run_id, stage_id, paths, reason, status, decision_reason, decided_by, requested_at, decided_at FROM scope_amendments
 WHERE run_id = $1
 ORDER BY requested_at ASC, id ASC
`

// Oldest first so the list endpoint and the fold both see requests
// in submission order.
func (q *Queries) ListScopeAmendmentsByRun(ctx context.Context, runID uuid.UUID) ([]ScopeAmendment, error) {
	rows, err := q.db.Query(ctx, listScopeAmendmentsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScopeAmendment
	for rows.Next() {
		var i ScopeAmendment
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StageID,
			&i.Paths,
			&i.Reason,
			&i.Status,
			&i.DecisionReason,
			&i.DecidedBy,
			&i.RequestedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
