// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package campaigndb

import (
	"context"

	"github.com/google/uuid"
)

const createCampaign = `-- name: CreateCampaign :one

INSERT INTO campaigns (id, repo, epic_ref, state, pause_policy, operator_agent)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, repo, epic_ref, state, created_at, updated_at, pause_policy, operator_agent
`

type CreateCampaignParams struct {
	ID            uuid.UUID `json:"id"`
	Repo          string    `json:"repo"`
	EpicRef       string    `json:"epic_ref"`
	State         string    `json:"state"`
	PausePolicy   string    `json:"pause_policy"`
	OperatorAgent []byte    `json:"operator_agent"`
}

// Campaign / campaign-item queries consumed by the postgres adapter for the
// campaign.Repository interface (ADR-047 / #1437, E25.2). sqlc generates
// typed Go into ./db per the `campaign` block in /backend/sqlc.yaml. Mirrors
// internal/run/queries.sql.
func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.ID,
		arg.Repo,
		arg.EpicRef,
		arg.State,
		arg.PausePolicy,
		arg.OperatorAgent,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.EpicRef,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausePolicy,
		&i.OperatorAgent,
	)
	return i, err
}

const createCampaignItem = `-- name: CreateCampaignItem :one
INSERT INTO campaign_items (id, campaign_id, issue_ref, depends_on, state)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, campaign_id, issue_ref, depends_on, run_id, state, created_at, updated_at, pause_reason
`

type CreateCampaignItemParams struct {
	ID         uuid.UUID `json:"id"`
	CampaignID uuid.UUID `json:"campaign_id"`
	IssueRef   string    `json:"issue_ref"`
	DependsOn  []byte    `json:"depends_on"`
	State      string    `json:"state"`
}

func (q *Queries) CreateCampaignItem(ctx context.Context, arg CreateCampaignItemParams) (CampaignItem, error) {
	row := q.db.QueryRow(ctx, createCampaignItem,
		arg.ID,
		arg.CampaignID,
		arg.IssueRef,
		arg.DependsOn,
		arg.State,
	)
	var i CampaignItem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.IssueRef,
		&i.DependsOn,
		&i.RunID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PauseReason,
	)
	return i, err
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, repo, epic_ref, state, created_at, updated_at, pause_policy, operator_agent FROM campaigns WHERE id = $1
`

func (q *Queries) GetCampaign(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.EpicRef,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausePolicy,
		&i.OperatorAgent,
	)
	return i, err
}

const getCampaignItem = `-- name: GetCampaignItem :one
SELECT id, campaign_id, issue_ref, depends_on, run_id, state, created_at, updated_at, pause_reason FROM campaign_items WHERE id = $1
`

func (q *Queries) GetCampaignItem(ctx context.Context, id uuid.UUID) (CampaignItem, error) {
	row := q.db.QueryRow(ctx, getCampaignItem, id)
	var i CampaignItem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.IssueRef,
		&i.DependsOn,
		&i.RunID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PauseReason,
	)
	return i, err
}

const listCampaignItemsForCampaign = `-- name: ListCampaignItemsForCampaign :many
SELECT id, campaign_id, issue_ref, depends_on, run_id, state, created_at, updated_at, pause_reason FROM campaign_items
 WHERE campaign_id = $1
 ORDER BY created_at ASC, id ASC
`

// Insertion order (created_at ASC + id tiebreak) so the campaign's items
// render in the order they were assembled.
func (q *Queries) ListCampaignItemsForCampaign(ctx context.Context, campaignID uuid.UUID) ([]CampaignItem, error) {
	rows, err := q.db.Query(ctx, listCampaignItemsForCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampaignItem
	for rows.Next() {
		var i CampaignItem
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.IssueRef,
			&i.DependsOn,
			&i.RunID,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PauseReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignItemsForRun = `-- name: ListCampaignItemsForRun :many
SELECT id, campaign_id, issue_ref, depends_on, run_id, state, created_at, updated_at, pause_reason FROM campaign_items
 WHERE run_id = $1
 ORDER BY created_at ASC, id ASC
`

// The reverse-discovery query ("which campaign owns this run") served by
// the campaign_items_run_idx index. Ordered created_at ASC for a stable
// result.
func (q *Queries) ListCampaignItemsForRun(ctx context.Context, runID *uuid.UUID) ([]CampaignItem, error) {
	rows, err := q.db.Query(ctx, listCampaignItemsForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampaignItem
	for rows.Next() {
		var i CampaignItem
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.IssueRef,
			&i.DependsOn,
			&i.RunID,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PauseReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, repo, epic_ref, state, created_at, updated_at, pause_policy, operator_agent FROM campaigns
 WHERE ($1::text = '' OR repo = $1)
   AND ($2::text = '' OR state = $2)
 ORDER BY created_at DESC, id DESC
 LIMIT $4 OFFSET $3
`

type ListCampaignsParams struct {
	Repo  string `json:"repo"`
	State string `json:"state"`
	Off   int32  `json:"off"`
	Lim   int32  `json:"lim"`
}

// Empty string in any filter means "no constraint." created_at DESC + id
// DESC tiebreak so paginations are stable across concurrent inserts at the
// same created_at microsecond.
func (q *Queries) ListCampaigns(ctx context.Context, arg ListCampaignsParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaigns,
		arg.Repo,
		arg.State,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Repo,
			&i.EpicRef,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausePolicy,
			&i.OperatorAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCampaignForUpdate = `-- name: LockCampaignForUpdate :one
SELECT id, repo, epic_ref, state, created_at, updated_at, pause_policy, operator_agent FROM campaigns WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockCampaignForUpdate(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, lockCampaignForUpdate, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.EpicRef,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausePolicy,
		&i.OperatorAgent,
	)
	return i, err
}

const lockCampaignItemForUpdate = `-- name: LockCampaignItemForUpdate :one
SELECT id, campaign_id, issue_ref, depends_on, run_id, state, created_at, updated_at, pause_reason FROM campaign_items WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockCampaignItemForUpdate(ctx context.Context, id uuid.UUID) (CampaignItem, error) {
	row := q.db.QueryRow(ctx, lockCampaignItemForUpdate, id)
	var i CampaignItem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.IssueRef,
		&i.DependsOn,
		&i.RunID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PauseReason,
	)
	return i, err
}

const setCampaignItemPause = `-- name: SetCampaignItemPause :one
UPDATE campaign_items
   SET state = 'paused', pause_reason = $2
 WHERE id = $1
RETURNING id, campaign_id, issue_ref, depends_on, run_id, state, created_at, updated_at, pause_reason
`

type SetCampaignItemPauseParams struct {
	ID          uuid.UUID `json:"id"`
	PauseReason []byte    `json:"pause_reason"`
}

// Pauses an item: sets state='paused' and records the pause_reason JSONB,
// applied under the existing LockCampaignItemForUpdate FOR UPDATE lock so the
// running→paused transition is serialized like the other state moves (E25.7).
func (q *Queries) SetCampaignItemPause(ctx context.Context, arg SetCampaignItemPauseParams) (CampaignItem, error) {
	row := q.db.QueryRow(ctx, setCampaignItemPause, arg.ID, arg.PauseReason)
	var i CampaignItem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.IssueRef,
		&i.DependsOn,
		&i.RunID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PauseReason,
	)
	return i, err
}

const setCampaignItemRun = `-- name: SetCampaignItemRun :one
UPDATE campaign_items
   SET run_id = $2
 WHERE id = $1
RETURNING id, campaign_id, issue_ref, depends_on, run_id, state, created_at, updated_at, pause_reason
`

type SetCampaignItemRunParams struct {
	ID    uuid.UUID  `json:"id"`
	RunID *uuid.UUID `json:"run_id"`
}

// Attaches (or clears, when $2 IS NULL) the run linkage on an item.
// Idempotent: re-setting the same value is a no-op the trigger keeps as a
// no-op against updated_at (assignment of identical value).
func (q *Queries) SetCampaignItemRun(ctx context.Context, arg SetCampaignItemRunParams) (CampaignItem, error) {
	row := q.db.QueryRow(ctx, setCampaignItemRun, arg.ID, arg.RunID)
	var i CampaignItem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.IssueRef,
		&i.DependsOn,
		&i.RunID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PauseReason,
	)
	return i, err
}

const updateCampaignItemState = `-- name: UpdateCampaignItemState :one
UPDATE campaign_items
   SET state = $2
 WHERE id = $1
RETURNING id, campaign_id, issue_ref, depends_on, run_id, state, created_at, updated_at, pause_reason
`

type UpdateCampaignItemStateParams struct {
	ID    uuid.UUID `json:"id"`
	State string    `json:"state"`
}

func (q *Queries) UpdateCampaignItemState(ctx context.Context, arg UpdateCampaignItemStateParams) (CampaignItem, error) {
	row := q.db.QueryRow(ctx, updateCampaignItemState, arg.ID, arg.State)
	var i CampaignItem
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.IssueRef,
		&i.DependsOn,
		&i.RunID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PauseReason,
	)
	return i, err
}

const updateCampaignState = `-- name: UpdateCampaignState :one
UPDATE campaigns
   SET state = $2
 WHERE id = $1
RETURNING id, repo, epic_ref, state, created_at, updated_at, pause_policy, operator_agent
`

type UpdateCampaignStateParams struct {
	ID    uuid.UUID `json:"id"`
	State string    `json:"state"`
}

func (q *Queries) UpdateCampaignState(ctx context.Context, arg UpdateCampaignStateParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignState, arg.ID, arg.State)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.EpicRef,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausePolicy,
		&i.OperatorAgent,
	)
	return i, err
}
