{{- if eq .Values.deployment.mode "allInOne" -}}
{{- include "fishhawk.validateSecrets" . -}}
{{- include "fishhawk.validateTopology" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fishhawk.fullname" . }}
  labels:
    {{- include "fishhawk.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fishhawk.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fishhawk.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "fishhawk.fishhawkdPodSpec" (dict "root" . "role" "all") | nindent 6 }}
{{- end -}}
