// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package artifactdb

import (
	"context"

	"github.com/google/uuid"
)

const createArtifact = `-- name: CreateArtifact :one

INSERT INTO artifacts (id, stage_id, kind, schema_version, content, content_hash)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, stage_id, kind, schema_version, content, content_hash, created_at
`

type CreateArtifactParams struct {
	ID            uuid.UUID `json:"id"`
	StageID       uuid.UUID `json:"stage_id"`
	Kind          string    `json:"kind"`
	SchemaVersion *string   `json:"schema_version"`
	Content       []byte    `json:"content"`
	ContentHash   string    `json:"content_hash"`
}

// Artifact queries consumed by the postgres adapter for the
// artifact.Repository interface (E2.1 / #22).
func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.ID,
		arg.StageID,
		arg.Kind,
		arg.SchemaVersion,
		arg.Content,
		arg.ContentHash,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.StageID,
		&i.Kind,
		&i.SchemaVersion,
		&i.Content,
		&i.ContentHash,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, stage_id, kind, schema_version, content, content_hash, created_at FROM artifacts WHERE id = $1
`

func (q *Queries) GetArtifact(ctx context.Context, id uuid.UUID) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.StageID,
		&i.Kind,
		&i.SchemaVersion,
		&i.Content,
		&i.ContentHash,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactByHash = `-- name: GetArtifactByHash :one
SELECT id, stage_id, kind, schema_version, content, content_hash, created_at FROM artifacts
WHERE stage_id = $1 AND content_hash = $2
`

type GetArtifactByHashParams struct {
	StageID     uuid.UUID `json:"stage_id"`
	ContentHash string    `json:"content_hash"`
}

// Look up an existing artifact by content hash within a stage. Used
// when re-uploading the same plan during retry — the dedup avoids
// a second copy of identical bytes in the audit log.
func (q *Queries) GetArtifactByHash(ctx context.Context, arg GetArtifactByHashParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifactByHash, arg.StageID, arg.ContentHash)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.StageID,
		&i.Kind,
		&i.SchemaVersion,
		&i.Content,
		&i.ContentHash,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifactsForStage = `-- name: ListArtifactsForStage :many
SELECT id, stage_id, kind, schema_version, content, content_hash, created_at FROM artifacts
WHERE stage_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListArtifactsForStage(ctx context.Context, stageID uuid.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsForStage, stageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.StageID,
			&i.Kind,
			&i.SchemaVersion,
			&i.Content,
			&i.ContentHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
