// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package mcptokendb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMCPToken = `-- name: CreateMCPToken :one

INSERT INTO mcp_tokens (id, run_id, token_hash, expires_at, scopes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, run_id, token_hash, issued_at, expires_at, last_used_at, revoked_at, scopes
`

type CreateMCPTokenParams struct {
	ID        uuid.UUID          `json:"id"`
	RunID     uuid.UUID          `json:"run_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Scopes    []string           `json:"scopes"`
}

// MCP token queries (E19.8 / #348). sqlc generates typed Go into
// ./db per backend/sqlc.yaml.
func (q *Queries) CreateMCPToken(ctx context.Context, arg CreateMCPTokenParams) (McpToken, error) {
	row := q.db.QueryRow(ctx, createMCPToken,
		arg.ID,
		arg.RunID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Scopes,
	)
	var i McpToken
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.Scopes,
	)
	return i, err
}

const getMCPTokenByHash = `-- name: GetMCPTokenByHash :one
SELECT id, run_id, token_hash, issued_at, expires_at, last_used_at, revoked_at, scopes FROM mcp_tokens
 WHERE token_hash = $1
   AND revoked_at IS NULL
`

// Active-only: revoked tokens never authenticate. Expiry is
// enforced row-level by the caller (the auth path needs to
// differentiate ErrExpired from ErrNotFound for observability).
func (q *Queries) GetMCPTokenByHash(ctx context.Context, tokenHash string) (McpToken, error) {
	row := q.db.QueryRow(ctx, getMCPTokenByHash, tokenHash)
	var i McpToken
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.Scopes,
	)
	return i, err
}

const getMCPTokenByID = `-- name: GetMCPTokenByID :one
SELECT id, run_id, token_hash, issued_at, expires_at, last_used_at, revoked_at, scopes FROM mcp_tokens
 WHERE id = $1
`

// Returns the row regardless of revocation / expiry state so
// handlers can return idempotent 204s on revoke.
func (q *Queries) GetMCPTokenByID(ctx context.Context, id uuid.UUID) (McpToken, error) {
	row := q.db.QueryRow(ctx, getMCPTokenByID, id)
	var i McpToken
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.Scopes,
	)
	return i, err
}

const revokeMCPToken = `-- name: RevokeMCPToken :one
UPDATE mcp_tokens
   SET revoked_at = COALESCE(revoked_at, $2)
 WHERE id = $1
RETURNING id, run_id, token_hash, issued_at, expires_at, last_used_at, revoked_at, scopes
`

type RevokeMCPTokenParams struct {
	ID        uuid.UUID          `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

// Idempotent: if revoked_at is already set, return the existing
// row unchanged.
func (q *Queries) RevokeMCPToken(ctx context.Context, arg RevokeMCPTokenParams) (McpToken, error) {
	row := q.db.QueryRow(ctx, revokeMCPToken, arg.ID, arg.RevokedAt)
	var i McpToken
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.Scopes,
	)
	return i, err
}

const revokeMCPTokensForRun = `-- name: RevokeMCPTokensForRun :execrows
UPDATE mcp_tokens
   SET revoked_at = $2
 WHERE run_id = $1
   AND revoked_at IS NULL
`

type RevokeMCPTokensForRunParams struct {
	RunID     uuid.UUID          `json:"run_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

// Revoke every active token for the run. Returns the count of
// newly-revoked rows (already-revoked rows aren't double-counted
// because of the partial-index-friendly WHERE clause).
func (q *Queries) RevokeMCPTokensForRun(ctx context.Context, arg RevokeMCPTokensForRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeMCPTokensForRun, arg.RunID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchMCPTokenLastUsed = `-- name: TouchMCPTokenLastUsed :exec
UPDATE mcp_tokens
   SET last_used_at = $2
 WHERE id = $1
`

type TouchMCPTokenLastUsedParams struct {
	ID         uuid.UUID          `json:"id"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

// Stamp last_used_at on successful auth. Best-effort; the auth
// decision doesn't depend on this succeeding.
func (q *Queries) TouchMCPTokenLastUsed(ctx context.Context, arg TouchMCPTokenLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchMCPTokenLastUsed, arg.ID, arg.LastUsedAt)
	return err
}
