package main

import (
	"bytes"
	"compress/gzip"
	"context"
	"crypto/ed25519"
	"crypto/rand"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/kuhlman-labs/fishhawk/runner/internal/agent"
	"github.com/kuhlman-labs/fishhawk/runner/internal/bundle"
	"github.com/kuhlman-labs/fishhawk/runner/internal/gitops"
	"github.com/kuhlman-labs/fishhawk/runner/internal/upload"
)

// openBundleForTest is a thin wrapper around bundle.Open so the
// table-driven test reads cleanly. We round-trip in tests because
// the runner is the producer; the canonical verifier path lives in
// /verifier (and it intentionally re-implements bundle parsing
// rather than importing this code, per ADR-008's no-trust model).
// gunzip is a small test helper for inspecting a runner-produced
// bundle. The runner's wire format is gzipped JSONL; redaction
// assertions need to look at the decompressed text.
func gunzip(b []byte) ([]byte, error) {
	r, err := gzip.NewReader(bytes.NewReader(b))
	if err != nil {
		return nil, err
	}
	defer func() { _ = r.Close() }()
	return io.ReadAll(r)
}

func openBundleForTest(data []byte) (bundle.ManifestData, []bundle.Line, bundle.TrailerData, error) {
	return bundle.Open(bytes.NewReader(data))
}

// fakeInvoker lets tests drive run() without spawning a child
// process. Returning (canned, returnErr) keeps the seam tiny.
type fakeInvoker struct {
	canned    agent.Result
	returnErr error
	gotAPIKey string
}

func (f *fakeInvoker) Invoke(ctx context.Context, inv agent.Invocation) (agent.Result, error) {
	return f.canned, f.returnErr
}

// withFakeInvoker swaps the package's newInvoker for one that
// records the API key and returns canned results. Cleanup restores
// the original constructor.
func withFakeInvoker(t *testing.T, fake *fakeInvoker) {
	t.Helper()
	orig := newInvoker
	newInvoker = func(apiKey string) agent.Invoker {
		fake.gotAPIKey = apiKey
		return fake
	}
	t.Cleanup(func() { newInvoker = orig })
}

// fakeUploader stands in for upload.Client during run() tests.
// Captures the IssueKey + ShipTrace + FetchPrompt inputs so
// assertions can confirm the runner wired the right
// run/stage/variant/bundle.
type fakeUploader struct {
	issueErr     error
	shipErr      error
	promptErr    error
	planErr      error
	prErr        error
	instTokenErr error

	// Recorded calls.
	gotIssueRunID string
	gotIssueCount int
	// gotShipArgs points at the first ShipTrace call so existing
	// tests that assert on it without caring about variant keep
	// working — for runs that ship both raw + redacted (the v0
	// default after E2.4) the first call is the raw upload.
	gotShipArgs *upload.ShipArgs
	// gotShipCalls captures every ShipTrace call in order so tests
	// can assert that both variants ship per stage.
	gotShipCalls     []upload.ShipArgs
	gotPromptArgs    *upload.FetchPromptArgs
	gotPlanArgs      *upload.ShipPlanArgs
	gotPRArgs        *upload.ShipPullRequestArgs
	gotInstTokenArgs *upload.FetchInstallationTokenArgs

	// Canned prompt response. If nil, FetchPrompt returns a default
	// one matching the requested stage_id.
	promptResp *upload.FetchedPrompt

	// Generated by IssueKey when issueErr is nil; ShipTrace returns
	// success keyed off the same key so a real signature is
	// unnecessary in tests.
	priv ed25519.PrivateKey
}

func newFakeUploader(t *testing.T) *fakeUploader {
	t.Helper()
	_, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	return &fakeUploader{priv: priv}
}

func (f *fakeUploader) IssueKey(_ context.Context, runID string, _ time.Duration) (*upload.IssuedKey, error) {
	f.gotIssueRunID = runID
	f.gotIssueCount++
	if f.issueErr != nil {
		return nil, f.issueErr
	}
	return &upload.IssuedKey{
		RunID:      runID,
		PrivateKey: f.priv,
		PublicKey:  f.priv.Public().(ed25519.PublicKey),
		IssuedAt:   time.Date(2026, 5, 2, 12, 0, 0, 0, time.UTC),
		ExpiresAt:  time.Date(2026, 5, 2, 12, 30, 0, 0, time.UTC),
	}, nil
}

func (f *fakeUploader) FetchPrompt(_ context.Context, args upload.FetchPromptArgs) (*upload.FetchedPrompt, error) {
	a := args
	f.gotPromptArgs = &a
	if f.promptErr != nil {
		return nil, f.promptErr
	}
	if f.promptResp != nil {
		r := *f.promptResp
		return &r, nil
	}
	return &upload.FetchedPrompt{
		StageID:   args.StageID,
		StageType: "plan", // default to a non-implement stage so the
		// PR-upload branch in run() doesn't fire on every test that
		// touches FetchPrompt. Implement-specific tests override via
		// fu.promptResp.StageType = "implement".
		Prompt:     "fake prompt body for stage " + args.StageID,
		PromptHash: "deadbeef",
	}, nil
}

func (f *fakeUploader) ShipTrace(_ context.Context, args upload.ShipArgs) (*upload.ShipResult, error) {
	a := args
	f.gotShipCalls = append(f.gotShipCalls, a)
	if f.gotShipArgs == nil {
		// Hold onto the first call so legacy tests stay happy; the
		// gotShipCalls slice is the canonical record of every call.
		f.gotShipArgs = &a
	}
	if f.shipErr != nil {
		return nil, f.shipErr
	}
	return &upload.ShipResult{
		RunID:       args.RunID,
		StageID:     args.StageID,
		Variant:     args.Variant,
		ContentHash: "deadbeef",
	}, nil
}

func (f *fakeUploader) ShipPlan(_ context.Context, args upload.ShipPlanArgs) (*upload.ShipPlanResult, error) {
	a := args
	f.gotPlanArgs = &a
	if f.planErr != nil {
		return nil, f.planErr
	}
	return &upload.ShipPlanResult{
		ID:            "00000000-0000-0000-0000-000000000aaa",
		StageID:       args.StageID,
		ContentHash:   "deadbeef",
		SchemaVersion: "standard_v1",
	}, nil
}

func (f *fakeUploader) ShipPullRequest(_ context.Context, args upload.ShipPullRequestArgs) (*upload.ShipPullRequestResult, error) {
	a := args
	f.gotPRArgs = &a
	if f.prErr != nil {
		return nil, f.prErr
	}
	return &upload.ShipPullRequestResult{
		ID:          "00000000-0000-0000-0000-000000000bbb",
		StageID:     args.StageID,
		ContentHash: "cafebabe",
		PRNumber:    42,
		PRURL:       "https://github.com/x/y/pull/42",
		HeadSHA:     "abc",
	}, nil
}

func (f *fakeUploader) FetchInstallationToken(_ context.Context, args upload.FetchInstallationTokenArgs) (*upload.FetchInstallationTokenResult, error) {
	a := args
	f.gotInstTokenArgs = &a
	if f.instTokenErr != nil {
		return nil, f.instTokenErr
	}
	return &upload.FetchInstallationTokenResult{Token: "ghs_app_token"}, nil
}

// withFakeUploader swaps newUploadClient. Caller restores via
// t.Cleanup automatically.
func withFakeUploader(t *testing.T, fake *fakeUploader) {
	t.Helper()
	orig := newUploadClient
	newUploadClient = func(_ string) uploadClient { return fake }
	t.Cleanup(func() { newUploadClient = orig })
}

// TestRun_HappyPath exercises the no-op success path: every
// required flag set, run() returns 0 and writes a startup log line.
func TestRun_HappyPath(t *testing.T) {
	var out strings.Builder
	got := run([]string{
		"--run-id", "11111111-2222-3333-4444-555555555555",
		"--backend-url", "https://api.fishhawk.test",
		"--workflow", "feature_change",
		"--stage", "plan",
	}, &out)
	if got != exitOK {
		t.Errorf("run = %d, want %d", got, exitOK)
	}
	for _, want := range []string{
		`"event":"runner_started"`,
		`"run_id":"11111111-2222-3333-4444-555555555555"`,
		`"workflow":"feature_change"`,
		`"stage":"plan"`,
	} {
		if !strings.Contains(out.String(), want) {
			t.Errorf("startup log missing %s:\n%s", want, out.String())
		}
	}
}

func TestRun_MissingRunID(t *testing.T) {
	var out strings.Builder
	got := run([]string{
		"--backend-url", "https://api.fishhawk.test",
		"--workflow", "feature_change",
		"--stage", "plan",
	}, &out)
	if got != exitUsage {
		t.Errorf("run = %d, want %d", got, exitUsage)
	}
}

func TestRun_BadFlag(t *testing.T) {
	got := run([]string{"--no-such-flag"}, io.Discard)
	if got != exitUsage {
		t.Errorf("run = %d, want %d", got, exitUsage)
	}
}

func TestRun_HelpExitsUsage(t *testing.T) {
	// flag.ContinueOnError + --help surfaces ErrHelp. We treat that
	// as a usage exit, same as a malformed flag.
	got := run([]string{"--help"}, io.Discard)
	if got != exitUsage {
		t.Errorf("run = %d, want %d", got, exitUsage)
	}
}

func TestRunnerVersion_NonEmpty(t *testing.T) {
	if runnerVersion() == "" {
		t.Fatal("runnerVersion() should never be empty")
	}
}

func TestRun_PromptFileMissing(t *testing.T) {
	var out strings.Builder
	got := run([]string{
		"--run-id", "11111111-2222-3333-4444-555555555555",
		"--backend-url", "https://api.fishhawk.test",
		"--workflow", "feature_change",
		"--stage", "plan",
		"--prompt-file", "/no/such/path/anywhere.txt",
	}, &out)
	if got != exitUsage {
		t.Errorf("run = %d, want %d", got, exitUsage)
	}
	if !strings.Contains(out.String(), `"event":"runner_failed"`) {
		t.Errorf("missing runner_failed log line: %s", out.String())
	}
	if !strings.Contains(out.String(), `"reason":"read_prompt"`) {
		t.Errorf("missing read_prompt reason: %s", out.String())
	}
}

func TestClassifyErr(t *testing.T) {
	cases := []struct {
		err  error
		want string
	}{
		{nil, ""},
		{agent.ErrTimeout, "timeout"},
		{fmt.Errorf("wrapped: %w", agent.ErrTimeout), "timeout"},
		{agent.ErrBudgetExceeded, "budget_exceeded"},
		{agent.ErrBinaryNotFound, "binary_not_found"},
		{agent.ErrAgentFailed, "agent_failed"},
		{fmt.Errorf("wrapped: %w", agent.ErrAgentFailed), "agent_failed"},
		{errors.New("anything else"), "other"},
	}
	for _, tc := range cases {
		var name string
		if tc.err == nil {
			name = "nil"
		} else {
			name = tc.err.Error()
		}
		t.Run(name, func(t *testing.T) {
			if got := classifyErr(tc.err); got != tc.want {
				t.Errorf("classifyErr(%v) = %q, want %q", tc.err, got, tc.want)
			}
		})
	}
}

func TestLogCompletion_OK(t *testing.T) {
	var w strings.Builder
	logCompletion(&w, agent.Result{OK: true, TokensUsed: 250}, nil)
	out := w.String()
	if !strings.Contains(out, `"outcome":"ok"`) {
		t.Errorf("missing outcome ok: %s", out)
	}
	if !strings.Contains(out, `"tokens_used":250`) {
		t.Errorf("missing tokens_used: %s", out)
	}
}

func TestLogCompletion_Failure(t *testing.T) {
	var w strings.Builder
	logCompletion(&w, agent.Result{
		OK:              false,
		FailureCategory: "A",
		FailureReason:   "agent timeout after 100ms",
		TokensUsed:      0,
	}, agent.ErrTimeout)
	out := w.String()
	for _, want := range []string{
		`"outcome":"failed"`,
		`"category":"A"`,
		`"reason":"agent timeout after 100ms"`,
		`"err_class":"timeout"`,
	} {
		if !strings.Contains(out, want) {
			t.Errorf("missing %s in: %s", want, out)
		}
	}
}

func TestRun_PromptInvokesAgentAndEmitsEvents(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "prompt.txt")
	if err := os.WriteFile(path, []byte("do the thing"), 0o600); err != nil {
		t.Fatal(err)
	}

	t.Setenv("ANTHROPIC_API_KEY", "sk-test-1234")

	fake := &fakeInvoker{
		canned: agent.Result{
			OK:         true,
			TokensUsed: 250,
			Events: []agent.Event{
				{Kind: "invocation_start", Payload: agent.MakePayload(map[string]string{"a": "b"})},
				{Kind: "result", Payload: agent.MakePayload(map[string]int{"n": 1})},
				{Kind: "invocation_end"},
			},
		},
	}
	withFakeInvoker(t, fake)

	// Capture stdout — emitEvents writes there.
	stdoutR, stdoutW, _ := os.Pipe()
	origStdout := os.Stdout
	os.Stdout = stdoutW
	t.Cleanup(func() { os.Stdout = origStdout })

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "11111111-2222-3333-4444-555555555555",
		"--backend-url", "https://api.fishhawk.test",
		"--workflow", "feature_change",
		"--stage", "plan",
		"--prompt-file", path,
		"--max-tokens", "1000",
		"--timeout", "30s",
	}, &stderr)

	_ = stdoutW.Close()
	stdoutBytes, _ := io.ReadAll(stdoutR)

	if got != exitOK {
		t.Errorf("run = %d, want %d", got, exitOK)
	}
	if fake.gotAPIKey != "sk-test-1234" {
		t.Errorf("invoker gotAPIKey = %q, want sk-test-1234", fake.gotAPIKey)
	}

	// Three events should have been emitted as JSON Lines on stdout.
	lines := bytes.Split(bytes.TrimRight(stdoutBytes, "\n"), []byte("\n"))
	if len(lines) != 3 {
		t.Fatalf("emitted %d JSONL lines, want 3:\n%s", len(lines), stdoutBytes)
	}
	for i, line := range lines {
		var ev agent.Event
		if err := json.Unmarshal(line, &ev); err != nil {
			t.Errorf("line %d not JSON: %v: %s", i, err, line)
		}
	}

	// The completion log line should report ok and the token count.
	if !strings.Contains(stderr.String(), `"outcome":"ok"`) {
		t.Errorf("missing ok outcome in stderr: %s", stderr.String())
	}
	if !strings.Contains(stderr.String(), `"tokens_used":250`) {
		t.Errorf("missing tokens_used in stderr: %s", stderr.String())
	}
}

func TestRun_AgentFailureMapsToExit1(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "prompt.txt")
	if err := os.WriteFile(path, []byte("p"), 0o600); err != nil {
		t.Fatal(err)
	}
	t.Setenv("ANTHROPIC_API_KEY", "")

	fake := &fakeInvoker{
		canned: agent.Result{
			OK:              false,
			FailureCategory: "A",
			FailureReason:   "agent timeout after 30s",
			Events: []agent.Event{
				{Kind: "invocation_start"},
				{Kind: "invocation_end"},
			},
		},
		returnErr: agent.ErrTimeout,
	}
	withFakeInvoker(t, fake)

	// Discard stdout to keep test output clean.
	stdoutR, stdoutW, _ := os.Pipe()
	origStdout := os.Stdout
	os.Stdout = stdoutW
	t.Cleanup(func() { os.Stdout = origStdout })

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "11111111-2222-3333-4444-555555555555",
		"--backend-url", "https://api.fishhawk.test",
		"--workflow", "feature_change",
		"--stage", "plan",
		"--prompt-file", path,
	}, &stderr)

	_ = stdoutW.Close()
	_, _ = io.ReadAll(stdoutR)

	if got != exitFailure {
		t.Errorf("run = %d, want %d", got, exitFailure)
	}
	out := stderr.String()
	if !strings.Contains(out, `"outcome":"failed"`) {
		t.Errorf("missing failed outcome: %s", out)
	}
	if !strings.Contains(out, `"category":"A"`) {
		t.Errorf("missing category A: %s", out)
	}
	if !strings.Contains(out, `"err_class":"timeout"`) {
		t.Errorf("missing err_class timeout: %s", out)
	}
}

func TestRun_PromptWithBundleOut_WritesGzipFile(t *testing.T) {
	dir := t.TempDir()
	promptPath := filepath.Join(dir, "prompt.txt")
	bundlePath := filepath.Join(dir, "trace.jsonl.gz")
	if err := os.WriteFile(promptPath, []byte("p"), 0o600); err != nil {
		t.Fatal(err)
	}

	fake := &fakeInvoker{
		canned: agent.Result{
			OK:         true,
			TokensUsed: 7,
			Events: []agent.Event{
				{Kind: "system.init", Payload: agent.MakePayload(map[string]string{"a": "b"})},
				{Kind: "result", Payload: agent.MakePayload(map[string]int{"n": 1})},
			},
		},
	}
	withFakeInvoker(t, fake)

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "11111111-2222-3333-4444-555555555555",
		"--backend-url", "https://api.fishhawk.test",
		"--workflow", "feature_change",
		"--stage", "plan",
		"--prompt-file", promptPath,
		"--bundle-out", bundlePath,
	}, &stderr)
	if got != exitOK {
		t.Fatalf("run = %d, want %d:\n%s", got, exitOK, stderr.String())
	}
	info, err := os.Stat(bundlePath)
	if err != nil {
		t.Fatalf("bundle not written: %v", err)
	}
	if info.Size() == 0 {
		t.Fatal("bundle is empty")
	}

	// Sanity-check that the file is a valid bundle. We import
	// internal/bundle here just to round-trip-verify; in
	// production the backend re-implements verification under
	// the audit-grade no-trust constraint (see verifier/).
	data, err := os.ReadFile(bundlePath)
	if err != nil {
		t.Fatal(err)
	}
	manifest, events, trailer, err := openBundleForTest(data)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	if manifest.RunID != "11111111-2222-3333-4444-555555555555" {
		t.Errorf("manifest RunID = %q", manifest.RunID)
	}
	if len(events) != 2 {
		t.Errorf("events = %d, want 2", len(events))
	}
	if trailer.EventCount != 2 {
		t.Errorf("trailer EventCount = %d, want 2", trailer.EventCount)
	}
}

func TestRun_BundleWriteFailureSurfacesAsExitFailure(t *testing.T) {
	dir := t.TempDir()
	promptPath := filepath.Join(dir, "prompt.txt")
	if err := os.WriteFile(promptPath, []byte("p"), 0o600); err != nil {
		t.Fatal(err)
	}

	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "rid",
		"--backend-url", "https://x",
		"--workflow", "w",
		"--stage", "s",
		"--prompt-file", promptPath,
		// Path under a non-existent parent directory.
		"--bundle-out", filepath.Join(dir, "no-such-subdir", "trace.jsonl.gz"),
	}, &stderr)
	if got != exitFailure {
		t.Errorf("run = %d, want %d", got, exitFailure)
	}
	if !strings.Contains(stderr.String(), `"reason":"bundle_write"`) {
		t.Errorf("missing bundle_write reason: %s", stderr.String())
	}
}

// validPlanJSON returns a minimal standard_v1 plan that the
// validator accepts. Inline rather than reading a fixture so the
// test is self-contained.
func validPlanJSON() string {
	return `{
  "plan_version": "standard_v1",
  "ticket_reference": {"type":"github_issue","url":"https://github.com/x/y/issues/1","id":"x/y#1"},
  "generated_by": {"agent":"claude-code","model":"claude-opus-4-7","version":"build-1","timestamp":"2026-05-02T10:00:00Z"},
  "summary": "Add a thing.",
  "scope": {"files": [{"path":"a.go","operation":"create"}], "estimated_lines_changed": 10},
  "approach": [{"step":1,"description":"Do."}],
  "verification": {"test_strategy":"go test","rollback_plan":"revert PR"}
}`
}

func TestRun_PlanValidationOK(t *testing.T) {
	dir := t.TempDir()
	promptPath := filepath.Join(dir, "prompt.txt")
	planPath := filepath.Join(dir, "plan.json")
	bundlePath := filepath.Join(dir, "trace.jsonl.gz")
	if err := os.WriteFile(promptPath, []byte("p"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(planPath, []byte(validPlanJSON()), 0o600); err != nil {
		t.Fatal(err)
	}
	withFakeInvoker(t, &fakeInvoker{
		canned: agent.Result{
			OK:     true,
			Events: []agent.Event{{Kind: "system.init"}},
		},
	})

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "rid", "--backend-url", "u", "--workflow", "w", "--stage", "s",
		"--prompt-file", promptPath, "--plan-out", planPath, "--bundle-out", bundlePath,
	}, &stderr)
	if got != exitOK {
		t.Fatalf("run = %d, want %d:\n%s", got, exitOK, stderr.String())
	}
	// Bundle should now contain the system.init plus a policy_event
	// with outcome=valid.
	data, err := os.ReadFile(bundlePath)
	if err != nil {
		t.Fatal(err)
	}
	_, events, _, err := openBundleForTest(data)
	if err != nil {
		t.Fatal(err)
	}
	var sawValid bool
	for _, ev := range events {
		if ev.Kind == "policy_event" && strings.Contains(string(ev.Data), `"outcome":"valid"`) {
			sawValid = true
		}
	}
	if !sawValid {
		t.Errorf("missing policy_event outcome=valid in bundle:\n%+v", events)
	}
}

func TestRun_PlanValidationInvalid_DemotesToCategoryB(t *testing.T) {
	dir := t.TempDir()
	promptPath := filepath.Join(dir, "prompt.txt")
	planPath := filepath.Join(dir, "plan.json")
	if err := os.WriteFile(promptPath, []byte("p"), 0o600); err != nil {
		t.Fatal(err)
	}
	// Drop required field "summary" — schema rejects.
	bad := strings.Replace(validPlanJSON(), `"summary": "Add a thing.",`, "", 1)
	if err := os.WriteFile(planPath, []byte(bad), 0o600); err != nil {
		t.Fatal(err)
	}
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "rid", "--backend-url", "u", "--workflow", "w", "--stage", "s",
		"--prompt-file", promptPath, "--plan-out", planPath,
	}, &stderr)
	if got != exitFailure {
		t.Errorf("run = %d, want exitFailure", got)
	}
	out := stderr.String()
	if !strings.Contains(out, `"category":"B"`) {
		t.Errorf("missing category B (plan validation should demote): %s", out)
	}
	if !strings.Contains(out, `"outcome":"failed"`) {
		t.Errorf("missing failed outcome: %s", out)
	}
}

func TestRun_PlanFileMissing_DemotesToCategoryB(t *testing.T) {
	dir := t.TempDir()
	promptPath := filepath.Join(dir, "prompt.txt")
	if err := os.WriteFile(promptPath, []byte("p"), 0o600); err != nil {
		t.Fatal(err)
	}
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "rid", "--backend-url", "u", "--workflow", "w", "--stage", "s",
		"--prompt-file", promptPath,
		"--plan-out", filepath.Join(dir, "nonexistent.json"),
	}, &stderr)
	if got != exitFailure {
		t.Errorf("run = %d, want exitFailure", got)
	}
	if !strings.Contains(stderr.String(), `"category":"B"`) {
		t.Errorf("missing category B: %s", stderr.String())
	}
}

func TestRun_PlanValidationSkippedOnAgentFailure(t *testing.T) {
	// If the agent already failed (category A), don't run plan
	// validation — there's no plan to validate, and the failure
	// classification must remain A.
	dir := t.TempDir()
	promptPath := filepath.Join(dir, "prompt.txt")
	if err := os.WriteFile(promptPath, []byte("p"), 0o600); err != nil {
		t.Fatal(err)
	}
	withFakeInvoker(t, &fakeInvoker{
		canned: agent.Result{
			OK:              false,
			FailureCategory: "A",
			FailureReason:   "agent crash",
		},
		returnErr: agent.ErrAgentFailed,
	})

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "rid", "--backend-url", "u", "--workflow", "w", "--stage", "s",
		"--prompt-file", promptPath,
		// plan-out points to a missing file — if validation ran, this
		// would override category to B; assert it doesn't.
		"--plan-out", filepath.Join(dir, "nope.json"),
	}, &stderr)
	if got != exitFailure {
		t.Errorf("run = %d, want exitFailure", got)
	}
	if !strings.Contains(stderr.String(), `"category":"A"`) {
		t.Errorf("expected category A preserved: %s", stderr.String())
	}
}

func TestRun_ConstraintsConfigUnreadable_DemotesToB(t *testing.T) {
	dir := t.TempDir()
	promptPath := filepath.Join(dir, "prompt.txt")
	if err := os.WriteFile(promptPath, []byte("p"), 0o600); err != nil {
		t.Fatal(err)
	}
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "rid", "--backend-url", "u", "--workflow", "w", "--stage", "s",
		"--prompt-file", promptPath,
		"--constraints-file", filepath.Join(dir, "no-such.json"),
		"--check-base-ref", "main",
	}, &stderr)
	if got != exitFailure {
		t.Fatalf("run = %d, want exitFailure", got)
	}
	if !strings.Contains(stderr.String(), `"category":"B"`) {
		t.Errorf("missing category B: %s", stderr.String())
	}
}

func TestRun_ConstraintsConfigInvalidJSON_DemotesToB(t *testing.T) {
	dir := t.TempDir()
	promptPath := filepath.Join(dir, "prompt.txt")
	configPath := filepath.Join(dir, "constraints.json")
	if err := os.WriteFile(promptPath, []byte("p"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(configPath, []byte("{not json"), 0o600); err != nil {
		t.Fatal(err)
	}
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "rid", "--backend-url", "u", "--workflow", "w", "--stage", "s",
		"--prompt-file", promptPath,
		"--constraints-file", configPath,
		"--check-base-ref", "main",
	}, &stderr)
	if got != exitFailure {
		t.Errorf("run = %d, want exitFailure", got)
	}
	if !strings.Contains(stderr.String(), `"category":"B"`) {
		t.Errorf("missing category B: %s", stderr.String())
	}
}

func TestRun_ConstraintsRequiresBothFlags(t *testing.T) {
	// --constraints-file alone (no --check-base-ref) should NOT
	// trigger constraint evaluation. Use a path that would error
	// if read; if we still exit OK, the wiring is correct.
	dir := t.TempDir()
	promptPath := filepath.Join(dir, "prompt.txt")
	if err := os.WriteFile(promptPath, []byte("p"), 0o600); err != nil {
		t.Fatal(err)
	}
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "rid", "--backend-url", "u", "--workflow", "w", "--stage", "s",
		"--prompt-file", promptPath,
		"--constraints-file", filepath.Join(dir, "no-such.json"),
		// --check-base-ref intentionally absent.
	}, &stderr)
	if got != exitOK {
		t.Errorf("run = %d, want exitOK (constraints should be skipped without --check-base-ref)", got)
	}
}

func TestRun_ConstraintsSkippedOnAgentFailure(t *testing.T) {
	// If the agent failed, constraint evaluation must not run —
	// keep failure category A.
	dir := t.TempDir()
	promptPath := filepath.Join(dir, "prompt.txt")
	if err := os.WriteFile(promptPath, []byte("p"), 0o600); err != nil {
		t.Fatal(err)
	}
	withFakeInvoker(t, &fakeInvoker{
		canned: agent.Result{
			OK: false, FailureCategory: "A", FailureReason: "agent crash",
		},
		returnErr: agent.ErrAgentFailed,
	})

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "rid", "--backend-url", "u", "--workflow", "w", "--stage", "s",
		"--prompt-file", promptPath,
		"--constraints-file", filepath.Join(dir, "no-such.json"),
		"--check-base-ref", "main",
	}, &stderr)
	if got != exitFailure {
		t.Fatalf("run = %d, want exitFailure", got)
	}
	if !strings.Contains(stderr.String(), `"category":"A"`) {
		t.Errorf("expected category A preserved: %s", stderr.String())
	}
}

func TestRun_UploadTrace_HappyPath(t *testing.T) {
	dir := t.TempDir()
	promptPath := filepath.Join(dir, "prompt.txt")
	if err := os.WriteFile(promptPath, []byte("p"), 0o600); err != nil {
		t.Fatal(err)
	}
	withFakeInvoker(t, &fakeInvoker{
		canned: agent.Result{
			OK:     true,
			Events: []agent.Event{{Kind: "system.init"}},
		},
	})
	fu := newFakeUploader(t)
	withFakeUploader(t, fu)

	stageID := "22222222-3333-4444-5555-666666666666"
	runID := "11111111-2222-3333-4444-555555555555"
	var stderr strings.Builder
	got := run([]string{
		"--run-id", runID, "--backend-url", "https://api.fishhawk.test",
		"--workflow", "feature_change", "--stage", "plan",
		"--prompt-file", promptPath,
		"--upload-trace",
		"--stage-id", stageID,
	}, &stderr)
	if got != exitOK {
		t.Fatalf("run = %d, want exitOK:\n%s", got, stderr.String())
	}
	if fu.gotIssueRunID != runID {
		t.Errorf("IssueKey runID = %q, want %q", fu.gotIssueRunID, runID)
	}
	if fu.gotShipArgs == nil {
		t.Fatal("ShipTrace not called")
	}
	if fu.gotShipArgs.StageID != stageID {
		t.Errorf("ShipTrace stage_id = %q, want %q", fu.gotShipArgs.StageID, stageID)
	}
	if fu.gotShipArgs.Variant != "raw" {
		t.Errorf("ShipTrace variant = %q", fu.gotShipArgs.Variant)
	}
	if len(fu.gotShipArgs.Bundle) == 0 {
		t.Error("ShipTrace bundle empty")
	}
	if !strings.Contains(stderr.String(), `"event":"trace_uploaded"`) {
		t.Errorf("missing trace_uploaded log: %s", stderr.String())
	}
	// Per E2.4: every stage ships *both* variants. Raw first
	// (compliance-preferred audit ordering), redacted second (the
	// SPA transcript reads this).
	if len(fu.gotShipCalls) != 2 {
		t.Fatalf("ShipTrace calls = %d, want 2 (raw + redacted)", len(fu.gotShipCalls))
	}
	if fu.gotShipCalls[0].Variant != "raw" {
		t.Errorf("first call variant = %q, want raw", fu.gotShipCalls[0].Variant)
	}
	if fu.gotShipCalls[1].Variant != "redacted" {
		t.Errorf("second call variant = %q, want redacted", fu.gotShipCalls[1].Variant)
	}
	if len(fu.gotShipCalls[1].Bundle) == 0 {
		t.Error("redacted bundle empty")
	}
}

func TestRun_UploadTrace_RedactsSecrets(t *testing.T) {
	// Plant a known credential in an event payload; the redacted
	// variant must not contain it after re-pack. This is the
	// regression guard for E2.4 — the redacted bundle is the SPA
	// transcript's only input, so leakage here ends up readable
	// behind cookie auth.
	dir := t.TempDir()
	promptPath := filepath.Join(dir, "prompt.txt")
	if err := os.WriteFile(promptPath, []byte("p"), 0o600); err != nil {
		t.Fatal(err)
	}

	// ghp_… is in DefaultPatterns; using a 36-char alphanumeric
	// suffix matches the regex exactly. The token bytes are
	// deliberate — anything that wouldn't match the pattern would
	// pass through and the test would assert against itself.
	secret := "ghp_" + strings.Repeat("a", 36)
	withFakeInvoker(t, &fakeInvoker{
		canned: agent.Result{
			OK: true,
			Events: []agent.Event{
				{Kind: "raw", Payload: json.RawMessage(`{"text":"saw ` + secret + ` in stderr"}`)},
			},
		},
	})
	fu := newFakeUploader(t)
	withFakeUploader(t, fu)

	stageID := "22222222-3333-4444-5555-666666666666"
	runID := "11111111-2222-3333-4444-555555555555"
	var stderr strings.Builder
	got := run([]string{
		"--run-id", runID, "--backend-url", "https://api.fishhawk.test",
		"--workflow", "feature_change", "--stage", "plan",
		"--prompt-file", promptPath,
		"--upload-trace",
		"--stage-id", stageID,
	}, &stderr)
	if got != exitOK {
		t.Fatalf("run = %d:\n%s", got, stderr.String())
	}
	if len(fu.gotShipCalls) != 2 {
		t.Fatalf("ShipTrace calls = %d, want 2", len(fu.gotShipCalls))
	}

	rawHasSecret := bytes.Contains(fu.gotShipCalls[0].Bundle, []byte(secret))
	redactedHasSecret := bytes.Contains(fu.gotShipCalls[1].Bundle, []byte(secret))
	if !rawHasSecret {
		// If the secret didn't make it into raw either, the test
		// is broken — likely the bundle's gzipped and we'd need to
		// decompress to find it. Decompress to be robust.
		raw, err := gunzip(fu.gotShipCalls[0].Bundle)
		if err != nil {
			t.Fatalf("raw bundle gunzip: %v", err)
		}
		if !bytes.Contains(raw, []byte(secret)) {
			t.Fatalf("secret not in raw bundle either; test broken")
		}
		// Compare against decompressed bytes for redacted too.
		redacted, err := gunzip(fu.gotShipCalls[1].Bundle)
		if err != nil {
			t.Fatalf("redacted bundle gunzip: %v", err)
		}
		if bytes.Contains(redacted, []byte(secret)) {
			t.Errorf("secret survived redaction in decompressed redacted bundle")
		}
		if !bytes.Contains(redacted, []byte("[REDACTED:github-pat-classic]")) {
			t.Errorf("redaction marker missing from redacted bundle")
		}
	} else if redactedHasSecret {
		t.Errorf("secret survived redaction in redacted bundle")
	}

	// Telemetry: a trace_redacted log line with a non-empty hits
	// list, so operators can see "the runner redacted N tokens this
	// run" without leaking the tokens themselves.
	if !strings.Contains(stderr.String(), `"event":"trace_redacted"`) {
		t.Errorf("missing trace_redacted telemetry log:\n%s", stderr.String())
	}
	if !strings.Contains(stderr.String(), `"github-pat-classic"`) {
		t.Errorf("trace_redacted log should name the matched pattern:\n%s", stderr.String())
	}
}

func TestRun_UploadTrace_RequiresStageID(t *testing.T) {
	dir := t.TempDir()
	promptPath := filepath.Join(dir, "prompt.txt")
	_ = os.WriteFile(promptPath, []byte("p"), 0o600)
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})
	withFakeUploader(t, newFakeUploader(t))

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "rid", "--backend-url", "u",
		"--workflow", "w", "--stage", "s",
		"--prompt-file", promptPath,
		"--upload-trace",
		// no --stage-id
	}, &stderr)
	if got != exitFailure {
		t.Errorf("run = %d, want exitFailure", got)
	}
	if !strings.Contains(stderr.String(), "stage-id required") {
		t.Errorf("missing stage-id required: %s", stderr.String())
	}
	if !strings.Contains(stderr.String(), `"category":"C"`) {
		t.Errorf("missing category C: %s", stderr.String())
	}
}

func TestRun_UploadTrace_IssueKeyFailure_CategoryC(t *testing.T) {
	dir := t.TempDir()
	promptPath := filepath.Join(dir, "prompt.txt")
	_ = os.WriteFile(promptPath, []byte("p"), 0o600)
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})
	fu := newFakeUploader(t)
	fu.issueErr = errors.New("backend unreachable")
	withFakeUploader(t, fu)

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "rid", "--backend-url", "u",
		"--workflow", "w", "--stage", "s",
		"--prompt-file", promptPath,
		"--upload-trace",
		"--stage-id", "22222222-3333-4444-5555-666666666666",
	}, &stderr)
	if got != exitFailure {
		t.Errorf("run = %d, want exitFailure", got)
	}
	if !strings.Contains(stderr.String(), `"category":"C"`) {
		t.Errorf("missing category C: %s", stderr.String())
	}
}

func TestRun_UploadTrace_ShipFailure_CategoryC(t *testing.T) {
	dir := t.TempDir()
	promptPath := filepath.Join(dir, "prompt.txt")
	_ = os.WriteFile(promptPath, []byte("p"), 0o600)
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})
	fu := newFakeUploader(t)
	fu.shipErr = errors.New("disk full on backend")
	withFakeUploader(t, fu)

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "rid", "--backend-url", "u",
		"--workflow", "w", "--stage", "s",
		"--prompt-file", promptPath,
		"--upload-trace",
		"--stage-id", "22222222-3333-4444-5555-666666666666",
	}, &stderr)
	if got != exitFailure {
		t.Errorf("run = %d, want exitFailure", got)
	}
	if !strings.Contains(stderr.String(), `"category":"C"`) {
		t.Errorf("missing category C: %s", stderr.String())
	}
}

func TestRun_UploadTrace_DoesntOverwriteCategoryB(t *testing.T) {
	// If plan validation already demoted to B, an upload failure
	// must not overwrite the category.
	dir := t.TempDir()
	promptPath := filepath.Join(dir, "prompt.txt")
	planPath := filepath.Join(dir, "plan.json")
	_ = os.WriteFile(promptPath, []byte("p"), 0o600)
	_ = os.WriteFile(planPath, []byte("{not a plan}"), 0o600)

	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})
	fu := newFakeUploader(t)
	withFakeUploader(t, fu)

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "rid", "--backend-url", "u",
		"--workflow", "w", "--stage", "s",
		"--prompt-file", promptPath,
		"--plan-out", planPath,
		"--upload-trace",
		"--stage-id", "22222222-3333-4444-5555-666666666666",
	}, &stderr)
	if got != exitFailure {
		t.Errorf("run = %d, want exitFailure", got)
	}
	// Category should still be B (plan validation failure), not C.
	if !strings.Contains(stderr.String(), `"category":"B"`) {
		t.Errorf("expected category B preserved: %s", stderr.String())
	}
}

func TestEmitEvents_OneJSONPerLine(t *testing.T) {
	var w bytes.Buffer
	emitEvents(&w, []agent.Event{
		{Kind: "a"},
		{Kind: "b", Payload: agent.MakePayload(map[string]int{"n": 1})},
	})
	lines := bytes.Split(bytes.TrimRight(w.Bytes(), "\n"), []byte("\n"))
	if len(lines) != 2 {
		t.Fatalf("got %d lines, want 2:\n%s", len(lines), w.String())
	}
	for _, line := range lines {
		var ev agent.Event
		if err := json.Unmarshal(line, &ev); err != nil {
			t.Errorf("line not JSON: %v: %s", err, line)
		}
	}
}

func TestNewInvoker_DefaultIsClaudeCode(t *testing.T) {
	// Sanity check: production wiring constructs a non-nil invoker.
	// Regression guard for someone removing the default assignment.
	inv := newInvoker("k")
	if inv == nil {
		t.Fatal("newInvoker returned nil")
	}
}

func TestLogCompletion_FailureFallsBackToErrText(t *testing.T) {
	// FailureReason empty → reason should fall back to err.Error().
	var w strings.Builder
	logCompletion(&w, agent.Result{OK: false}, errors.New("boom"))
	out := w.String()
	if !strings.Contains(out, `"reason":"boom"`) {
		t.Errorf("missing reason fallback: %s", out)
	}
	// FailureCategory empty → should default to "A".
	if !strings.Contains(out, `"category":"A"`) {
		t.Errorf("missing default category A: %s", out)
	}
}

func TestRun_FetchPrompt_HappyPath(t *testing.T) {
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})
	fu := newFakeUploader(t)
	fu.promptResp = &upload.FetchedPrompt{
		StageID:    "22222222-3333-4444-5555-666666666666",
		StageType:  "implement",
		Prompt:     "Hello agent, do the thing.",
		PromptHash: "deadbeef",
	}
	withFakeUploader(t, fu)

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "11111111-2222-3333-4444-555555555555",
		"--backend-url", "https://api.fishhawk.test",
		"--workflow", "feature_change", "--stage", "implement",
		"--stage-id", "22222222-3333-4444-5555-666666666666",
		"--fetch-prompt",
	}, &stderr)
	if got != exitOK {
		t.Fatalf("run = %d, want exitOK:\n%s", got, stderr.String())
	}
	if fu.gotPromptArgs == nil {
		t.Fatal("FetchPrompt not called")
	}
	if fu.gotPromptArgs.StageID != "22222222-3333-4444-5555-666666666666" {
		t.Errorf("FetchPrompt stage_id = %q", fu.gotPromptArgs.StageID)
	}
	if !strings.Contains(stderr.String(), `"event":"prompt_fetched"`) {
		t.Errorf("missing prompt_fetched log: %s", stderr.String())
	}
	if !strings.Contains(stderr.String(), `"event":"signing_key_issued"`) {
		t.Errorf("missing signing_key_issued log: %s", stderr.String())
	}
}

func TestRun_FetchPrompt_PromptFileWins(t *testing.T) {
	dir := t.TempDir()
	promptPath := filepath.Join(dir, "prompt.txt")
	if err := os.WriteFile(promptPath, []byte("local override"), 0o600); err != nil {
		t.Fatal(err)
	}
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})
	fu := newFakeUploader(t)
	withFakeUploader(t, fu)

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "rid", "--backend-url", "u",
		"--workflow", "w", "--stage", "s",
		"--stage-id", "stage-1",
		"--fetch-prompt",
		"--prompt-file", promptPath,
	}, &stderr)
	if got != exitOK {
		t.Fatalf("run = %d, want exitOK:\n%s", got, stderr.String())
	}
	if fu.gotPromptArgs != nil {
		t.Errorf("FetchPrompt called even though --prompt-file was set")
	}
}

func TestRun_FetchPrompt_RequiresStageID(t *testing.T) {
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})
	withFakeUploader(t, newFakeUploader(t))

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "rid", "--backend-url", "u",
		"--workflow", "w", "--stage", "s",
		"--fetch-prompt",
		// no --stage-id
	}, &stderr)
	if got != exitUsage {
		t.Errorf("run = %d, want exitUsage", got)
	}
	if !strings.Contains(stderr.String(), "stage-id") {
		t.Errorf("missing stage-id error: %s", stderr.String())
	}
}

func TestRun_FetchPrompt_FetchFailure(t *testing.T) {
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})
	fu := newFakeUploader(t)
	fu.promptErr = errors.New("backend down")
	withFakeUploader(t, fu)

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "rid", "--backend-url", "u",
		"--workflow", "w", "--stage", "s",
		"--stage-id", "stage-1",
		"--fetch-prompt",
	}, &stderr)
	if got != exitFailure {
		t.Errorf("run = %d, want exitFailure", got)
	}
	if !strings.Contains(stderr.String(), "fetch_prompt") {
		t.Errorf("missing fetch_prompt error: %s", stderr.String())
	}
}

func TestRun_FetchPrompt_IssueKeyFailure(t *testing.T) {
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})
	fu := newFakeUploader(t)
	fu.issueErr = errors.New("issue failed")
	withFakeUploader(t, fu)

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "rid", "--backend-url", "u",
		"--workflow", "w", "--stage", "s",
		"--stage-id", "stage-1",
		"--fetch-prompt",
	}, &stderr)
	if got != exitFailure {
		t.Errorf("run = %d, want exitFailure", got)
	}
	if !strings.Contains(stderr.String(), "issue_key") {
		t.Errorf("missing issue_key error: %s", stderr.String())
	}
}

func TestRun_FetchPrompt_PlusUploadTrace_OnlyOneIssueKeyCall(t *testing.T) {
	// Critical invariant: signing-key endpoint is one-shot per run.
	// Combining --fetch-prompt with --upload-trace must reuse the
	// same key issued at fetch-prompt time, not call IssueKey twice.
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true,
		Events: []agent.Event{{Kind: "system.init"}}}})
	fu := newFakeUploader(t)
	withFakeUploader(t, fu)

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "rid", "--backend-url", "u",
		"--workflow", "w", "--stage", "s",
		"--stage-id", "stage-1",
		"--fetch-prompt",
		"--upload-trace",
	}, &stderr)
	if got != exitOK {
		t.Fatalf("run = %d, want exitOK:\n%s", got, stderr.String())
	}
	if fu.gotIssueCount != 1 {
		t.Errorf("IssueKey calls = %d, want 1", fu.gotIssueCount)
	}
	if fu.gotPromptArgs == nil {
		t.Error("FetchPrompt not called")
	}
	if fu.gotShipArgs == nil {
		t.Error("ShipTrace not called")
	}
}

func TestRun_UploadPlan_HappyPath(t *testing.T) {
	dir := t.TempDir()
	promptPath := filepath.Join(dir, "prompt.txt")
	planPath := filepath.Join(dir, "plan.json")
	if err := os.WriteFile(promptPath, []byte("p"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(planPath, []byte(validPlanJSON()), 0o600); err != nil {
		t.Fatal(err)
	}
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})
	fu := newFakeUploader(t)
	withFakeUploader(t, fu)

	stageID := "22222222-3333-4444-5555-666666666666"
	runID := "11111111-2222-3333-4444-555555555555"
	var stderr strings.Builder
	got := run([]string{
		"--run-id", runID, "--backend-url", "https://api.fishhawk.test",
		"--workflow", "feature_change", "--stage", "plan",
		"--prompt-file", promptPath,
		"--plan-out", planPath,
		"--upload-trace",
		"--stage-id", stageID,
	}, &stderr)
	if got != exitOK {
		t.Fatalf("run = %d, want exitOK:\n%s", got, stderr.String())
	}

	// Both trace and plan should have been shipped, in that order.
	if fu.gotShipArgs == nil {
		t.Fatal("ShipTrace not called")
	}
	if fu.gotPlanArgs == nil {
		t.Fatal("ShipPlan not called")
	}
	if fu.gotPlanArgs.StageID != stageID {
		t.Errorf("ShipPlan stage_id = %q, want %q", fu.gotPlanArgs.StageID, stageID)
	}
	if fu.gotPlanArgs.RunID != runID {
		t.Errorf("ShipPlan run_id = %q, want %q", fu.gotPlanArgs.RunID, runID)
	}
	if !strings.HasPrefix(string(fu.gotPlanArgs.Plan), `{`) {
		t.Errorf("ShipPlan plan body should be JSON, got prefix %q", string(fu.gotPlanArgs.Plan)[:1])
	}

	// Single-issue: signing-key issued exactly once across the whole
	// run (prompt fetch / trace upload / plan upload share it).
	if fu.gotIssueCount != 1 {
		t.Errorf("IssueKey called %d times, want 1", fu.gotIssueCount)
	}

	if !strings.Contains(stderr.String(), `"event":"plan_uploaded"`) {
		t.Errorf("missing plan_uploaded log:\n%s", stderr.String())
	}
}

func TestRun_UploadPlan_NetworkError_CategoryC(t *testing.T) {
	dir := t.TempDir()
	promptPath := filepath.Join(dir, "prompt.txt")
	planPath := filepath.Join(dir, "plan.json")
	_ = os.WriteFile(promptPath, []byte("p"), 0o600)
	_ = os.WriteFile(planPath, []byte(validPlanJSON()), 0o600)
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})
	fu := newFakeUploader(t)
	fu.planErr = errors.New("ship plan: connection refused")
	withFakeUploader(t, fu)

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "11111111-2222-3333-4444-555555555555",
		"--backend-url", "https://api.fishhawk.test",
		"--workflow", "w", "--stage", "s",
		"--prompt-file", promptPath,
		"--plan-out", planPath,
		"--upload-trace",
		"--stage-id", "22222222-3333-4444-5555-666666666666",
	}, &stderr)
	if got != exitFailure {
		t.Errorf("run = %d, want exitFailure", got)
	}
	if !strings.Contains(stderr.String(), `"reason":"plan_upload"`) {
		t.Errorf("missing plan_upload reason:\n%s", stderr.String())
	}
	if !strings.Contains(stderr.String(), `"category":"C"`) {
		t.Errorf("expected category-C on network error, got:\n%s", stderr.String())
	}
}

func TestRun_UploadPlan_PlanInvalid_CategoryB(t *testing.T) {
	dir := t.TempDir()
	promptPath := filepath.Join(dir, "prompt.txt")
	planPath := filepath.Join(dir, "plan.json")
	_ = os.WriteFile(promptPath, []byte("p"), 0o600)
	_ = os.WriteFile(planPath, []byte(validPlanJSON()), 0o600)
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})
	fu := newFakeUploader(t)
	fu.planErr = upload.ErrPlanInvalid
	withFakeUploader(t, fu)

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "11111111-2222-3333-4444-555555555555",
		"--backend-url", "https://api.fishhawk.test",
		"--workflow", "w", "--stage", "s",
		"--prompt-file", promptPath,
		"--plan-out", planPath,
		"--upload-trace",
		"--stage-id", "22222222-3333-4444-5555-666666666666",
	}, &stderr)
	if got != exitFailure {
		t.Errorf("run = %d, want exitFailure", got)
	}
	if !strings.Contains(stderr.String(), `"category":"B"`) {
		t.Errorf("expected category-B on schema reject, got:\n%s", stderr.String())
	}
}

func TestRun_UploadPlan_NotShippedWithoutPlanOut(t *testing.T) {
	dir := t.TempDir()
	promptPath := filepath.Join(dir, "prompt.txt")
	_ = os.WriteFile(promptPath, []byte("p"), 0o600)
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})
	fu := newFakeUploader(t)
	withFakeUploader(t, fu)

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "rid", "--backend-url", "u",
		"--workflow", "w", "--stage", "s",
		"--prompt-file", promptPath,
		"--upload-trace",
		"--stage-id", "22222222-3333-4444-5555-666666666666",
	}, &stderr)
	if got != exitOK {
		t.Fatalf("run = %d, want exitOK", got)
	}
	if fu.gotPlanArgs != nil {
		t.Error("ShipPlan should not be called without --plan-out")
	}
}

// fakePusher captures CommitAndPush args and returns canned results.
type fakePusher struct {
	gotArgs *gitops.CommitAndPushArgs
	result  *gitops.CommitAndPushResult
	err     error
}

func (f *fakePusher) CommitAndPush(_ context.Context, args gitops.CommitAndPushArgs) (*gitops.CommitAndPushResult, error) {
	a := args
	f.gotArgs = &a
	if f.err != nil {
		return nil, f.err
	}
	if f.result != nil {
		return f.result, nil
	}
	return &gitops.CommitAndPushResult{
		HeadSHA: "head-sha-abc",
		BaseSHA: "base-sha-def",
	}, nil
}

// fakePROpener captures OpenPR args and returns canned results.
type fakePROpener struct {
	gotArgs  *gitops.OpenPRArgs
	gotToken string
	result   *gitops.OpenPRResult
	err      error
}

func (f *fakePROpener) OpenPR(_ context.Context, args gitops.OpenPRArgs) (*gitops.OpenPRResult, error) {
	a := args
	f.gotArgs = &a
	if f.err != nil {
		return nil, f.err
	}
	if f.result != nil {
		return f.result, nil
	}
	return &gitops.OpenPRResult{
		PRNumber: 42,
		PRURL:    "https://github.com/x/y/pull/42",
	}, nil
}

func withFakeGitOps(t *testing.T, fp *fakePusher, fpr *fakePROpener) {
	t.Helper()
	origP, origO := newPusher, newPROpener
	newPusher = func() pusher { return fp }
	newPROpener = func(token string) prOpener {
		fpr.gotToken = token
		return fpr
	}
	t.Cleanup(func() { newPusher = origP; newPROpener = origO })
}

// implementEnv sets the env vars the implement-stage flow reads
// from the Actions environment. The App-token migration (#197) made
// GITHUB_TOKEN unused; we keep setting it for parity with the live
// Actions environment (the runner doesn't read it any more).
// Restored via t.Cleanup.
func implementEnv(t *testing.T, repo, ref string) {
	t.Helper()
	t.Setenv("GITHUB_REPOSITORY", repo)
	t.Setenv("GITHUB_REF_NAME", ref)
}

func TestRun_ImplementStage_HappyPath(t *testing.T) {
	implementEnv(t, "kuhlman-labs/fishhawk", "main")
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})
	fu := newFakeUploader(t)
	fu.promptResp = &upload.FetchedPrompt{
		StageID:    "22222222-3333-4444-5555-666666666666",
		StageType:  "implement",
		Prompt:     "implement",
		PromptHash: "h",
	}
	withFakeUploader(t, fu)
	fp := &fakePusher{}
	fpr := &fakePROpener{}
	withFakeGitOps(t, fp, fpr)

	runID := "11111111-2222-3333-4444-555555555555"
	stageID := "22222222-3333-4444-5555-666666666666"
	var stderr strings.Builder
	got := run([]string{
		"--run-id", runID,
		"--backend-url", "https://api.fishhawk.test",
		"--workflow", "feature_change", "--stage", "implement",
		"--stage-id", stageID,
		"--fetch-prompt",
		"--upload-trace",
	}, &stderr)
	if got != exitOK {
		t.Fatalf("run = %d, want exitOK:\n%s", got, stderr.String())
	}

	if fp.gotArgs == nil {
		t.Fatal("CommitAndPush not called")
	}
	if !strings.HasPrefix(fp.gotArgs.Branch, "fishhawk/run-11111111/stage-22222222") {
		t.Errorf("branch = %q, want fishhawk/run-<short>/stage-<short>", fp.gotArgs.Branch)
	}
	if fp.gotArgs.RemoteURL != "https://github.com/kuhlman-labs/fishhawk" {
		t.Errorf("RemoteURL = %q", fp.gotArgs.RemoteURL)
	}
	// Push auth flows through actions/checkout's extraheader (set
	// by the auth pre-step in the workflow per #201), not through
	// gitops args.

	if fpr.gotArgs == nil {
		t.Fatal("OpenPR not called")
	}
	if fpr.gotArgs.Owner != "kuhlman-labs" || fpr.gotArgs.Repo != "fishhawk" {
		t.Errorf("owner/repo = %q/%q", fpr.gotArgs.Owner, fpr.gotArgs.Repo)
	}
	if fpr.gotArgs.Base != "main" {
		t.Errorf("base = %q", fpr.gotArgs.Base)
	}
	if fpr.gotToken != "ghs_app_token" {
		t.Errorf("PROpener token = %q, want ghs_app_token (the App installation token)", fpr.gotToken)
	}

	if fu.gotPRArgs == nil {
		t.Fatal("ShipPullRequest not called")
	}
	var sent map[string]any
	if err := json.Unmarshal(fu.gotPRArgs.Body, &sent); err != nil {
		t.Fatalf("decode shipped body: %v", err)
	}
	for _, want := range []string{"pr_number", "pr_url", "branch", "head_sha", "base_sha", "title"} {
		if _, ok := sent[want]; !ok {
			t.Errorf("shipped body missing %q: %+v", want, sent)
		}
	}

	if !strings.Contains(stderr.String(), `"event":"pull_request_opened"`) ||
		!strings.Contains(stderr.String(), `"event":"pull_request_uploaded"`) {
		t.Errorf("missing pr lifecycle log lines:\n%s", stderr.String())
	}
}

func TestRun_ImplementStage_NoChanges_SkipsPRAndShip(t *testing.T) {
	implementEnv(t, "kuhlman-labs/fishhawk", "main")
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})
	fu := newFakeUploader(t)
	fu.promptResp = &upload.FetchedPrompt{
		StageID:    "22222222-3333-4444-5555-666666666666",
		StageType:  "implement",
		Prompt:     "implement",
		PromptHash: "h",
	}
	withFakeUploader(t, fu)
	fp := &fakePusher{result: &gitops.CommitAndPushResult{NoChanges: true, BaseSHA: "base"}}
	fpr := &fakePROpener{}
	withFakeGitOps(t, fp, fpr)

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "11111111-2222-3333-4444-555555555555",
		"--backend-url", "https://api.fishhawk.test",
		"--workflow", "feature_change", "--stage", "implement",
		"--stage-id", "22222222-3333-4444-5555-666666666666",
		"--fetch-prompt", "--upload-trace",
	}, &stderr)
	if got != exitOK {
		t.Fatalf("run = %d, want exitOK:\n%s", got, stderr.String())
	}
	if fpr.gotArgs != nil {
		t.Error("OpenPR should not be called when there are no changes")
	}
	if fu.gotPRArgs != nil {
		t.Error("ShipPullRequest should not be called when there are no changes")
	}
	if !strings.Contains(stderr.String(), `"event":"implement_no_changes"`) {
		t.Errorf("missing implement_no_changes log:\n%s", stderr.String())
	}
}

func TestRun_ImplementStage_PushError_CategoryC(t *testing.T) {
	implementEnv(t, "kuhlman-labs/fishhawk", "main")
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})
	fu := newFakeUploader(t)
	fu.promptResp = &upload.FetchedPrompt{
		StageID:    "22222222-3333-4444-5555-666666666666",
		StageType:  "implement",
		Prompt:     "implement",
		PromptHash: "h",
	}
	withFakeUploader(t, fu)
	fp := &fakePusher{err: errors.New("push: bad credentials")}
	withFakeGitOps(t, fp, &fakePROpener{})

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "11111111-2222-3333-4444-555555555555",
		"--backend-url", "https://api.fishhawk.test",
		"--workflow", "feature_change", "--stage", "implement",
		"--stage-id", "22222222-3333-4444-5555-666666666666",
		"--fetch-prompt", "--upload-trace",
	}, &stderr)
	if got != exitFailure {
		t.Errorf("run = %d, want exitFailure", got)
	}
	if !strings.Contains(stderr.String(), `"category":"C"`) {
		t.Errorf("expected category-C on push error, got:\n%s", stderr.String())
	}
}

func TestRun_ImplementStage_ShipPRInvalid_CategoryB(t *testing.T) {
	implementEnv(t, "kuhlman-labs/fishhawk", "main")
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})
	fu := newFakeUploader(t)
	fu.promptResp = &upload.FetchedPrompt{
		StageID:    "22222222-3333-4444-5555-666666666666",
		StageType:  "implement",
		Prompt:     "implement",
		PromptHash: "h",
	}
	fu.prErr = upload.ErrPullRequestInvalid
	withFakeUploader(t, fu)
	withFakeGitOps(t, &fakePusher{}, &fakePROpener{})

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "11111111-2222-3333-4444-555555555555",
		"--backend-url", "https://api.fishhawk.test",
		"--workflow", "feature_change", "--stage", "implement",
		"--stage-id", "22222222-3333-4444-5555-666666666666",
		"--fetch-prompt", "--upload-trace",
	}, &stderr)
	if got != exitFailure {
		t.Errorf("run = %d, want exitFailure", got)
	}
	if !strings.Contains(stderr.String(), `"category":"B"`) {
		t.Errorf("expected category-B on schema reject, got:\n%s", stderr.String())
	}
}

func TestRun_ImplementStage_PlanOutWithImplementStage_DoesNotValidatePlan(t *testing.T) {
	// Workflow file passes plan-out unconditionally; for an
	// implement stage there's no plan file at that path. The
	// runner must not fail-by-default — it should skip plan
	// validation entirely.
	implementEnv(t, "kuhlman-labs/fishhawk", "main")
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})
	fu := newFakeUploader(t)
	fu.promptResp = &upload.FetchedPrompt{
		StageID:    "22222222-3333-4444-5555-666666666666",
		StageType:  "implement",
		Prompt:     "implement",
		PromptHash: "h",
	}
	withFakeUploader(t, fu)
	withFakeGitOps(t, &fakePusher{}, &fakePROpener{})

	dir := t.TempDir()
	missingPlan := filepath.Join(dir, "no-such-plan.json")
	var stderr strings.Builder
	got := run([]string{
		"--run-id", "11111111-2222-3333-4444-555555555555",
		"--backend-url", "https://api.fishhawk.test",
		"--workflow", "feature_change", "--stage", "implement",
		"--stage-id", "22222222-3333-4444-5555-666666666666",
		"--fetch-prompt", "--upload-trace",
		"--plan-out", missingPlan, // file doesn't exist; would fail validation pre-fix
	}, &stderr)
	if got != exitOK {
		t.Fatalf("run = %d, want exitOK (plan validation should be skipped for implement stage):\n%s", got, stderr.String())
	}
	if fu.gotPlanArgs != nil {
		t.Error("ShipPlan should not be called for implement stage")
	}
}

func TestRun_ImplementStage_InstallationTokenFetchFails_CategoryC(t *testing.T) {
	// Backend returns 502 (or any error) when fetching the App
	// token. The implement stage should abort with category-C
	// before any git push or PR is attempted.
	implementEnv(t, "kuhlman-labs/fishhawk", "main")
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})
	fu := newFakeUploader(t)
	fu.promptResp = &upload.FetchedPrompt{
		StageID:    "22222222-3333-4444-5555-666666666666",
		StageType:  "implement",
		Prompt:     "implement",
		PromptHash: "h",
	}
	fu.instTokenErr = errors.New("backend: installation_token_issuance_failed")
	withFakeUploader(t, fu)
	fp := &fakePusher{}
	fpr := &fakePROpener{}
	withFakeGitOps(t, fp, fpr)

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "11111111-2222-3333-4444-555555555555",
		"--backend-url", "https://api.fishhawk.test",
		"--workflow", "feature_change", "--stage", "implement",
		"--stage-id", "22222222-3333-4444-5555-666666666666",
		"--fetch-prompt", "--upload-trace",
	}, &stderr)
	if got != exitFailure {
		t.Errorf("run = %d, want exitFailure", got)
	}
	if !strings.Contains(stderr.String(), `"category":"C"`) {
		t.Errorf("expected category-C on token-fetch error, got:\n%s", stderr.String())
	}
	if fp.gotArgs != nil {
		t.Error("CommitAndPush should not be called when token fetch fails")
	}
}

func TestRun_ImplementStage_AlwaysFetchesFreshTokenBeforePush(t *testing.T) {
	// Even with FISHHAWK_GITHUB_TOKEN set in env (the auth pre-
	// step's pass-through), the runner always mints a fresh token
	// before push so a long agent run can outlive the original
	// token's 1-hour TTL. The audit chain gets two
	// installation_token_issued events per implement stage: the
	// OIDC one at workflow start, the Ed25519 one here.
	implementEnv(t, "kuhlman-labs/fishhawk", "main")
	t.Setenv("FISHHAWK_GITHUB_TOKEN", "stale-pre-step-token")
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})
	fu := newFakeUploader(t)
	fu.promptResp = &upload.FetchedPrompt{
		StageID:    "22222222-3333-4444-5555-666666666666",
		StageType:  "implement",
		Prompt:     "implement",
		PromptHash: "h",
	}
	withFakeUploader(t, fu)
	fp := &fakePusher{}
	fpr := &fakePROpener{}
	withFakeGitOps(t, fp, fpr)

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "11111111-2222-3333-4444-555555555555",
		"--backend-url", "https://api.fishhawk.test",
		"--workflow", "feature_change", "--stage", "implement",
		"--stage-id", "22222222-3333-4444-5555-666666666666",
		"--fetch-prompt", "--upload-trace",
	}, &stderr)
	if got != exitOK {
		t.Fatalf("run = %d, want exitOK:\n%s", got, stderr.String())
	}
	// Always-fetch invariant: the runner called FetchInstallationToken
	// regardless of FISHHAWK_GITHUB_TOKEN being set in env.
	if fu.gotInstTokenArgs == nil {
		t.Error("FetchInstallationToken must be called every implement stage to get a non-expired token")
	}
	// The fresh token from the backend (not the env one) reaches
	// gitops as PushToken and the PR opener.
	if fp.gotArgs == nil {
		t.Fatal("CommitAndPush not called")
	}
	if fp.gotArgs.PushToken != "ghs_app_token" {
		t.Errorf("PushToken = %q, want ghs_app_token (the fresh backend-minted token, NOT the stale env token)", fp.gotArgs.PushToken)
	}
	if fpr.gotToken != "ghs_app_token" {
		t.Errorf("PROpener token = %q, want ghs_app_token", fpr.gotToken)
	}
}

// withPRDescriptionPath redirects pullRequestDescriptionPath to a
// temp dir for the duration of the test, restoring the production
// value via t.Cleanup. Tests that write to the file should call
// this before writing.
func withPRDescriptionPath(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "fishhawk-pr.md")
	orig := pullRequestDescriptionPath
	pullRequestDescriptionPath = path
	t.Cleanup(func() { pullRequestDescriptionPath = orig })
	return path
}

func TestPRTitleAndBody_AgentAuthored_HappyPath(t *testing.T) {
	path := withPRDescriptionPath(t)
	if err := os.WriteFile(path, []byte("Add make minio-init target\n\n## Why\n\nLocal stack needed a bucket-init step.\n\nCloses #184\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	cfg := config{
		runID:      "11111111-2222-3333-4444-555555555555",
		stageID:    "22222222-3333-4444-5555-666666666666",
		backendURL: "https://api.fishhawk.test",
	}
	var stderr strings.Builder
	title, body := prTitleAndBody(cfg, "fishhawk/run-x/stage-y", &stderr)
	if title != "Add make minio-init target" {
		t.Errorf("title = %q, want agent's first line", title)
	}
	if !strings.Contains(body, "## Why") {
		t.Errorf("body should preserve agent markdown, got:\n%s", body)
	}
	if !strings.Contains(body, "Closes #184") {
		t.Errorf("body should include the Closes line, got:\n%s", body)
	}
	// Footer must be appended for audit-trail provenance.
	if !strings.Contains(body, "Audit log:") || !strings.Contains(body, cfg.runID) {
		t.Errorf("body missing Fishhawk attribution footer:\n%s", body)
	}
	// No template-warning logs on the happy path.
	if strings.Contains(stderr.String(), "pr_template_invalid") || strings.Contains(stderr.String(), "pr_template_warning") {
		t.Errorf("happy path should produce no template warnings, got:\n%s", stderr.String())
	}
}

func TestPRTitleAndBody_AgentAuthored_TitleOnly(t *testing.T) {
	path := withPRDescriptionPath(t)
	if err := os.WriteFile(path, []byte("Just the title\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	var stderr strings.Builder
	title, body := prTitleAndBody(config{
		runID: "r", stageID: "s", backendURL: "https://x",
	}, "branch", &stderr)
	if title != "Just the title" {
		t.Errorf("title = %q", title)
	}
	// Body is empty + footer; the title-only case is allowed.
	if !strings.Contains(body, "Audit log:") {
		t.Errorf("footer should still be appended, got:\n%s", body)
	}
	// Should warn (not error) because title-only is non-canonical.
	if !strings.Contains(stderr.String(), "pr_template_warning") {
		t.Errorf("expected pr_template_warning for title-only, got:\n%s", stderr.String())
	}
}

func TestPRTitleAndBody_AgentAuthored_NoBlankLine(t *testing.T) {
	path := withPRDescriptionPath(t)
	// Title and body separated only by a single \n (no blank line).
	if err := os.WriteFile(path, []byte("Title here\nBody starts immediately.\nMore body.\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	var stderr strings.Builder
	title, body := prTitleAndBody(config{
		runID: "r", stageID: "s", backendURL: "https://x",
	}, "branch", &stderr)
	if title != "Title here" {
		t.Errorf("title = %q", title)
	}
	if !strings.Contains(body, "Body starts immediately.") {
		t.Errorf("body missing first line:\n%s", body)
	}
	// Should warn but still parse successfully.
	if !strings.Contains(stderr.String(), "pr_template_warning") {
		t.Errorf("expected pr_template_warning for missing blank line, got:\n%s", stderr.String())
	}
}

func TestPRTitleAndBody_FallbackWhenFileMissing(t *testing.T) {
	// withPRDescriptionPath points at a temp file, but we don't
	// write it. Helper must fall back silently.
	withPRDescriptionPath(t)
	var stderr strings.Builder
	title, body := prTitleAndBody(config{
		runID:      "11111111-2222-3333-4444-555555555555",
		stageID:    "22222222-3333-4444-5555-666666666666",
		backendURL: "https://api.fishhawk.test",
	}, "fishhawk/run-x/stage-y", &stderr)
	if !strings.HasPrefix(title, "Fishhawk: implement stage") {
		t.Errorf("fallback title should use the generic template, got %q", title)
	}
	if !strings.Contains(body, "Opened by Fishhawk for run") {
		t.Errorf("fallback body should use the generic template:\n%s", body)
	}
	// Missing file is the common no-op path; no warning logged.
	if strings.Contains(stderr.String(), "pr_template_") {
		t.Errorf("missing file should be silent, got:\n%s", stderr.String())
	}
}

func TestPRTitleAndBody_FallbackWhenFileEmpty(t *testing.T) {
	path := withPRDescriptionPath(t)
	if err := os.WriteFile(path, []byte(""), 0o600); err != nil {
		t.Fatal(err)
	}
	var stderr strings.Builder
	title, _ := prTitleAndBody(config{
		runID: "r", stageID: "s", backendURL: "https://x",
	}, "branch", &stderr)
	if !strings.HasPrefix(title, "Fishhawk:") {
		t.Errorf("empty file should fall back, got title %q", title)
	}
	if !strings.Contains(stderr.String(), "pr_template_invalid") {
		t.Errorf("empty file should produce pr_template_invalid log, got:\n%s", stderr.String())
	}
}

func TestPRTitleAndBody_FallbackWhenTitleEmpty(t *testing.T) {
	path := withPRDescriptionPath(t)
	// First line is whitespace; that's not a usable title.
	if err := os.WriteFile(path, []byte("   \n\nbody only\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	var stderr strings.Builder
	title, _ := prTitleAndBody(config{
		runID: "r", stageID: "s", backendURL: "https://x",
	}, "branch", &stderr)
	if !strings.HasPrefix(title, "Fishhawk:") {
		t.Errorf("empty-title file should fall back, got title %q", title)
	}
	if !strings.Contains(stderr.String(), "pr_template_invalid") {
		t.Errorf("expected pr_template_invalid on empty title, got:\n%s", stderr.String())
	}
}

func TestRun_ImplementStage_PassesAgentAuthoredPRTitle(t *testing.T) {
	// End-to-end: agent wrote /tmp/fishhawk-pr.md (via the
	// PullRequestDescriptionPath constant in the prompt), the
	// runner reads it, and the agent's title + body land on the
	// gitops.OpenPRArgs and on the shipped pull_request artifact.
	prPath := withPRDescriptionPath(t)
	if err := os.WriteFile(prPath, []byte("Add make minio-init target\n\nThis adds an idempotent make target for the local MinIO bucket.\n\nCloses #184\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	implementEnv(t, "kuhlman-labs/fishhawk", "main")
	withFakeInvoker(t, &fakeInvoker{canned: agent.Result{OK: true}})
	fu := newFakeUploader(t)
	fu.promptResp = &upload.FetchedPrompt{
		StageID:    "22222222-3333-4444-5555-666666666666",
		StageType:  "implement",
		Prompt:     "implement",
		PromptHash: "h",
	}
	withFakeUploader(t, fu)
	fp := &fakePusher{}
	fpr := &fakePROpener{}
	withFakeGitOps(t, fp, fpr)

	var stderr strings.Builder
	got := run([]string{
		"--run-id", "11111111-2222-3333-4444-555555555555",
		"--backend-url", "https://api.fishhawk.test",
		"--workflow", "feature_change", "--stage", "implement",
		"--stage-id", "22222222-3333-4444-5555-666666666666",
		"--fetch-prompt", "--upload-trace",
	}, &stderr)
	if got != exitOK {
		t.Fatalf("run = %d, want exitOK:\n%s", got, stderr.String())
	}

	if fpr.gotArgs == nil {
		t.Fatal("OpenPR not called")
	}
	if fpr.gotArgs.Title != "Add make minio-init target" {
		t.Errorf("OpenPR title = %q, want agent-authored title", fpr.gotArgs.Title)
	}
	if !strings.Contains(fpr.gotArgs.Body, "Closes #184") {
		t.Errorf("OpenPR body should preserve agent's Closes line, got:\n%s", fpr.gotArgs.Body)
	}
	if !strings.Contains(fpr.gotArgs.Body, "Audit log:") {
		t.Errorf("OpenPR body should append Fishhawk attribution footer, got:\n%s", fpr.gotArgs.Body)
	}

	// And the shipped artifact body must reflect the same title.
	if fu.gotPRArgs == nil {
		t.Fatal("ShipPullRequest not called")
	}
	var shipped map[string]any
	if err := json.Unmarshal(fu.gotPRArgs.Body, &shipped); err != nil {
		t.Fatal(err)
	}
	if got := shipped["title"]; got != "Add make minio-init target" {
		t.Errorf("shipped artifact title = %v, want agent-authored", got)
	}
}
