// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package accountdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID          uuid.UUID          `json:"id"`
	Provider    string             `json:"provider"`
	AccountKey  string             `json:"account_key"`
	DisplayName *string            `json:"display_name"`
	Granularity string             `json:"granularity"`
	HomeRegion  *string            `json:"home_region"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AccountMember struct {
	ID        uuid.UUID          `json:"id"`
	AccountID uuid.UUID          `json:"account_id"`
	Provider  string             `json:"provider"`
	MemberRef string             `json:"member_ref"`
	Role      *string            `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Installation struct {
	ID              uuid.UUID          `json:"id"`
	AccountID       uuid.UUID          `json:"account_id"`
	Provider        string             `json:"provider"`
	InstallationRef string             `json:"installation_ref"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ForgeBaseUrl    *string            `json:"forge_base_url"`
	OauthBaseUrl    *string            `json:"oauth_base_url"`
}
