// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package accountdb

import (
	"context"

	"github.com/google/uuid"
)

const getAccount = `-- name: GetAccount :one
SELECT id, provider, account_key, display_name, granularity, home_region, created_at, updated_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.AccountKey,
		&i.DisplayName,
		&i.Granularity,
		&i.HomeRegion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByKey = `-- name: GetAccountByKey :one
SELECT id, provider, account_key, display_name, granularity, home_region, created_at, updated_at FROM accounts WHERE provider = $1 AND account_key = $2
`

type GetAccountByKeyParams struct {
	Provider   string `json:"provider"`
	AccountKey string `json:"account_key"`
}

func (q *Queries) GetAccountByKey(ctx context.Context, arg GetAccountByKeyParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByKey, arg.Provider, arg.AccountKey)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.AccountKey,
		&i.DisplayName,
		&i.Granularity,
		&i.HomeRegion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountMemberRole = `-- name: GetAccountMemberRole :one
SELECT role FROM account_members
 WHERE account_id = $1
   AND provider = $2
   AND member_ref = $3
`

type GetAccountMemberRoleParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Provider  string    `json:"provider"`
	MemberRef string    `json:"member_ref"`
}

// The handler-authz role lookup (E44.5 / #1829): the caller's role in an
// account, keyed on the forge-neutral (account_id, provider, member_ref).
// role is nullable — a grant with no explicit role scans as NULL, which the
// Go layer interprets as member-tier (least privilege). No row (no membership)
// surfaces as pgx.ErrNoRows, also member-tier at the caller.
func (q *Queries) GetAccountMemberRole(ctx context.Context, arg GetAccountMemberRoleParams) (*string, error) {
	row := q.db.QueryRow(ctx, getAccountMemberRole, arg.AccountID, arg.Provider, arg.MemberRef)
	var role *string
	err := row.Scan(&role)
	return role, err
}

const getInstallationByRef = `-- name: GetInstallationByRef :one
SELECT id, account_id, provider, installation_ref, created_at, updated_at, forge_base_url, oauth_base_url FROM installations WHERE provider = $1 AND installation_ref = $2
`

type GetInstallationByRefParams struct {
	Provider        string `json:"provider"`
	InstallationRef string `json:"installation_ref"`
}

func (q *Queries) GetInstallationByRef(ctx context.Context, arg GetInstallationByRefParams) (Installation, error) {
	row := q.db.QueryRow(ctx, getInstallationByRef, arg.Provider, arg.InstallationRef)
	var i Installation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.InstallationRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ForgeBaseUrl,
		&i.OauthBaseUrl,
	)
	return i, err
}

const listAccountMembers = `-- name: ListAccountMembers :many
SELECT id, account_id, provider, member_ref, role, created_at, updated_at FROM account_members
 WHERE account_id = $1
 ORDER BY created_at ASC, id ASC
`

// Insertion order (created_at ASC + id tiebreak) so a membership roster renders
// stably.
func (q *Queries) ListAccountMembers(ctx context.Context, accountID uuid.UUID) ([]AccountMember, error) {
	rows, err := q.db.Query(ctx, listAccountMembers, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountMember
	for rows.Next() {
		var i AccountMember
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Provider,
			&i.MemberRef,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsByAccountKey = `-- name: ListAccountsByAccountKey :many
SELECT id, provider, account_key, display_name, granularity, home_region, created_at, updated_at FROM accounts
 WHERE account_key = $1
 ORDER BY provider ASC
`

// The provider-discriminator lookup for the per-repo conventions loader
// (E45.16 / #2022): keyed by account_key ALONE — the provider is exactly what
// the caller is resolving. UNIQUE(provider, account_key) permits the same key
// under both providers, so this can return more than one row; the resolver
// treats that as ambiguous (found=false), never an arbitrary first row. Stable
// provider order keeps the multi-row result deterministic anyway.
func (q *Queries) ListAccountsByAccountKey(ctx context.Context, accountKey string) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByAccountKey, accountKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.AccountKey,
			&i.DisplayName,
			&i.Granularity,
			&i.HomeRegion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutoJoinAccountsByKeys = `-- name: ListAutoJoinAccountsByKeys :many
SELECT id, account_key, auto_join_role
  FROM accounts
 WHERE provider = $1
   AND granularity = 'organization'
   AND auto_join_role IS NOT NULL
   AND account_key = ANY($2::text[])
 ORDER BY account_key ASC
`

type ListAutoJoinAccountsByKeysParams struct {
	Provider    string   `json:"provider"`
	AccountKeys []string `json:"account_keys"`
}

type ListAutoJoinAccountsByKeysRow struct {
	ID           uuid.UUID `json:"id"`
	AccountKey   string    `json:"account_key"`
	AutoJoinRole *string   `json:"auto_join_role"`
}

// Auto-join bootstrap intersection (E44.3): organization-granularity accounts
// whose auto_join_role policy is set and whose org key appears in the user's
// LIVE forge org list. Stable account_key order keeps the callback's
// deterministic-first pick reproducible.
func (q *Queries) ListAutoJoinAccountsByKeys(ctx context.Context, arg ListAutoJoinAccountsByKeysParams) ([]ListAutoJoinAccountsByKeysRow, error) {
	rows, err := q.db.Query(ctx, listAutoJoinAccountsByKeys, arg.Provider, arg.AccountKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAutoJoinAccountsByKeysRow
	for rows.Next() {
		var i ListAutoJoinAccountsByKeysRow
		if err := rows.Scan(&i.ID, &i.AccountKey, &i.AutoJoinRole); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberGrantsByRef = `-- name: ListMemberGrantsByRef :many
SELECT m.account_id, m.origin, a.account_key, a.granularity, a.auto_join_role
  FROM account_members m
  JOIN accounts a ON a.id = m.account_id
 WHERE m.provider = $1
   AND m.member_ref = $2
 ORDER BY m.created_at ASC, m.id ASC
`

type ListMemberGrantsByRefParams struct {
	Provider  string `json:"provider"`
	MemberRef string `json:"member_ref"`
}

type ListMemberGrantsByRefRow struct {
	AccountID    uuid.UUID `json:"account_id"`
	Origin       string    `json:"origin"`
	AccountKey   string    `json:"account_key"`
	Granularity  string    `json:"granularity"`
	AutoJoinRole *string   `json:"auto_join_role"`
}

// The login-gate admission read (E44.3 / ADR-057 Amendment A2): every grant for
// a forge member joined with its account's admission fields, so the resolver
// can admit invited rows DB-only and re-verify auto_join rows against their
// policy predicate. Explicit columns (a per-query Row struct) — the resolver
// needs only the admission slice, not the whole roster row.
func (q *Queries) ListMemberGrantsByRef(ctx context.Context, arg ListMemberGrantsByRefParams) ([]ListMemberGrantsByRefRow, error) {
	rows, err := q.db.Query(ctx, listMemberGrantsByRef, arg.Provider, arg.MemberRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemberGrantsByRefRow
	for rows.Next() {
		var i ListMemberGrantsByRefRow
		if err := rows.Scan(
			&i.AccountID,
			&i.Origin,
			&i.AccountKey,
			&i.Granularity,
			&i.AutoJoinRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinAccountHomeRegion = `-- name: PinAccountHomeRegion :one

UPDATE accounts
   SET home_region = $3,
       updated_at  = now()
 WHERE provider = $1
   AND account_key = $2
   AND (home_region IS NULL OR home_region = $3)
RETURNING id, provider, account_key, display_name, granularity, home_region, created_at, updated_at
`

type PinAccountHomeRegionParams struct {
	Provider   string  `json:"provider"`
	AccountKey string  `json:"account_key"`
	HomeRegion *string `json:"home_region"`
}

// The cell-side region pin (ADR-062 A2.3, E44.7 / #1831). First-write-wins is
// enforced HERE, in SQL, rather than as a check-then-act read/write pair in Go:
// the WHERE clause matches only a row that is unpinned or ALREADY pinned to the
// same region, so two concurrent pins proposing different regions serialize on
// the row lock and exactly one can match.
//
// The statement is UPDATE-only ON PURPOSE — it must never create an account. A
// handoff naming an account this cell has never heard of matches no row and is
// refused, not silently materialized (ADR-062 A2.5).
//
// Zero rows is therefore ambiguous by design and the Go layer disambiguates:
// either the account does not exist here, or it is already pinned to a
// DIFFERENT region. Both are refusals; neither is an overwrite.
func (q *Queries) PinAccountHomeRegion(ctx context.Context, arg PinAccountHomeRegionParams) (Account, error) {
	row := q.db.QueryRow(ctx, pinAccountHomeRegion, arg.Provider, arg.AccountKey, arg.HomeRegion)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.AccountKey,
		&i.DisplayName,
		&i.Granularity,
		&i.HomeRegion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAccount = `-- name: UpsertAccount :one

INSERT INTO accounts (id, provider, account_key, display_name, granularity, home_region)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (provider, account_key) DO UPDATE
   SET display_name = EXCLUDED.display_name,
       granularity  = EXCLUDED.granularity,
       home_region  = EXCLUDED.home_region
RETURNING id, provider, account_key, display_name, granularity, home_region, created_at, updated_at
`

type UpsertAccountParams struct {
	ID          uuid.UUID `json:"id"`
	Provider    string    `json:"provider"`
	AccountKey  string    `json:"account_key"`
	DisplayName *string   `json:"display_name"`
	Granularity string    `json:"granularity"`
	HomeRegion  *string   `json:"home_region"`
}

// Idempotent create-or-update keyed on the forge-neutral natural key
// (provider, account_key). The endpoint columns now live on installations
// (Amendment A1), so accounts carries none.
func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, upsertAccount,
		arg.ID,
		arg.Provider,
		arg.AccountKey,
		arg.DisplayName,
		arg.Granularity,
		arg.HomeRegion,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.AccountKey,
		&i.DisplayName,
		&i.Granularity,
		&i.HomeRegion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAccountMember = `-- name: UpsertAccountMember :one
INSERT INTO account_members (id, account_id, provider, member_ref, role)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (account_id, provider, member_ref) DO UPDATE
   SET role = EXCLUDED.role
RETURNING id, account_id, provider, member_ref, role, created_at, updated_at
`

type UpsertAccountMemberParams struct {
	ID        uuid.UUID `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
	Provider  string    `json:"provider"`
	MemberRef string    `json:"member_ref"`
	Role      *string   `json:"role"`
}

// Idempotent create-or-update keyed on (account_id, provider, member_ref).
func (q *Queries) UpsertAccountMember(ctx context.Context, arg UpsertAccountMemberParams) (AccountMember, error) {
	row := q.db.QueryRow(ctx, upsertAccountMember,
		arg.ID,
		arg.AccountID,
		arg.Provider,
		arg.MemberRef,
		arg.Role,
	)
	var i AccountMember
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.MemberRef,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAccountMemberWithOrigin = `-- name: UpsertAccountMemberWithOrigin :exec
INSERT INTO account_members (id, account_id, provider, member_ref, role, origin)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (account_id, provider, member_ref) DO UPDATE
   SET role   = EXCLUDED.role,
       origin = EXCLUDED.origin
`

type UpsertAccountMemberWithOriginParams struct {
	ID        uuid.UUID `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
	Provider  string    `json:"provider"`
	MemberRef string    `json:"member_ref"`
	Role      *string   `json:"role"`
	Origin    string    `json:"origin"`
}

// Mint (or refresh) a grant with an explicit origin — the auto-join bootstrap's
// audited origin='auto_join' write. UpsertAccountMember above keeps its
// pre-0056 shape (origin defaults to 'invited').
func (q *Queries) UpsertAccountMemberWithOrigin(ctx context.Context, arg UpsertAccountMemberWithOriginParams) error {
	_, err := q.db.Exec(ctx, upsertAccountMemberWithOrigin,
		arg.ID,
		arg.AccountID,
		arg.Provider,
		arg.MemberRef,
		arg.Role,
		arg.Origin,
	)
	return err
}

const upsertInstallation = `-- name: UpsertInstallation :one
INSERT INTO installations (id, account_id, provider, installation_ref, forge_base_url, oauth_base_url)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (provider, installation_ref) DO UPDATE
   SET account_id     = EXCLUDED.account_id,
       forge_base_url = EXCLUDED.forge_base_url,
       oauth_base_url = EXCLUDED.oauth_base_url
RETURNING id, account_id, provider, installation_ref, created_at, updated_at, forge_base_url, oauth_base_url
`

type UpsertInstallationParams struct {
	ID              uuid.UUID `json:"id"`
	AccountID       uuid.UUID `json:"account_id"`
	Provider        string    `json:"provider"`
	InstallationRef string    `json:"installation_ref"`
	ForgeBaseUrl    *string   `json:"forge_base_url"`
	OauthBaseUrl    *string   `json:"oauth_base_url"`
}

// Idempotent create-or-update keyed on (provider, installation_ref). Carries
// the relocated forge_base_url / oauth_base_url endpoint columns (Amendment A1).
func (q *Queries) UpsertInstallation(ctx context.Context, arg UpsertInstallationParams) (Installation, error) {
	row := q.db.QueryRow(ctx, upsertInstallation,
		arg.ID,
		arg.AccountID,
		arg.Provider,
		arg.InstallationRef,
		arg.ForgeBaseUrl,
		arg.OauthBaseUrl,
	)
	var i Installation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.InstallationRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ForgeBaseUrl,
		&i.OauthBaseUrl,
	)
	return i, err
}
