// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package accountdb

import (
	"context"

	"github.com/google/uuid"
)

const getAccount = `-- name: GetAccount :one
SELECT id, provider, account_key, display_name, granularity, home_region, created_at, updated_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.AccountKey,
		&i.DisplayName,
		&i.Granularity,
		&i.HomeRegion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByKey = `-- name: GetAccountByKey :one
SELECT id, provider, account_key, display_name, granularity, home_region, created_at, updated_at FROM accounts WHERE provider = $1 AND account_key = $2
`

type GetAccountByKeyParams struct {
	Provider   string `json:"provider"`
	AccountKey string `json:"account_key"`
}

func (q *Queries) GetAccountByKey(ctx context.Context, arg GetAccountByKeyParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByKey, arg.Provider, arg.AccountKey)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.AccountKey,
		&i.DisplayName,
		&i.Granularity,
		&i.HomeRegion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstallationByRef = `-- name: GetInstallationByRef :one
SELECT id, account_id, provider, installation_ref, created_at, updated_at, forge_base_url, oauth_base_url FROM installations WHERE provider = $1 AND installation_ref = $2
`

type GetInstallationByRefParams struct {
	Provider        string `json:"provider"`
	InstallationRef string `json:"installation_ref"`
}

func (q *Queries) GetInstallationByRef(ctx context.Context, arg GetInstallationByRefParams) (Installation, error) {
	row := q.db.QueryRow(ctx, getInstallationByRef, arg.Provider, arg.InstallationRef)
	var i Installation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.InstallationRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ForgeBaseUrl,
		&i.OauthBaseUrl,
	)
	return i, err
}

const listAccountMembers = `-- name: ListAccountMembers :many
SELECT id, account_id, provider, member_ref, role, created_at, updated_at FROM account_members
 WHERE account_id = $1
 ORDER BY created_at ASC, id ASC
`

// Insertion order (created_at ASC + id tiebreak) so a membership roster renders
// stably.
func (q *Queries) ListAccountMembers(ctx context.Context, accountID uuid.UUID) ([]AccountMember, error) {
	rows, err := q.db.Query(ctx, listAccountMembers, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountMember
	for rows.Next() {
		var i AccountMember
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Provider,
			&i.MemberRef,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAccount = `-- name: UpsertAccount :one

INSERT INTO accounts (id, provider, account_key, display_name, granularity, home_region)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (provider, account_key) DO UPDATE
   SET display_name = EXCLUDED.display_name,
       granularity  = EXCLUDED.granularity,
       home_region  = EXCLUDED.home_region
RETURNING id, provider, account_key, display_name, granularity, home_region, created_at, updated_at
`

type UpsertAccountParams struct {
	ID          uuid.UUID `json:"id"`
	Provider    string    `json:"provider"`
	AccountKey  string    `json:"account_key"`
	DisplayName *string   `json:"display_name"`
	Granularity string    `json:"granularity"`
	HomeRegion  *string   `json:"home_region"`
}

// Idempotent create-or-update keyed on the forge-neutral natural key
// (provider, account_key). The endpoint columns now live on installations
// (Amendment A1), so accounts carries none.
func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, upsertAccount,
		arg.ID,
		arg.Provider,
		arg.AccountKey,
		arg.DisplayName,
		arg.Granularity,
		arg.HomeRegion,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.AccountKey,
		&i.DisplayName,
		&i.Granularity,
		&i.HomeRegion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAccountMember = `-- name: UpsertAccountMember :one
INSERT INTO account_members (id, account_id, provider, member_ref, role)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (account_id, provider, member_ref) DO UPDATE
   SET role = EXCLUDED.role
RETURNING id, account_id, provider, member_ref, role, created_at, updated_at
`

type UpsertAccountMemberParams struct {
	ID        uuid.UUID `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
	Provider  string    `json:"provider"`
	MemberRef string    `json:"member_ref"`
	Role      *string   `json:"role"`
}

// Idempotent create-or-update keyed on (account_id, provider, member_ref).
func (q *Queries) UpsertAccountMember(ctx context.Context, arg UpsertAccountMemberParams) (AccountMember, error) {
	row := q.db.QueryRow(ctx, upsertAccountMember,
		arg.ID,
		arg.AccountID,
		arg.Provider,
		arg.MemberRef,
		arg.Role,
	)
	var i AccountMember
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.MemberRef,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertInstallation = `-- name: UpsertInstallation :one
INSERT INTO installations (id, account_id, provider, installation_ref, forge_base_url, oauth_base_url)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (provider, installation_ref) DO UPDATE
   SET account_id     = EXCLUDED.account_id,
       forge_base_url = EXCLUDED.forge_base_url,
       oauth_base_url = EXCLUDED.oauth_base_url
RETURNING id, account_id, provider, installation_ref, created_at, updated_at, forge_base_url, oauth_base_url
`

type UpsertInstallationParams struct {
	ID              uuid.UUID `json:"id"`
	AccountID       uuid.UUID `json:"account_id"`
	Provider        string    `json:"provider"`
	InstallationRef string    `json:"installation_ref"`
	ForgeBaseUrl    *string   `json:"forge_base_url"`
	OauthBaseUrl    *string   `json:"oauth_base_url"`
}

// Idempotent create-or-update keyed on (provider, installation_ref). Carries
// the relocated forge_base_url / oauth_base_url endpoint columns (Amendment A1).
func (q *Queries) UpsertInstallation(ctx context.Context, arg UpsertInstallationParams) (Installation, error) {
	row := q.db.QueryRow(ctx, upsertInstallation,
		arg.ID,
		arg.AccountID,
		arg.Provider,
		arg.InstallationRef,
		arg.ForgeBaseUrl,
		arg.OauthBaseUrl,
	)
	var i Installation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.InstallationRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ForgeBaseUrl,
		&i.OauthBaseUrl,
	)
	return i, err
}
