package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// repoRoot walks up to the go.work workspace root.
func repoRoot(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.work")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatalf("could not resolve repo root")
		}
		dir = parent
	}
}

// TestCheckMode_CleanTree asserts --check reports no drift on the
// committed tree (the pages were generated by this same code).
func TestCheckMode_CleanTree(t *testing.T) {
	root := repoRoot(t)
	var out, errb strings.Builder
	code := run([]string{"--root", root, "--check"}, &out, &errb)
	if code != 0 {
		t.Fatalf("check mode = %d, want 0; stderr:\n%s", code, errb.String())
	}
	if !strings.Contains(out.String(), "up to date") {
		t.Errorf("expected up-to-date message, got:\n%s", out.String())
	}
}

// TestWriteMode_CleanTree drives the WRITE path against the committed
// tree: because the pages are already current, WriteFile reports every
// page unchanged and mutates nothing. This covers the write branch and
// docgen.WriteFile's read-compare-early-return without touching the tree.
func TestWriteMode_CleanTree(t *testing.T) {
	root := repoRoot(t)
	var out, errb strings.Builder
	code := run([]string{"--root", root}, &out, &errb)
	if code != 0 {
		t.Fatalf("write mode = %d, want 0; stderr:\n%s", code, errb.String())
	}
	if strings.Contains(out.String(), "regenerated") {
		t.Errorf("committed tree should be up to date, but a page was rewritten:\n%s", out.String())
	}
	if !strings.Contains(out.String(), "unchanged") {
		t.Errorf("expected unchanged lines, got:\n%s", out.String())
	}
}

// TestDefaultRoot_Discovered covers findRepoRoot: with no --root the
// binary discovers the workspace root from the working directory, then
// runs the write path (unchanged, no mutation).
func TestDefaultRoot_Discovered(t *testing.T) {
	var out, errb strings.Builder
	code := run([]string{}, &out, &errb)
	if code != 0 {
		t.Fatalf("default-root run = %d, want 0; stderr:\n%s", code, errb.String())
	}
	if !strings.Contains(out.String(), "unchanged") {
		t.Errorf("expected unchanged lines from discovered root, got:\n%s", out.String())
	}
}

// TestBadRoot_FailsClosed asserts a nonexistent --root errors rather than
// silently succeeding.
func TestBadRoot_FailsClosed(t *testing.T) {
	var out, errb strings.Builder
	code := run([]string{"--root", filepath.Join(t.TempDir(), "no-such"), "--check"}, &out, &errb)
	if code == 0 {
		t.Fatalf("check against a nonexistent root should fail, got 0")
	}
}

// TestBadFlag_Usage asserts an unknown flag returns the usage exit code.
func TestBadFlag_Usage(t *testing.T) {
	var out, errb strings.Builder
	if code := run([]string{"--nope"}, &out, &errb); code != 2 {
		t.Fatalf("unknown flag = %d, want 2", code)
	}
}

// mirrorRoot copies the canonical sources and the four committed reference
// pages into a temp root, so a test can corrupt a page and exercise the
// drift / regenerate branches without touching the real tree.
func mirrorRoot(t *testing.T) string {
	t.Helper()
	src := repoRoot(t)
	dst := t.TempDir()
	files := []string{
		"docs/spec/workflow-v0.schema.json",
		"docs/spec/workflow-v1.schema.json",
		"docs/spec/workflow-v2.schema.json",
		"docs/spec/plan-standard-v1.schema.json",
		"docs/spec/examples/workflow-v2-reuse.yaml",
		"docs/spec/examples/workflow-v2-backlog-grooming.yaml",
		"docs/api/v0.openapi.yaml",
		"site/src/content/docs/reference/workflow-spec.md",
		"site/src/content/docs/reference/plan-schema.md",
		"site/src/content/docs/reference/cli.md",
		"site/src/content/docs/reference/api.md",
	}
	for _, rel := range files {
		b, err := os.ReadFile(filepath.Join(src, rel))
		if err != nil {
			t.Fatalf("read %s: %v", rel, err)
		}
		out := filepath.Join(dst, rel)
		if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
			t.Fatalf("mkdir: %v", err)
		}
		if err := os.WriteFile(out, b, 0o644); err != nil {
			t.Fatalf("write %s: %v", rel, err)
		}
	}
	return dst
}

// corruptPage inserts a stray line inside a page's generated region.
func corruptPage(t *testing.T, root, rel, id string) {
	t.Helper()
	p := filepath.Join(root, rel)
	b, err := os.ReadFile(p)
	if err != nil {
		t.Fatalf("read %s: %v", rel, err)
	}
	marker := "<!-- BEGIN GENERATED " + id + " -->\n"
	s := strings.Replace(string(b), marker, marker+"STRAY DRIFT\n", 1)
	if err := os.WriteFile(p, []byte(s), 0o644); err != nil {
		t.Fatalf("write %s: %v", rel, err)
	}
}

// TestCheckMode_DetectsDrift corrupts a mirrored page and asserts --check
// exits non-zero naming it.
func TestCheckMode_DetectsDrift(t *testing.T) {
	root := mirrorRoot(t)
	corruptPage(t, root, "site/src/content/docs/reference/cli.md", "cli")
	var out, errb strings.Builder
	code := run([]string{"--root", root, "--check"}, &out, &errb)
	if code == 0 {
		t.Fatalf("check mode = 0 on a drifted tree, want non-zero")
	}
	if !strings.Contains(errb.String(), "cli.md") {
		t.Errorf("drift report should name cli.md, got:\n%s", errb.String())
	}
}

// TestNoRepoRoot_FailsClosed runs with no --root from a directory with no
// go.work above it, so findRepoRoot returns an error and run() exits 1.
func TestNoRepoRoot_FailsClosed(t *testing.T) {
	orig, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	t.Cleanup(func() { _ = os.Chdir(orig) })
	if err := os.Chdir(t.TempDir()); err != nil {
		t.Fatalf("chdir: %v", err)
	}
	var out, errb strings.Builder
	if code := run([]string{}, &out, &errb); code == 0 {
		t.Fatalf("run with no discoverable repo root = 0, want non-zero")
	}
	if !strings.Contains(errb.String(), "repo root") {
		t.Errorf("expected a repo-root error, got:\n%s", errb.String())
	}
}

// TestWriteMode_PageUnreadable replaces a page with a directory so
// WriteFile's read fails, exercising the write-error branch.
func TestWriteMode_PageUnreadable(t *testing.T) {
	root := mirrorRoot(t)
	p := filepath.Join(root, "site/src/content/docs/reference/cli.md")
	if err := os.Remove(p); err != nil {
		t.Fatalf("remove: %v", err)
	}
	if err := os.Mkdir(p, 0o755); err != nil { // a directory where a file is expected
		t.Fatalf("mkdir: %v", err)
	}
	var out, errb strings.Builder
	if code := run([]string{"--root", root}, &out, &errb); code == 0 {
		t.Fatalf("write mode over an unreadable page = 0, want non-zero")
	}
}

// TestWriteMode_Regenerates corrupts a mirrored page and asserts the write
// path rewrites it back to the generated content (exit 0).
func TestWriteMode_Regenerates(t *testing.T) {
	root := mirrorRoot(t)
	corruptPage(t, root, "site/src/content/docs/reference/api.md", "api")
	var out, errb strings.Builder
	code := run([]string{"--root", root}, &out, &errb)
	if code != 0 {
		t.Fatalf("write mode = %d, want 0; stderr:\n%s", code, errb.String())
	}
	if !strings.Contains(out.String(), "regenerated site/src/content/docs/reference/api.md") {
		t.Errorf("expected api.md to be regenerated, got:\n%s", out.String())
	}
	// A second --check should now be clean.
	var out2, errb2 strings.Builder
	if code := run([]string{"--root", root, "--check"}, &out2, &errb2); code != 0 {
		t.Fatalf("post-regenerate check = %d, want 0; stderr:\n%s", code, errb2.String())
	}
}
