// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package auditdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendAuditEntry = `-- name: AppendAuditEntry :one

INSERT INTO audit_entries (
    id, run_id, stage_id, ts, category, actor_kind, actor_subject,
    payload, prev_hash, entry_hash, account_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, sequence, run_id, stage_id, ts, category, actor_kind, actor_subject, payload, prev_hash, entry_hash, account_id
`

type AppendAuditEntryParams struct {
	ID           uuid.UUID          `json:"id"`
	RunID        *uuid.UUID         `json:"run_id"`
	StageID      *uuid.UUID         `json:"stage_id"`
	Ts           pgtype.Timestamptz `json:"ts"`
	Category     string             `json:"category"`
	ActorKind    *string            `json:"actor_kind"`
	ActorSubject *string            `json:"actor_subject"`
	Payload      []byte             `json:"payload"`
	PrevHash     *string            `json:"prev_hash"`
	EntryHash    string             `json:"entry_hash"`
	AccountID    *uuid.UUID         `json:"account_id"`
}

// Audit-entry queries consumed by the postgres adapter for the
// audit.Repository interface (E2.1 / #22). Append-only — no
// UpdateAuditEntry or DeleteAuditEntry queries exist or will exist
// in this file. Database-level triggers backstop the same invariant.
func (q *Queries) AppendAuditEntry(ctx context.Context, arg AppendAuditEntryParams) (AuditEntry, error) {
	row := q.db.QueryRow(ctx, appendAuditEntry,
		arg.ID,
		arg.RunID,
		arg.StageID,
		arg.Ts,
		arg.Category,
		arg.ActorKind,
		arg.ActorSubject,
		arg.Payload,
		arg.PrevHash,
		arg.EntryHash,
		arg.AccountID,
	)
	var i AuditEntry
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.RunID,
		&i.StageID,
		&i.Ts,
		&i.Category,
		&i.ActorKind,
		&i.ActorSubject,
		&i.Payload,
		&i.PrevHash,
		&i.EntryHash,
		&i.AccountID,
	)
	return i, err
}

const getAuditEntry = `-- name: GetAuditEntry :one
SELECT id, sequence, run_id, stage_id, ts, category, actor_kind, actor_subject, payload, prev_hash, entry_hash, account_id FROM audit_entries WHERE id = $1
`

func (q *Queries) GetAuditEntry(ctx context.Context, id uuid.UUID) (AuditEntry, error) {
	row := q.db.QueryRow(ctx, getAuditEntry, id)
	var i AuditEntry
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.RunID,
		&i.StageID,
		&i.Ts,
		&i.Category,
		&i.ActorKind,
		&i.ActorSubject,
		&i.Payload,
		&i.PrevHash,
		&i.EntryHash,
		&i.AccountID,
	)
	return i, err
}

const getLastAuditEntryForRun = `-- name: GetLastAuditEntryForRun :one
SELECT id, sequence, run_id, stage_id, ts, category, actor_kind, actor_subject, payload, prev_hash, entry_hash, account_id FROM audit_entries
WHERE run_id = $1
ORDER BY sequence DESC
LIMIT 1
`

// Used by Append to fetch prev_hash for the next entry in the run.
func (q *Queries) GetLastAuditEntryForRun(ctx context.Context, runID *uuid.UUID) (AuditEntry, error) {
	row := q.db.QueryRow(ctx, getLastAuditEntryForRun, runID)
	var i AuditEntry
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.RunID,
		&i.StageID,
		&i.Ts,
		&i.Category,
		&i.ActorKind,
		&i.ActorSubject,
		&i.Payload,
		&i.PrevHash,
		&i.EntryHash,
		&i.AccountID,
	)
	return i, err
}

const getLastGlobalAuditEntryForAccount = `-- name: GetLastGlobalAuditEntryForAccount :one
SELECT id, sequence, run_id, stage_id, ts, category, actor_kind, actor_subject, payload, prev_hash, entry_hash, account_id FROM audit_entries
 WHERE run_id IS NULL AND account_id = $1
 ORDER BY sequence DESC
 LIMIT 1
`

// Mirror of GetLastAuditEntryForRun for one tenant account's run-less
// chain partition (ADR-057 / #1828, was the single-partition
// GetLastGlobalAuditEntry, E2.7 / #138). Used by AppendGlobalChained
// to fetch prev_hash for the next non-run event (token issue/revoke,
// OAuth sign-in, etc.) within the account's chain. Served by the 0058
// partial index audit_entries_global_account_seq_idx.
func (q *Queries) GetLastGlobalAuditEntryForAccount(ctx context.Context, accountID *uuid.UUID) (AuditEntry, error) {
	row := q.db.QueryRow(ctx, getLastGlobalAuditEntryForAccount, accountID)
	var i AuditEntry
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.RunID,
		&i.StageID,
		&i.Ts,
		&i.Category,
		&i.ActorKind,
		&i.ActorSubject,
		&i.Payload,
		&i.PrevHash,
		&i.EntryHash,
		&i.AccountID,
	)
	return i, err
}

const getLastGlobalAuditEntryUntenanted = `-- name: GetLastGlobalAuditEntryUntenanted :one
SELECT id, sequence, run_id, stage_id, ts, category, actor_kind, actor_subject, payload, prev_hash, entry_hash, account_id FROM audit_entries
 WHERE run_id IS NULL AND account_id IS NULL
 ORDER BY sequence DESC
 LIMIT 1
`

// The account_id IS NULL variant of GetLastGlobalAuditEntryForAccount:
// the untenanted legacy partition (historical rows plus writers with no
// resolvable account — the #1829 NULL-allow window) stays one chain of
// its own.
func (q *Queries) GetLastGlobalAuditEntryUntenanted(ctx context.Context) (AuditEntry, error) {
	row := q.db.QueryRow(ctx, getLastGlobalAuditEntryUntenanted)
	var i AuditEntry
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.RunID,
		&i.StageID,
		&i.Ts,
		&i.Category,
		&i.ActorKind,
		&i.ActorSubject,
		&i.Payload,
		&i.PrevHash,
		&i.EntryHash,
		&i.AccountID,
	)
	return i, err
}

const listAuditEntriesForRunChain = `-- name: ListAuditEntriesForRunChain :many
WITH RECURSIVE run_chain AS (
    SELECT id FROM runs WHERE id = $1
    UNION ALL
    SELECT r.id FROM runs r
    JOIN run_chain rc ON r.parent_run_id = rc.id
    WHERE ($2::boolean OR r.decomposed_from IS NULL)
)
SELECT ae.id, ae.sequence, ae.run_id, ae.stage_id, ae.ts, ae.category,
       ae.actor_kind, ae.actor_subject, ae.payload, ae.prev_hash, ae.entry_hash,
       ae.account_id
FROM audit_entries ae
JOIN run_chain rc ON ae.run_id = rc.id
ORDER BY ae.sequence ASC
`

type ListAuditEntriesForRunChainParams struct {
	ParentRunID       uuid.UUID `json:"parent_run_id"`
	IncludeDecomposed bool      `json:"include_decomposed"`
}

func (q *Queries) ListAuditEntriesForRunChain(ctx context.Context, arg ListAuditEntriesForRunChainParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, listAuditEntriesForRunChain, arg.ParentRunID, arg.IncludeDecomposed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEntry
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.Sequence,
			&i.RunID,
			&i.StageID,
			&i.Ts,
			&i.Category,
			&i.ActorKind,
			&i.ActorSubject,
			&i.Payload,
			&i.PrevHash,
			&i.EntryHash,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEntriesAll = `-- name: ListAuditEntriesAll :many
SELECT id, sequence, run_id, stage_id, ts, category, actor_kind, actor_subject, payload, prev_hash, entry_hash, account_id FROM audit_entries
 WHERE ($1::text IS NULL OR category = $1::text)
   AND ($2::uuid  IS NULL OR run_id   = $2::uuid)
   AND ($3::uuid IS NULL OR account_id = $3::uuid OR account_id IS NULL)
 ORDER BY ts DESC, id DESC
`

type ListAuditEntriesAllParams struct {
	Category  *string    `json:"category"`
	RunID     *uuid.UUID `json:"run_id"`
	AccountID *uuid.UUID `json:"account_id"`
}

// Cross-chain feed (per-run rows + global-chain rows) used by the
// audit-log search surface (#211). Time-descending so the most-recent
// governance event is at the top; secondary sort on (id) keeps ordering
// deterministic when entries share a millisecond. Optional category +
// run_id filters; sqlc.narg makes them omittable from the WHERE.
// account_id (ADR-057 / #1830) scopes to a tenant workspace account: a
// set filter keeps the account's rows PLUS untenanted (NULL account_id)
// rows — the same contract as run.ListRuns — while NULL (unset) keeps
// the internal system readers' cross-account scans unconstrained.
func (q *Queries) ListAuditEntriesAll(ctx context.Context, arg ListAuditEntriesAllParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, listAuditEntriesAll, arg.Category, arg.RunID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEntry
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.Sequence,
			&i.RunID,
			&i.StageID,
			&i.Ts,
			&i.Category,
			&i.ActorKind,
			&i.ActorSubject,
			&i.Payload,
			&i.PrevHash,
			&i.EntryHash,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEntriesByCategory = `-- name: ListAuditEntriesByCategory :many
SELECT id, sequence, run_id, stage_id, ts, category, actor_kind, actor_subject, payload, prev_hash, entry_hash, account_id FROM audit_entries
WHERE run_id = $1 AND category = $2
ORDER BY sequence ASC
`

type ListAuditEntriesByCategoryParams struct {
	RunID    *uuid.UUID `json:"run_id"`
	Category string     `json:"category"`
}

func (q *Queries) ListAuditEntriesByCategory(ctx context.Context, arg ListAuditEntriesByCategoryParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, listAuditEntriesByCategory, arg.RunID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEntry
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.Sequence,
			&i.RunID,
			&i.StageID,
			&i.Ts,
			&i.Category,
			&i.ActorKind,
			&i.ActorSubject,
			&i.Payload,
			&i.PrevHash,
			&i.EntryHash,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEntriesForRun = `-- name: ListAuditEntriesForRun :many
SELECT id, sequence, run_id, stage_id, ts, category, actor_kind, actor_subject, payload, prev_hash, entry_hash, account_id FROM audit_entries
WHERE run_id = $1
ORDER BY sequence ASC
`

func (q *Queries) ListAuditEntriesForRun(ctx context.Context, runID *uuid.UUID) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, listAuditEntriesForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEntry
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.Sequence,
			&i.RunID,
			&i.StageID,
			&i.Ts,
			&i.Category,
			&i.ActorKind,
			&i.ActorSubject,
			&i.Payload,
			&i.PrevHash,
			&i.EntryHash,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalAuditEntries = `-- name: ListGlobalAuditEntries :many
SELECT id, sequence, run_id, stage_id, ts, category, actor_kind, actor_subject, payload, prev_hash, entry_hash, account_id FROM audit_entries
 WHERE run_id IS NULL
 ORDER BY sequence ASC
`

// Used by compliance exports + the verifier to walk the run-less
// partition (all accounts) in append order.
func (q *Queries) ListGlobalAuditEntries(ctx context.Context) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, listGlobalAuditEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEntry
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.Sequence,
			&i.RunID,
			&i.StageID,
			&i.Ts,
			&i.Category,
			&i.ActorKind,
			&i.ActorSubject,
			&i.Payload,
			&i.PrevHash,
			&i.EntryHash,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalAuditEntriesByAccount = `-- name: ListGlobalAuditEntriesByAccount :many
SELECT id, sequence, run_id, stage_id, ts, category, actor_kind, actor_subject, payload, prev_hash, entry_hash, account_id FROM audit_entries
 WHERE run_id IS NULL AND account_id IS NOT DISTINCT FROM $1
 ORDER BY sequence ASC
`

// One account's run-less chain partition in append order (ADR-057 /
// #1828); IS NOT DISTINCT FROM folds the untenanted partition in — a
// NULL $1 selects the account_id IS NULL rows. Feeds the per-account
// compliance-export groups and per-partition verification.
func (q *Queries) ListGlobalAuditEntriesByAccount(ctx context.Context, accountID *uuid.UUID) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, listGlobalAuditEntriesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEntry
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.Sequence,
			&i.RunID,
			&i.StageID,
			&i.Ts,
			&i.Category,
			&i.ActorKind,
			&i.ActorSubject,
			&i.Payload,
			&i.PrevHash,
			&i.EntryHash,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
