// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package auditdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendAuditEntry = `-- name: AppendAuditEntry :one

INSERT INTO audit_entries (
    id, run_id, stage_id, ts, category, actor_kind, actor_subject,
    payload, prev_hash, entry_hash
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, sequence, run_id, stage_id, ts, category, actor_kind, actor_subject, payload, prev_hash, entry_hash
`

type AppendAuditEntryParams struct {
	ID           uuid.UUID          `json:"id"`
	RunID        *uuid.UUID         `json:"run_id"`
	StageID      *uuid.UUID         `json:"stage_id"`
	Ts           pgtype.Timestamptz `json:"ts"`
	Category     string             `json:"category"`
	ActorKind    *string            `json:"actor_kind"`
	ActorSubject *string            `json:"actor_subject"`
	Payload      []byte             `json:"payload"`
	PrevHash     *string            `json:"prev_hash"`
	EntryHash    string             `json:"entry_hash"`
}

// Audit-entry queries consumed by the postgres adapter for the
// audit.Repository interface (E2.1 / #22). Append-only — no
// UpdateAuditEntry or DeleteAuditEntry queries exist or will exist
// in this file. Database-level triggers backstop the same invariant.
func (q *Queries) AppendAuditEntry(ctx context.Context, arg AppendAuditEntryParams) (AuditEntry, error) {
	row := q.db.QueryRow(ctx, appendAuditEntry,
		arg.ID,
		arg.RunID,
		arg.StageID,
		arg.Ts,
		arg.Category,
		arg.ActorKind,
		arg.ActorSubject,
		arg.Payload,
		arg.PrevHash,
		arg.EntryHash,
	)
	var i AuditEntry
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.RunID,
		&i.StageID,
		&i.Ts,
		&i.Category,
		&i.ActorKind,
		&i.ActorSubject,
		&i.Payload,
		&i.PrevHash,
		&i.EntryHash,
	)
	return i, err
}

const getAuditEntry = `-- name: GetAuditEntry :one
SELECT id, sequence, run_id, stage_id, ts, category, actor_kind, actor_subject, payload, prev_hash, entry_hash FROM audit_entries WHERE id = $1
`

func (q *Queries) GetAuditEntry(ctx context.Context, id uuid.UUID) (AuditEntry, error) {
	row := q.db.QueryRow(ctx, getAuditEntry, id)
	var i AuditEntry
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.RunID,
		&i.StageID,
		&i.Ts,
		&i.Category,
		&i.ActorKind,
		&i.ActorSubject,
		&i.Payload,
		&i.PrevHash,
		&i.EntryHash,
	)
	return i, err
}

const getLastAuditEntryForRun = `-- name: GetLastAuditEntryForRun :one
SELECT id, sequence, run_id, stage_id, ts, category, actor_kind, actor_subject, payload, prev_hash, entry_hash FROM audit_entries
WHERE run_id = $1
ORDER BY sequence DESC
LIMIT 1
`

// Used by Append to fetch prev_hash for the next entry in the run.
func (q *Queries) GetLastAuditEntryForRun(ctx context.Context, runID *uuid.UUID) (AuditEntry, error) {
	row := q.db.QueryRow(ctx, getLastAuditEntryForRun, runID)
	var i AuditEntry
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.RunID,
		&i.StageID,
		&i.Ts,
		&i.Category,
		&i.ActorKind,
		&i.ActorSubject,
		&i.Payload,
		&i.PrevHash,
		&i.EntryHash,
	)
	return i, err
}

const getLastGlobalAuditEntry = `-- name: GetLastGlobalAuditEntry :one
SELECT id, sequence, run_id, stage_id, ts, category, actor_kind, actor_subject, payload, prev_hash, entry_hash FROM audit_entries
 WHERE run_id IS NULL
 ORDER BY sequence DESC
 LIMIT 1
`

// Mirror of GetLastAuditEntryForRun for the global chain partition
// (E2.7 / #138). Used by AppendGlobalChained to fetch prev_hash for
// the next non-run event (token issue/revoke, OAuth sign-in, etc.).
func (q *Queries) GetLastGlobalAuditEntry(ctx context.Context) (AuditEntry, error) {
	row := q.db.QueryRow(ctx, getLastGlobalAuditEntry)
	var i AuditEntry
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.RunID,
		&i.StageID,
		&i.Ts,
		&i.Category,
		&i.ActorKind,
		&i.ActorSubject,
		&i.Payload,
		&i.PrevHash,
		&i.EntryHash,
	)
	return i, err
}

const listAuditEntriesByCategory = `-- name: ListAuditEntriesByCategory :many
SELECT id, sequence, run_id, stage_id, ts, category, actor_kind, actor_subject, payload, prev_hash, entry_hash FROM audit_entries
WHERE run_id = $1 AND category = $2
ORDER BY sequence ASC
`

type ListAuditEntriesByCategoryParams struct {
	RunID    *uuid.UUID `json:"run_id"`
	Category string     `json:"category"`
}

func (q *Queries) ListAuditEntriesByCategory(ctx context.Context, arg ListAuditEntriesByCategoryParams) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, listAuditEntriesByCategory, arg.RunID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEntry
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.Sequence,
			&i.RunID,
			&i.StageID,
			&i.Ts,
			&i.Category,
			&i.ActorKind,
			&i.ActorSubject,
			&i.Payload,
			&i.PrevHash,
			&i.EntryHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEntriesForRun = `-- name: ListAuditEntriesForRun :many
SELECT id, sequence, run_id, stage_id, ts, category, actor_kind, actor_subject, payload, prev_hash, entry_hash FROM audit_entries
WHERE run_id = $1
ORDER BY sequence ASC
`

func (q *Queries) ListAuditEntriesForRun(ctx context.Context, runID *uuid.UUID) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, listAuditEntriesForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEntry
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.Sequence,
			&i.RunID,
			&i.StageID,
			&i.Ts,
			&i.Category,
			&i.ActorKind,
			&i.ActorSubject,
			&i.Payload,
			&i.PrevHash,
			&i.EntryHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalAuditEntries = `-- name: ListGlobalAuditEntries :many
SELECT id, sequence, run_id, stage_id, ts, category, actor_kind, actor_subject, payload, prev_hash, entry_hash FROM audit_entries
 WHERE run_id IS NULL
 ORDER BY sequence ASC
`

// Used by compliance exports + the verifier to walk the global
// chain in append order.
func (q *Queries) ListGlobalAuditEntries(ctx context.Context) ([]AuditEntry, error) {
	rows, err := q.db.Query(ctx, listGlobalAuditEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEntry
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.Sequence,
			&i.RunID,
			&i.StageID,
			&i.Ts,
			&i.Category,
			&i.ActorKind,
			&i.ActorSubject,
			&i.Payload,
			&i.PrevHash,
			&i.EntryHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
