// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package rundb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Run struct {
	ID            uuid.UUID          `json:"id"`
	Repo          string             `json:"repo"`
	WorkflowID    string             `json:"workflow_id"`
	WorkflowSha   string             `json:"workflow_sha"`
	TriggerSource string             `json:"trigger_source"`
	TriggerRef    *string            `json:"trigger_ref"`
	State         string             `json:"state"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Stage struct {
	ID              uuid.UUID          `json:"id"`
	RunID           uuid.UUID          `json:"run_id"`
	Sequence        int32              `json:"sequence"`
	StageType       string             `json:"stage_type"`
	ExecutorKind    string             `json:"executor_kind"`
	ExecutorRef     string             `json:"executor_ref"`
	State           string             `json:"state"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	FailureCategory *string            `json:"failure_category"`
	FailureReason   *string            `json:"failure_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
