// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package rundb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRun = `-- name: CreateRun :one

INSERT INTO runs (id, repo, workflow_id, workflow_sha, trigger_source, trigger_ref, state, installation_id, idempotency_key, parent_run_id, required_checks_snapshot, workflow_spec, retry_attempt, max_retries_snapshot, runner_kind, issue_context)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, repo, workflow_id, workflow_sha, trigger_source, trigger_ref, state, created_at, updated_at, installation_id, idempotency_key, parent_run_id, pull_request_url, required_checks_snapshot, workflow_spec, retry_attempt, max_retries_snapshot, runner_kind, issue_context
`

type CreateRunParams struct {
	ID                     uuid.UUID  `json:"id"`
	Repo                   string     `json:"repo"`
	WorkflowID             string     `json:"workflow_id"`
	WorkflowSha            string     `json:"workflow_sha"`
	TriggerSource          string     `json:"trigger_source"`
	TriggerRef             *string    `json:"trigger_ref"`
	State                  string     `json:"state"`
	InstallationID         *int64     `json:"installation_id"`
	IdempotencyKey         *string    `json:"idempotency_key"`
	ParentRunID            *uuid.UUID `json:"parent_run_id"`
	RequiredChecksSnapshot []byte     `json:"required_checks_snapshot"`
	WorkflowSpec           []byte     `json:"workflow_spec"`
	RetryAttempt           int32      `json:"retry_attempt"`
	MaxRetriesSnapshot     int32      `json:"max_retries_snapshot"`
	RunnerKind             string     `json:"runner_kind"`
	IssueContext           []byte     `json:"issue_context"`
}

// Run / stage queries consumed by the postgres adapter for the
// run.Repository interface (E3.3 / #43). sqlc generates typed Go
// into ./db per the config in /backend/sqlc.yaml.
func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.ID,
		arg.Repo,
		arg.WorkflowID,
		arg.WorkflowSha,
		arg.TriggerSource,
		arg.TriggerRef,
		arg.State,
		arg.InstallationID,
		arg.IdempotencyKey,
		arg.ParentRunID,
		arg.RequiredChecksSnapshot,
		arg.WorkflowSpec,
		arg.RetryAttempt,
		arg.MaxRetriesSnapshot,
		arg.RunnerKind,
		arg.IssueContext,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.WorkflowID,
		&i.WorkflowSha,
		&i.TriggerSource,
		&i.TriggerRef,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstallationID,
		&i.IdempotencyKey,
		&i.ParentRunID,
		&i.PullRequestUrl,
		&i.RequiredChecksSnapshot,
		&i.WorkflowSpec,
		&i.RetryAttempt,
		&i.MaxRetriesSnapshot,
		&i.RunnerKind,
		&i.IssueContext,
	)
	return i, err
}

const createStage = `-- name: CreateStage :one
INSERT INTO stages (
    id, run_id, sequence, stage_type, executor_kind, executor_ref, state,
    gate_sla, requires_approval,
    gate_type, gate_approvers
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, run_id, sequence, stage_type, executor_kind, executor_ref, state, started_at, ended_at, failure_category, failure_reason, created_at, updated_at, gate_sla, requires_approval, gate_type, gate_approvers
`

type CreateStageParams struct {
	ID               uuid.UUID `json:"id"`
	RunID            uuid.UUID `json:"run_id"`
	Sequence         int32     `json:"sequence"`
	StageType        string    `json:"stage_type"`
	ExecutorKind     string    `json:"executor_kind"`
	ExecutorRef      string    `json:"executor_ref"`
	State            string    `json:"state"`
	GateSla          *string   `json:"gate_sla"`
	RequiresApproval bool      `json:"requires_approval"`
	GateType         *string   `json:"gate_type"`
	GateApprovers    []byte    `json:"gate_approvers"`
}

func (q *Queries) CreateStage(ctx context.Context, arg CreateStageParams) (Stage, error) {
	row := q.db.QueryRow(ctx, createStage,
		arg.ID,
		arg.RunID,
		arg.Sequence,
		arg.StageType,
		arg.ExecutorKind,
		arg.ExecutorRef,
		arg.State,
		arg.GateSla,
		arg.RequiresApproval,
		arg.GateType,
		arg.GateApprovers,
	)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Sequence,
		&i.StageType,
		&i.ExecutorKind,
		&i.ExecutorRef,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.FailureCategory,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GateSla,
		&i.RequiresApproval,
		&i.GateType,
		&i.GateApprovers,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, repo, workflow_id, workflow_sha, trigger_source, trigger_ref, state, created_at, updated_at, installation_id, idempotency_key, parent_run_id, pull_request_url, required_checks_snapshot, workflow_spec, retry_attempt, max_retries_snapshot, runner_kind, issue_context FROM runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id uuid.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.WorkflowID,
		&i.WorkflowSha,
		&i.TriggerSource,
		&i.TriggerRef,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstallationID,
		&i.IdempotencyKey,
		&i.ParentRunID,
		&i.PullRequestUrl,
		&i.RequiredChecksSnapshot,
		&i.WorkflowSpec,
		&i.RetryAttempt,
		&i.MaxRetriesSnapshot,
		&i.RunnerKind,
		&i.IssueContext,
	)
	return i, err
}

const getRunByIdempotencyKey = `-- name: GetRunByIdempotencyKey :one
SELECT id, repo, workflow_id, workflow_sha, trigger_source, trigger_ref, state, created_at, updated_at, installation_id, idempotency_key, parent_run_id, pull_request_url, required_checks_snapshot, workflow_spec, retry_attempt, max_retries_snapshot, runner_kind, issue_context FROM runs
 WHERE repo = $1
   AND idempotency_key = $2
`

type GetRunByIdempotencyKeyParams struct {
	Repo           string  `json:"repo"`
	IdempotencyKey *string `json:"idempotency_key"`
}

// Used by POST /v0/runs to resolve an Idempotency-Key header to
// a previously-created run. Active scope is (repo, idempotency_key);
// the partial unique index covers this lookup with no full scan.
func (q *Queries) GetRunByIdempotencyKey(ctx context.Context, arg GetRunByIdempotencyKeyParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRunByIdempotencyKey, arg.Repo, arg.IdempotencyKey)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.WorkflowID,
		&i.WorkflowSha,
		&i.TriggerSource,
		&i.TriggerRef,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstallationID,
		&i.IdempotencyKey,
		&i.ParentRunID,
		&i.PullRequestUrl,
		&i.RequiredChecksSnapshot,
		&i.WorkflowSpec,
		&i.RetryAttempt,
		&i.MaxRetriesSnapshot,
		&i.RunnerKind,
		&i.IssueContext,
	)
	return i, err
}

const getStage = `-- name: GetStage :one
SELECT id, run_id, sequence, stage_type, executor_kind, executor_ref, state, started_at, ended_at, failure_category, failure_reason, created_at, updated_at, gate_sla, requires_approval, gate_type, gate_approvers FROM stages WHERE id = $1
`

func (q *Queries) GetStage(ctx context.Context, id uuid.UUID) (Stage, error) {
	row := q.db.QueryRow(ctx, getStage, id)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Sequence,
		&i.StageType,
		&i.ExecutorKind,
		&i.ExecutorRef,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.FailureCategory,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GateSla,
		&i.RequiresApproval,
		&i.GateType,
		&i.GateApprovers,
	)
	return i, err
}

const listRuns = `-- name: ListRuns :many
SELECT id, repo, workflow_id, workflow_sha, trigger_source, trigger_ref, state, created_at, updated_at, installation_id, idempotency_key, parent_run_id, pull_request_url, required_checks_snapshot, workflow_spec, retry_attempt, max_retries_snapshot, runner_kind, issue_context FROM runs
 WHERE ($1::text = '' OR repo = $1)
   AND ($2::text = '' OR workflow_id = $2)
   AND ($3::text = '' OR state = $3)
   AND ($4::text IS NULL OR pull_request_url = $4)
   AND ($5::text IS NULL OR trigger_ref = $5)
   AND ($6::text IS NULL OR runner_kind = $6)
 ORDER BY created_at DESC, id DESC
 LIMIT $8 OFFSET $7
`

type ListRunsParams struct {
	Repo           string  `json:"repo"`
	WorkflowID     string  `json:"workflow_id"`
	State          string  `json:"state"`
	PullRequestUrl *string `json:"pull_request_url"`
	TriggerRef     *string `json:"trigger_ref"`
	RunnerKind     *string `json:"runner_kind"`
	Off            int32   `json:"off"`
	Lim            int32   `json:"lim"`
}

// Empty string / nil in any filter means "no constraint." created_at
// DESC + id DESC tiebreak so paginations are stable across concurrent
// inserts at the same created_at microsecond.
//
// pull_request_url and trigger_ref are nullable filters: pass NULL to
// skip; pass a value to match exactly. They're indexed (partial,
// WHERE NOT NULL) so an equality match on either is cheap. Used by
// the threaded-runs view (#216) to render "every run on this PR."
func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRuns,
		arg.Repo,
		arg.WorkflowID,
		arg.State,
		arg.PullRequestUrl,
		arg.TriggerRef,
		arg.RunnerKind,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Repo,
			&i.WorkflowID,
			&i.WorkflowSha,
			&i.TriggerSource,
			&i.TriggerRef,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InstallationID,
			&i.IdempotencyKey,
			&i.ParentRunID,
			&i.PullRequestUrl,
			&i.RequiredChecksSnapshot,
			&i.WorkflowSpec,
			&i.RetryAttempt,
			&i.MaxRetriesSnapshot,
			&i.RunnerKind,
			&i.IssueContext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagesAwaitingApproval = `-- name: ListStagesAwaitingApproval :many
SELECT id, run_id, sequence, stage_type, executor_kind, executor_ref, state, started_at, ended_at, failure_category, failure_reason, created_at, updated_at, gate_sla, requires_approval, gate_type, gate_approvers FROM stages
 WHERE state = 'awaiting_approval'
   AND gate_sla IS NOT NULL
 ORDER BY updated_at ASC
`

// Used by the SLA ticker to find candidates for timeout. Filters
// to stages in awaiting_approval state with a non-null gate_sla so
// the ticker doesn't pay for SLA parsing on rows where it isn't
// applicable. Ordered by updated_at ASC: the oldest entry is the
// most likely to be past SLA, so the ticker can early-exit if the
// first row hasn't elapsed (when the parsed durations are uniform).
func (q *Queries) ListStagesAwaitingApproval(ctx context.Context) ([]Stage, error) {
	rows, err := q.db.Query(ctx, listStagesAwaitingApproval)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stage
	for rows.Next() {
		var i Stage
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Sequence,
			&i.StageType,
			&i.ExecutorKind,
			&i.ExecutorRef,
			&i.State,
			&i.StartedAt,
			&i.EndedAt,
			&i.FailureCategory,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GateSla,
			&i.RequiresApproval,
			&i.GateType,
			&i.GateApprovers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagesDispatched = `-- name: ListStagesDispatched :many
SELECT id, run_id, sequence, stage_type, executor_kind, executor_ref, state, started_at, ended_at, failure_category, failure_reason, created_at, updated_at, gate_sla, requires_approval, gate_type, gate_approvers FROM stages
 WHERE state = 'dispatched'
 ORDER BY updated_at ASC
`

// Used by the dispatch watchdog (E8.4) to find stages stuck at
// 'dispatched' past a configurable timeout. Ordered by updated_at
// ASC so the oldest stuck stage is processed first; lets the
// watchdog early-exit once it sees one that's still within the
// window.
func (q *Queries) ListStagesDispatched(ctx context.Context) ([]Stage, error) {
	rows, err := q.db.Query(ctx, listStagesDispatched)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stage
	for rows.Next() {
		var i Stage
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Sequence,
			&i.StageType,
			&i.ExecutorKind,
			&i.ExecutorRef,
			&i.State,
			&i.StartedAt,
			&i.EndedAt,
			&i.FailureCategory,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GateSla,
			&i.RequiresApproval,
			&i.GateType,
			&i.GateApprovers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagesForRun = `-- name: ListStagesForRun :many
SELECT id, run_id, sequence, stage_type, executor_kind, executor_ref, state, started_at, ended_at, failure_category, failure_reason, created_at, updated_at, gate_sla, requires_approval, gate_type, gate_approvers FROM stages WHERE run_id = $1 ORDER BY sequence ASC
`

func (q *Queries) ListStagesForRun(ctx context.Context, runID uuid.UUID) ([]Stage, error) {
	rows, err := q.db.Query(ctx, listStagesForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stage
	for rows.Next() {
		var i Stage
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Sequence,
			&i.StageType,
			&i.ExecutorKind,
			&i.ExecutorRef,
			&i.State,
			&i.StartedAt,
			&i.EndedAt,
			&i.FailureCategory,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GateSla,
			&i.RequiresApproval,
			&i.GateType,
			&i.GateApprovers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRunForUpdate = `-- name: LockRunForUpdate :one
SELECT id, repo, workflow_id, workflow_sha, trigger_source, trigger_ref, state, created_at, updated_at, installation_id, idempotency_key, parent_run_id, pull_request_url, required_checks_snapshot, workflow_spec, retry_attempt, max_retries_snapshot, runner_kind, issue_context FROM runs WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockRunForUpdate(ctx context.Context, id uuid.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, lockRunForUpdate, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.WorkflowID,
		&i.WorkflowSha,
		&i.TriggerSource,
		&i.TriggerRef,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstallationID,
		&i.IdempotencyKey,
		&i.ParentRunID,
		&i.PullRequestUrl,
		&i.RequiredChecksSnapshot,
		&i.WorkflowSpec,
		&i.RetryAttempt,
		&i.MaxRetriesSnapshot,
		&i.RunnerKind,
		&i.IssueContext,
	)
	return i, err
}

const lockStageForUpdate = `-- name: LockStageForUpdate :one
SELECT id, run_id, sequence, stage_type, executor_kind, executor_ref, state, started_at, ended_at, failure_category, failure_reason, created_at, updated_at, gate_sla, requires_approval, gate_type, gate_approvers FROM stages WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockStageForUpdate(ctx context.Context, id uuid.UUID) (Stage, error) {
	row := q.db.QueryRow(ctx, lockStageForUpdate, id)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Sequence,
		&i.StageType,
		&i.ExecutorKind,
		&i.ExecutorRef,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.FailureCategory,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GateSla,
		&i.RequiresApproval,
		&i.GateType,
		&i.GateApprovers,
	)
	return i, err
}

const setRunPullRequestURL = `-- name: SetRunPullRequestURL :one
UPDATE runs
   SET pull_request_url = $2
 WHERE id = $1
RETURNING id, repo, workflow_id, workflow_sha, trigger_source, trigger_ref, state, created_at, updated_at, installation_id, idempotency_key, parent_run_id, pull_request_url, required_checks_snapshot, workflow_spec, retry_attempt, max_retries_snapshot, runner_kind, issue_context
`

type SetRunPullRequestURLParams struct {
	ID             uuid.UUID `json:"id"`
	PullRequestUrl *string   `json:"pull_request_url"`
}

// Backfills the implement-stage PR URL onto the run row when the
// pull_request artifact lands (#216). Idempotent: a re-upload with
// the same URL is a no-op the trigger keeps as a no-op against
// updated_at (assignment of identical value).
func (q *Queries) SetRunPullRequestURL(ctx context.Context, arg SetRunPullRequestURLParams) (Run, error) {
	row := q.db.QueryRow(ctx, setRunPullRequestURL, arg.ID, arg.PullRequestUrl)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.WorkflowID,
		&i.WorkflowSha,
		&i.TriggerSource,
		&i.TriggerRef,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstallationID,
		&i.IdempotencyKey,
		&i.ParentRunID,
		&i.PullRequestUrl,
		&i.RequiredChecksSnapshot,
		&i.WorkflowSpec,
		&i.RetryAttempt,
		&i.MaxRetriesSnapshot,
		&i.RunnerKind,
		&i.IssueContext,
	)
	return i, err
}

const updateRunState = `-- name: UpdateRunState :one
UPDATE runs
   SET state = $2
 WHERE id = $1
RETURNING id, repo, workflow_id, workflow_sha, trigger_source, trigger_ref, state, created_at, updated_at, installation_id, idempotency_key, parent_run_id, pull_request_url, required_checks_snapshot, workflow_spec, retry_attempt, max_retries_snapshot, runner_kind, issue_context
`

type UpdateRunStateParams struct {
	ID    uuid.UUID `json:"id"`
	State string    `json:"state"`
}

func (q *Queries) UpdateRunState(ctx context.Context, arg UpdateRunStateParams) (Run, error) {
	row := q.db.QueryRow(ctx, updateRunState, arg.ID, arg.State)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.WorkflowID,
		&i.WorkflowSha,
		&i.TriggerSource,
		&i.TriggerRef,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstallationID,
		&i.IdempotencyKey,
		&i.ParentRunID,
		&i.PullRequestUrl,
		&i.RequiredChecksSnapshot,
		&i.WorkflowSpec,
		&i.RetryAttempt,
		&i.MaxRetriesSnapshot,
		&i.RunnerKind,
		&i.IssueContext,
	)
	return i, err
}

const updateStageState = `-- name: UpdateStageState :one
UPDATE stages
   SET state            = $2,
       started_at       = COALESCE(started_at, $3),
       ended_at         = $4,
       failure_category = $5,
       failure_reason   = $6
 WHERE id = $1
RETURNING id, run_id, sequence, stage_type, executor_kind, executor_ref, state, started_at, ended_at, failure_category, failure_reason, created_at, updated_at, gate_sla, requires_approval, gate_type, gate_approvers
`

type UpdateStageStateParams struct {
	ID              uuid.UUID          `json:"id"`
	State           string             `json:"state"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	FailureCategory *string            `json:"failure_category"`
	FailureReason   *string            `json:"failure_reason"`
}

func (q *Queries) UpdateStageState(ctx context.Context, arg UpdateStageStateParams) (Stage, error) {
	row := q.db.QueryRow(ctx, updateStageState,
		arg.ID,
		arg.State,
		arg.StartedAt,
		arg.EndedAt,
		arg.FailureCategory,
		arg.FailureReason,
	)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Sequence,
		&i.StageType,
		&i.ExecutorKind,
		&i.ExecutorRef,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.FailureCategory,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GateSla,
		&i.RequiresApproval,
		&i.GateType,
		&i.GateApprovers,
	)
	return i, err
}
