// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package concerndb

import (
	"context"

	"github.com/google/uuid"
)

const getReviewConcernsByIDs = `-- name: GetReviewConcernsByIDs :many
SELECT id, run_id, stage_id, stage_kind, origin_review_sequence, reviewer_model, severity, category, note, state, state_reason, created_at, updated_at, suggested_patch FROM review_concerns
 WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetReviewConcernsByIDs(ctx context.Context, ids []uuid.UUID) ([]ReviewConcern, error) {
	rows, err := q.db.Query(ctx, getReviewConcernsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewConcern
	for rows.Next() {
		var i ReviewConcern
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StageID,
			&i.StageKind,
			&i.OriginReviewSequence,
			&i.ReviewerModel,
			&i.Severity,
			&i.Category,
			&i.Note,
			&i.State,
			&i.StateReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SuggestedPatch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertReviewConcern = `-- name: InsertReviewConcern :one

INSERT INTO review_concerns (
    id, run_id, stage_id, stage_kind, origin_review_sequence,
    reviewer_model, severity, category, note, suggested_patch
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, run_id, stage_id, stage_kind, origin_review_sequence, reviewer_model, severity, category, note, state, state_reason, created_at, updated_at, suggested_patch
`

type InsertReviewConcernParams struct {
	ID                   uuid.UUID `json:"id"`
	RunID                uuid.UUID `json:"run_id"`
	StageID              uuid.UUID `json:"stage_id"`
	StageKind            string    `json:"stage_kind"`
	OriginReviewSequence int64     `json:"origin_review_sequence"`
	ReviewerModel        *string   `json:"reviewer_model"`
	Severity             string    `json:"severity"`
	Category             string    `json:"category"`
	Note                 string    `json:"note"`
	SuggestedPatch       string    `json:"suggested_patch"`
}

// Review-concern queries (E22.X / #964). sqlc generates typed Go
// into ./db per backend/sqlc.yaml.
func (q *Queries) InsertReviewConcern(ctx context.Context, arg InsertReviewConcernParams) (ReviewConcern, error) {
	row := q.db.QueryRow(ctx, insertReviewConcern,
		arg.ID,
		arg.RunID,
		arg.StageID,
		arg.StageKind,
		arg.OriginReviewSequence,
		arg.ReviewerModel,
		arg.Severity,
		arg.Category,
		arg.Note,
		arg.SuggestedPatch,
	)
	var i ReviewConcern
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StageID,
		&i.StageKind,
		&i.OriginReviewSequence,
		&i.ReviewerModel,
		&i.Severity,
		&i.Category,
		&i.Note,
		&i.State,
		&i.StateReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuggestedPatch,
	)
	return i, err
}

const listOpenReviewConcernsByRun = `-- name: ListOpenReviewConcernsByRun :many
SELECT id, run_id, stage_id, stage_kind, origin_review_sequence, reviewer_model, severity, category, note, state, state_reason, created_at, updated_at, suggested_patch FROM review_concerns
 WHERE run_id = $1
   AND state IN ('raised', 'addressed_pending', 'reopened')
 ORDER BY origin_review_sequence ASC, created_at ASC, id ASC
`

// Open states only (raised, addressed_pending, reopened). The state set
// is duplicated from the Go state machine's IsOpen — keep in sync.
func (q *Queries) ListOpenReviewConcernsByRun(ctx context.Context, runID uuid.UUID) ([]ReviewConcern, error) {
	rows, err := q.db.Query(ctx, listOpenReviewConcernsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewConcern
	for rows.Next() {
		var i ReviewConcern
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StageID,
			&i.StageKind,
			&i.OriginReviewSequence,
			&i.ReviewerModel,
			&i.Severity,
			&i.Category,
			&i.Note,
			&i.State,
			&i.StateReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SuggestedPatch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewConcernsByRun = `-- name: ListReviewConcernsByRun :many
SELECT id, run_id, stage_id, stage_kind, origin_review_sequence, reviewer_model, severity, category, note, state, state_reason, created_at, updated_at, suggested_patch FROM review_concerns
 WHERE run_id = $1
 ORDER BY origin_review_sequence ASC, created_at ASC, id ASC
`

// Origin-sequence order so concerns read oldest review first.
func (q *Queries) ListReviewConcernsByRun(ctx context.Context, runID uuid.UUID) ([]ReviewConcern, error) {
	rows, err := q.db.Query(ctx, listReviewConcernsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewConcern
	for rows.Next() {
		var i ReviewConcern
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StageID,
			&i.StageKind,
			&i.OriginReviewSequence,
			&i.ReviewerModel,
			&i.Severity,
			&i.Category,
			&i.Note,
			&i.State,
			&i.StateReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SuggestedPatch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReviewConcernState = `-- name: UpdateReviewConcernState :one
UPDATE review_concerns
   SET state = $2,
       state_reason = $3,
       updated_at = now()
 WHERE id = $1
   AND state = $4
RETURNING id, run_id, stage_id, stage_kind, origin_review_sequence, reviewer_model, severity, category, note, state, state_reason, created_at, updated_at, suggested_patch
`

type UpdateReviewConcernStateParams struct {
	ID          uuid.UUID `json:"id"`
	State       string    `json:"state"`
	StateReason string    `json:"state_reason"`
	FromState   string    `json:"from_state"`
}

// from-state guard in the WHERE clause makes the transition atomic
// under concurrent writers: a racing update matches zero rows and the
// caller re-reads to re-validate against the state machine.
func (q *Queries) UpdateReviewConcernState(ctx context.Context, arg UpdateReviewConcernStateParams) (ReviewConcern, error) {
	row := q.db.QueryRow(ctx, updateReviewConcernState,
		arg.ID,
		arg.State,
		arg.StateReason,
		arg.FromState,
	)
	var i ReviewConcern
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StageID,
		&i.StageKind,
		&i.OriginReviewSequence,
		&i.ReviewerModel,
		&i.Severity,
		&i.Category,
		&i.Note,
		&i.State,
		&i.StateReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuggestedPatch,
	)
	return i, err
}
