// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package authdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id, user_id, token_hash,
    sliding_expires_at, absolute_expires_at
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, issued_at, last_used_at, sliding_expires_at, absolute_expires_at, revoked_at
`

type CreateSessionParams struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	TokenHash         string             `json:"token_hash"`
	SlidingExpiresAt  pgtype.Timestamptz `json:"sliding_expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.SlidingExpiresAt,
		arg.AbsoluteExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.LastUsedAt,
		&i.SlidingExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const evictExpiredSessions = `-- name: EvictExpiredSessions :execrows
DELETE FROM sessions
 WHERE absolute_expires_at < $1
`

// Used by the eviction ticker. The partial index on
// absolute_expires_at WHERE revoked_at IS NULL keeps this an
// index range scan.
func (q *Queries) EvictExpiredSessions(ctx context.Context, absoluteExpiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, evictExpiredSessions, absoluteExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionByHash = `-- name: GetSessionByHash :one
SELECT id, user_id, token_hash, issued_at, last_used_at, sliding_expires_at, absolute_expires_at, revoked_at FROM sessions
 WHERE token_hash = $1
   AND revoked_at IS NULL
   AND absolute_expires_at > now()
`

// Active-only: revoked or absolute-expired sessions never
// authenticate. Sliding-expiry is checked at the application
// layer (the row is read first, then validated against now()).
func (q *Queries) GetSessionByHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.LastUsedAt,
		&i.SlidingExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, github_user_id, github_login, name, email, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubLogin,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGitHubID = `-- name: GetUserByGitHubID :one
SELECT id, github_user_id, github_login, name, email, created_at, updated_at FROM users WHERE github_user_id = $1
`

func (q *Queries) GetUserByGitHubID(ctx context.Context, githubUserID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGitHubID, githubUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubLogin,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeSessionByID = `-- name: RevokeSessionByID :exec
UPDATE sessions
   SET revoked_at = COALESCE(revoked_at, $2)
 WHERE id = $1
`

type RevokeSessionByIDParams struct {
	ID        uuid.UUID          `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

// Idempotent: a second call is a no-op (COALESCE).
func (q *Queries) RevokeSessionByID(ctx context.Context, arg RevokeSessionByIDParams) error {
	_, err := q.db.Exec(ctx, revokeSessionByID, arg.ID, arg.RevokedAt)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
   SET last_used_at       = $2,
       sliding_expires_at = $3
 WHERE id = $1
`

type TouchSessionParams struct {
	ID               uuid.UUID          `json:"id"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	SlidingExpiresAt pgtype.Timestamptz `json:"sliding_expires_at"`
}

// Slide the sliding-expiry forward on every authenticated request.
// The absolute_expires_at is fixed at issue time; this only moves
// the sliding window.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.LastUsedAt, arg.SlidingExpiresAt)
	return err
}

const upsertUser = `-- name: UpsertUser :one

INSERT INTO users (id, github_user_id, github_login, name, email)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (github_user_id) DO UPDATE
   SET github_login = EXCLUDED.github_login,
       name         = EXCLUDED.name,
       email        = EXCLUDED.email
RETURNING id, github_user_id, github_login, name, email, created_at, updated_at
`

type UpsertUserParams struct {
	ID           uuid.UUID `json:"id"`
	GithubUserID int64     `json:"github_user_id"`
	GithubLogin  string    `json:"github_login"`
	Name         string    `json:"name"`
	Email        *string   `json:"email"`
}

// Auth (users + sessions) queries (E4.2 / #49). sqlc generates
// typed Go into ./db per backend/sqlc.yaml.
// Upsert keyed on github_user_id (stable across login renames).
// Refreshes login + name + email on every sign-in.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ID,
		arg.GithubUserID,
		arg.GithubLogin,
		arg.Name,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubLogin,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
