// Package bridge generates the agent-instruction files that route work in a
// repository through the Fishhawk loop.
//
// It writes two files under a caller-supplied root directory:
//
//   - AGENTS.md — the canonical, cross-agent instruction file. Fishhawk owns a
//     marker-delimited managed block inside it (BeginMarker … EndMarker);
//     everything outside the markers is user content and is never clobbered.
//   - CLAUDE.md — a bridge file that imports AGENTS.md via an "@AGENTS.md"
//     line. Claude Code reads only CLAUDE.md / CLAUDE.local.md and does not
//     read AGENTS.md natively (ADR-048 / #1500), so the import is required for
//     Claude Code to pick up the canonical instructions.
//
// Both operations are idempotent. An existing AGENTS.md has only its managed
// block inserted or replaced; an existing CLAUDE.md gains the import line only
// if it is absent; and a file is rewritten only when its content actually
// changes, so re-running EnsureAgentDocs on an already-current tree yields a
// clean git diff.
//
// This is a pure library: it operates on the root directory the caller hands
// it and performs no repo-root detection of its own. The walk-up that finds a
// repository root is the caller's responsibility (E29.3 `fishhawk init`,
// E29.7 App-PR).
//
// The package is mirrored byte-for-byte into backend/internal/bridge and
// cli/internal/bridge because the backend and CLI are separate Go modules with
// no shared module between them (the E29.1 / #1509 module-wall precedent). Keep
// the two copies identical.
package bridge

import (
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// Marker constants delimit the Fishhawk-managed region inside AGENTS.md. The
// text between (and including) these two lines is regenerated on every run;
// text outside them is preserved verbatim.
const (
	BeginMarker = "<!-- fishhawk:begin -->"
	EndMarker   = "<!-- fishhawk:end -->"
)

// ImportLine is the line CLAUDE.md carries to pull in the canonical AGENTS.md.
// Claude Code resolves an "@path" line as a file import.
const ImportLine = "@AGENTS.md"

// FileStatus reports what EnsureAgentDocs did to a single file.
type FileStatus string

const (
	// StatusCreated means the file did not exist and was written.
	StatusCreated FileStatus = "created"
	// StatusUpdated means the file existed and its content changed.
	StatusUpdated FileStatus = "updated"
	// StatusUnchanged means the file was already current and was not rewritten.
	StatusUnchanged FileStatus = "unchanged"
)

// Result reports the per-file outcome of EnsureAgentDocs so a caller (E29.3 /
// E29.7) can decide whether a change — and therefore a PR — is warranted.
type Result struct {
	AgentsMD FileStatus
	ClaudeMD FileStatus
}

// Changed reports whether EnsureAgentDocs modified either file.
func (r Result) Changed() bool {
	return r.AgentsMD != StatusUnchanged || r.ClaudeMD != StatusUnchanged
}

// ManagedBlock returns the marker-delimited Fishhawk routing instructions. The
// markers are on their own lines and the block ends with a trailing newline so
// it composes cleanly with surrounding content.
func ManagedBlock() string {
	return BeginMarker + "\n" +
		managedBody +
		EndMarker + "\n"
}

// managedBody is the instruction text carried between the markers. Restrained,
// technical voice per BRAND_FOUNDATIONS §5 — state the routing contract, no
// banned words.
const managedBody = `## Fishhawk loop

Changes in this repository are made through Fishhawk. A run drives a change
through gated stages — plan, implement, review — with a human deciding at each
gate.

Do not commit directly to a branch or open a pull request by hand. Start a run
for the issue you are working, let the plan stage propose the change, and edit
the working tree only when a stage tells you to. Fishhawk records the commit,
pushes the branch, and opens the pull request.

This block is generated by Fishhawk. Edit the text outside the markers, not
inside them — the managed region is regenerated on the next run.
`

// mergeManagedBlock inserts or replaces the Fishhawk managed block in the
// AGENTS.md content `existing`, preserving all text outside the markers. It
// returns the merged content and whether it differs from the input.
//
// Behavior:
//   - Both markers present: the region from BeginMarker through EndMarker
//     (inclusive) is replaced with the current ManagedBlock().
//   - No markers: the block is appended after the existing content, separated
//     by a single blank line.
//   - Empty/whitespace-only input: the result is just the block.
func mergeManagedBlock(existing string) (result string, changed bool) {
	block := ManagedBlock()

	if strings.TrimSpace(existing) == "" {
		result = block
		return result, result != existing
	}

	begin := strings.Index(existing, BeginMarker)
	end := strings.Index(existing, EndMarker)
	if begin != -1 && end != -1 && end > begin {
		// Replace the inclusive [begin, end+len(EndMarker)) region. The
		// replacement block already ends in a newline; drop any single newline
		// immediately following the old EndMarker so we don't accumulate blank
		// lines across runs.
		after := existing[end+len(EndMarker):]
		after = strings.TrimPrefix(after, "\n")
		result = existing[:begin] + block + after
		return result, result != existing
	}

	// No managed block yet: append after the existing content with one blank
	// line of separation.
	prefix := strings.TrimRight(existing, "\n")
	result = prefix + "\n\n" + block
	return result, result != existing
}

// ensureClaudeImport ensures the CLAUDE.md content `existing` imports AGENTS.md.
// It returns the updated content and whether it differs from the input.
//
// Behavior:
//   - Any line already equal (trimmed) to ImportLine: unchanged.
//   - Empty/whitespace-only input: a minimal CLAUDE.md (a short comment line
//     plus the import line) is produced.
//   - Otherwise: the import line is appended on its own trailing line.
func ensureClaudeImport(existing string) (result string, changed bool) {
	for _, line := range strings.Split(existing, "\n") {
		if strings.TrimSpace(line) == ImportLine {
			return existing, false
		}
	}

	if strings.TrimSpace(existing) == "" {
		result = "# CLAUDE.md\n\n" + ImportLine + "\n"
		return result, result != existing
	}

	prefix := strings.TrimRight(existing, "\n")
	result = prefix + "\n" + ImportLine + "\n"
	return result, result != existing
}

// EnsureAgentDocs writes AGENTS.md and CLAUDE.md under rootDir, applying the
// idempotent merge helpers. A file is written (mode 0644) only when its content
// changes, so an already-current tree is left byte-for-byte untouched.
func EnsureAgentDocs(rootDir string) (Result, error) {
	var res Result

	agentsStatus, err := ensureFile(filepath.Join(rootDir, "AGENTS.md"), mergeManagedBlock)
	if err != nil {
		return res, err
	}
	res.AgentsMD = agentsStatus

	claudeStatus, err := ensureFile(filepath.Join(rootDir, "CLAUDE.md"), ensureClaudeImport)
	if err != nil {
		return res, err
	}
	res.ClaudeMD = claudeStatus

	return res, nil
}

// ensureFile reads path (a missing file reads as empty content), applies merge,
// and writes back only when merge reports a change. It returns the resulting
// FileStatus.
func ensureFile(path string, merge func(string) (string, bool)) (FileStatus, error) {
	existed := true
	data, err := os.ReadFile(path)
	if err != nil {
		if !errors.Is(err, fs.ErrNotExist) {
			return "", err
		}
		existed = false
		data = nil
	}

	result, changed := merge(string(data))
	if !changed {
		return StatusUnchanged, nil
	}

	if err := os.WriteFile(path, []byte(result), 0o644); err != nil {
		return "", err
	}
	if existed {
		return StatusUpdated, nil
	}
	return StatusCreated, nil
}
