// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package refinementdb

import (
	"context"

	"github.com/google/uuid"
)

const createRefinementDecision = `-- name: CreateRefinementDecision :one
INSERT INTO refinement_decisions (id, session_id, draft_id, decision, reason, draft_content_hash, decided_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, session_id, draft_id, decision, reason, draft_content_hash, decided_by, created_at
`

type CreateRefinementDecisionParams struct {
	ID               uuid.UUID `json:"id"`
	SessionID        uuid.UUID `json:"session_id"`
	DraftID          uuid.UUID `json:"draft_id"`
	Decision         string    `json:"decision"`
	Reason           string    `json:"reason"`
	DraftContentHash string    `json:"draft_content_hash"`
	DecidedBy        *string   `json:"decided_by"`
}

func (q *Queries) CreateRefinementDecision(ctx context.Context, arg CreateRefinementDecisionParams) (RefinementDecision, error) {
	row := q.db.QueryRow(ctx, createRefinementDecision,
		arg.ID,
		arg.SessionID,
		arg.DraftID,
		arg.Decision,
		arg.Reason,
		arg.DraftContentHash,
		arg.DecidedBy,
	)
	var i RefinementDecision
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DraftID,
		&i.Decision,
		&i.Reason,
		&i.DraftContentHash,
		&i.DecidedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createRefinementDraft = `-- name: CreateRefinementDraft :one

INSERT INTO refinement_drafts (id, session_id, brief, draft, model, origin)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, session_id, brief, draft, model, created_at, origin
`

type CreateRefinementDraftParams struct {
	ID        uuid.UUID `json:"id"`
	SessionID uuid.UUID `json:"session_id"`
	Brief     string    `json:"brief"`
	Draft     []byte    `json:"draft"`
	Model     *string   `json:"model"`
	Origin    string    `json:"origin"`
}

// Refinement queries consumed by the postgres adapter for the
// refinement.Repository interface (E34.1 / #1592, E34.2 / #1593). A draft is
// keyed by its refinement session id; nothing here files a provider work item.
// A decision is an append-only approve/reject verdict pinning one draft
// revision + its content hash (E34.2's gate record).
func (q *Queries) CreateRefinementDraft(ctx context.Context, arg CreateRefinementDraftParams) (RefinementDraft, error) {
	row := q.db.QueryRow(ctx, createRefinementDraft,
		arg.ID,
		arg.SessionID,
		arg.Brief,
		arg.Draft,
		arg.Model,
		arg.Origin,
	)
	var i RefinementDraft
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Brief,
		&i.Draft,
		&i.Model,
		&i.CreatedAt,
		&i.Origin,
	)
	return i, err
}

const getRefinementDraft = `-- name: GetRefinementDraft :one
SELECT id, session_id, brief, draft, model, created_at, origin FROM refinement_drafts WHERE id = $1
`

func (q *Queries) GetRefinementDraft(ctx context.Context, id uuid.UUID) (RefinementDraft, error) {
	row := q.db.QueryRow(ctx, getRefinementDraft, id)
	var i RefinementDraft
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Brief,
		&i.Draft,
		&i.Model,
		&i.CreatedAt,
		&i.Origin,
	)
	return i, err
}

const listRefinementDecisionsForSession = `-- name: ListRefinementDecisionsForSession :many
SELECT id, session_id, draft_id, decision, reason, draft_content_hash, decided_by, created_at FROM refinement_decisions
WHERE session_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListRefinementDecisionsForSession(ctx context.Context, sessionID uuid.UUID) ([]RefinementDecision, error) {
	rows, err := q.db.Query(ctx, listRefinementDecisionsForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefinementDecision
	for rows.Next() {
		var i RefinementDecision
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.DraftID,
			&i.Decision,
			&i.Reason,
			&i.DraftContentHash,
			&i.DecidedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefinementDraftsForSession = `-- name: ListRefinementDraftsForSession :many
SELECT id, session_id, brief, draft, model, created_at, origin FROM refinement_drafts
WHERE session_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListRefinementDraftsForSession(ctx context.Context, sessionID uuid.UUID) ([]RefinementDraft, error) {
	rows, err := q.db.Query(ctx, listRefinementDraftsForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefinementDraft
	for rows.Next() {
		var i RefinementDraft
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Brief,
			&i.Draft,
			&i.Model,
			&i.CreatedAt,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
