// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package refinementdb

import (
	"context"

	"github.com/google/uuid"
)

const createRefinementDraft = `-- name: CreateRefinementDraft :one

INSERT INTO refinement_drafts (id, session_id, brief, draft, model)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, session_id, brief, draft, model, created_at
`

type CreateRefinementDraftParams struct {
	ID        uuid.UUID `json:"id"`
	SessionID uuid.UUID `json:"session_id"`
	Brief     string    `json:"brief"`
	Draft     []byte    `json:"draft"`
	Model     *string   `json:"model"`
}

// Refinement-draft queries consumed by the postgres adapter for the
// refinement.Repository interface (E34.1 / #1592). A draft is keyed by its
// refinement session id; nothing here files a provider work item.
func (q *Queries) CreateRefinementDraft(ctx context.Context, arg CreateRefinementDraftParams) (RefinementDraft, error) {
	row := q.db.QueryRow(ctx, createRefinementDraft,
		arg.ID,
		arg.SessionID,
		arg.Brief,
		arg.Draft,
		arg.Model,
	)
	var i RefinementDraft
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Brief,
		&i.Draft,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const getRefinementDraft = `-- name: GetRefinementDraft :one
SELECT id, session_id, brief, draft, model, created_at FROM refinement_drafts WHERE id = $1
`

func (q *Queries) GetRefinementDraft(ctx context.Context, id uuid.UUID) (RefinementDraft, error) {
	row := q.db.QueryRow(ctx, getRefinementDraft, id)
	var i RefinementDraft
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Brief,
		&i.Draft,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const listRefinementDraftsForSession = `-- name: ListRefinementDraftsForSession :many
SELECT id, session_id, brief, draft, model, created_at FROM refinement_drafts
WHERE session_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListRefinementDraftsForSession(ctx context.Context, sessionID uuid.UUID) ([]RefinementDraft, error) {
	rows, err := q.db.Query(ctx, listRefinementDraftsForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefinementDraft
	for rows.Next() {
		var i RefinementDraft
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Brief,
			&i.Draft,
			&i.Model,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
