// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package apitokendb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID         uuid.UUID          `json:"id"`
	Subject    string             `json:"subject"`
	TokenHash  string             `json:"token_hash"`
	Scopes     []string           `json:"scopes"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type Approval struct {
	ID              uuid.UUID          `json:"id"`
	StageID         uuid.UUID          `json:"stage_id"`
	ApproverSubject string             `json:"approver_subject"`
	Decision        string             `json:"decision"`
	Comment         *string            `json:"comment"`
	Surface         string             `json:"surface"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
}

type Artifact struct {
	ID            uuid.UUID          `json:"id"`
	StageID       uuid.UUID          `json:"stage_id"`
	Kind          string             `json:"kind"`
	SchemaVersion *string            `json:"schema_version"`
	Content       []byte             `json:"content"`
	ContentHash   string             `json:"content_hash"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AuditEntry struct {
	ID           uuid.UUID          `json:"id"`
	Sequence     int64              `json:"sequence"`
	RunID        *uuid.UUID         `json:"run_id"`
	StageID      *uuid.UUID         `json:"stage_id"`
	Ts           pgtype.Timestamptz `json:"ts"`
	Category     string             `json:"category"`
	ActorKind    *string            `json:"actor_kind"`
	ActorSubject *string            `json:"actor_subject"`
	Payload      []byte             `json:"payload"`
	PrevHash     *string            `json:"prev_hash"`
	EntryHash    string             `json:"entry_hash"`
}

type Run struct {
	ID             uuid.UUID          `json:"id"`
	Repo           string             `json:"repo"`
	WorkflowID     string             `json:"workflow_id"`
	WorkflowSha    string             `json:"workflow_sha"`
	TriggerSource  string             `json:"trigger_source"`
	TriggerRef     *string            `json:"trigger_ref"`
	State          string             `json:"state"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	InstallationID *int64             `json:"installation_id"`
	IdempotencyKey *string            `json:"idempotency_key"`
}

type Session struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	TokenHash         string             `json:"token_hash"`
	IssuedAt          pgtype.Timestamptz `json:"issued_at"`
	LastUsedAt        pgtype.Timestamptz `json:"last_used_at"`
	SlidingExpiresAt  pgtype.Timestamptz `json:"sliding_expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
}

type SigningKey struct {
	RunID     uuid.UUID          `json:"run_id"`
	PublicKey []byte             `json:"public_key"`
	IssuedAt  pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	ID        uuid.UUID          `json:"id"`
}

type Stage struct {
	ID               uuid.UUID          `json:"id"`
	RunID            uuid.UUID          `json:"run_id"`
	Sequence         int32              `json:"sequence"`
	StageType        string             `json:"stage_type"`
	ExecutorKind     string             `json:"executor_kind"`
	ExecutorRef      string             `json:"executor_ref"`
	State            string             `json:"state"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
	FailureCategory  *string            `json:"failure_category"`
	FailureReason    *string            `json:"failure_reason"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	GateSla          *string            `json:"gate_sla"`
	RequiresApproval bool               `json:"requires_approval"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	GithubUserID int64              `json:"github_user_id"`
	GithubLogin  string             `json:"github_login"`
	Name         string             `json:"name"`
	Email        *string            `json:"email"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type WebhookDelivery struct {
	DeliveryID string             `json:"delivery_id"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
}
