// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package apitokendb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createToken = `-- name: CreateToken :one

INSERT INTO api_tokens (id, subject, token_hash, scopes)
VALUES ($1, $2, $3, $4)
RETURNING id, subject, token_hash, scopes, last_used_at, created_at, revoked_at
`

type CreateTokenParams struct {
	ID        uuid.UUID `json:"id"`
	Subject   string    `json:"subject"`
	TokenHash string    `json:"token_hash"`
	Scopes    []string  `json:"scopes"`
}

// API token queries (E4.5 / #51). sqlc generates typed Go into
// ./db per backend/sqlc.yaml.
func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.ID,
		arg.Subject,
		arg.TokenHash,
		arg.Scopes,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.TokenHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT id, subject, token_hash, scopes, last_used_at, created_at, revoked_at FROM api_tokens
 WHERE token_hash = $1
   AND revoked_at IS NULL
`

// Active-only: revoked tokens never authenticate. Used on every
// bearer-auth request, so the partial index on (token_hash) WHERE
// revoked_at IS NULL is the hot path.
func (q *Queries) GetTokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getTokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.TokenHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getTokenByID = `-- name: GetTokenByID :one
SELECT id, subject, token_hash, scopes, last_used_at, created_at, revoked_at FROM api_tokens
 WHERE id = $1
`

// Returns the row regardless of revocation state — callers (the
// DELETE handler) need to see revoked rows to return idempotent
// 204s.
func (q *Queries) GetTokenByID(ctx context.Context, id uuid.UUID) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getTokenByID, id)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.TokenHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listTokensForSubject = `-- name: ListTokensForSubject :many
SELECT id, subject, token_hash, scopes, last_used_at, created_at, revoked_at FROM api_tokens
 WHERE subject = $1
   AND revoked_at IS NULL
 ORDER BY created_at DESC
`

// Active tokens for a user, newest first. Revoked rows are
// filtered out by the partial index.
func (q *Queries) ListTokensForSubject(ctx context.Context, subject string) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listTokensForSubject, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiToken
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.TokenHash,
			&i.Scopes,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeToken = `-- name: RevokeToken :one
UPDATE api_tokens
   SET revoked_at = COALESCE(revoked_at, $2)
 WHERE id = $1
RETURNING id, subject, token_hash, scopes, last_used_at, created_at, revoked_at
`

type RevokeTokenParams struct {
	ID        uuid.UUID          `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

// Idempotent: if revoked_at is already set, return the existing
// row unchanged. The handler checks ownership before calling.
func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, revokeToken, arg.ID, arg.RevokedAt)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.TokenHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const touchTokenLastUsed = `-- name: TouchTokenLastUsed :exec
UPDATE api_tokens
   SET last_used_at = $2
 WHERE id = $1
`

type TouchTokenLastUsedParams struct {
	ID         uuid.UUID          `json:"id"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

// Stamp last_used_at on a successful auth. Best-effort; the auth
// decision doesn't depend on this succeeding.
func (q *Queries) TouchTokenLastUsed(ctx context.Context, arg TouchTokenLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchTokenLastUsed, arg.ID, arg.LastUsedAt)
	return err
}
