// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package webhookdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const evictOldDeliveries = `-- name: EvictOldDeliveries :execrows
DELETE FROM webhook_deliveries
 WHERE received_at < $1
`

// Returns the number of rows deleted so the eviction ticker can
// log a counter. The index on received_at makes this an index
// range scan rather than a full table sweep.
func (q *Queries) EvictOldDeliveries(ctx context.Context, receivedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, evictOldDeliveries, receivedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDelivery = `-- name: MarkDelivery :one

INSERT INTO webhook_deliveries (delivery_id)
VALUES ($1)
ON CONFLICT (delivery_id) DO NOTHING
RETURNING delivery_id
`

// Webhook delivery dedup queries (E3.9 / #110). sqlc generates
// typed Go into ./db per backend/sqlc.yaml.
// INSERT ... ON CONFLICT DO NOTHING RETURNING. Empty result
// means the row already existed (= duplicate); a returned
// delivery_id means the row was newly inserted.
func (q *Queries) MarkDelivery(ctx context.Context, deliveryID string) (string, error) {
	row := q.db.QueryRow(ctx, markDelivery, deliveryID)
	var delivery_id string
	err := row.Scan(&delivery_id)
	return delivery_id, err
}
