// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repoacldb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type RepoAclEntry struct {
	ID         uuid.UUID          `json:"id"`
	Provider   string             `json:"provider"`
	Subject    string             `json:"subject"`
	Repo       string             `json:"repo"`
	Permission string             `json:"permission"`
	CheckedAt  pgtype.Timestamptz `json:"checked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type RepoAclPurgeWatermark struct {
	Provider   string             `json:"provider"`
	Subject    string             `json:"subject"`
	Generation int64              `json:"generation"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
