// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repoacldb

import (
	"context"

	"github.com/google/uuid"
)

const deleteRepoACLEntriesForSubject = `-- name: DeleteRepoACLEntriesForSubject :exec
DELETE FROM repo_acl_entries
 WHERE provider = $1
   AND subject = $2
`

type DeleteRepoACLEntriesForSubjectParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

// The login purge: drop every mirrored entry for one identity so the next read
// re-resolves against the forge. Served by
// repo_acl_entries_provider_subject_idx.
func (q *Queries) DeleteRepoACLEntriesForSubject(ctx context.Context, arg DeleteRepoACLEntriesForSubjectParams) error {
	_, err := q.db.Exec(ctx, deleteRepoACLEntriesForSubject, arg.Provider, arg.Subject)
	return err
}

const getRepoACLEntry = `-- name: GetRepoACLEntry :one
SELECT id, provider, subject, repo, permission, checked_at, created_at, updated_at FROM repo_acl_entries
 WHERE provider = $1
   AND subject = $2
   AND repo = $3
`

type GetRepoACLEntryParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
	Repo     string `json:"repo"`
}

// The read-path lookup, keyed on the natural key. pgx.ErrNoRows is a MISS,
// which the Go layer resolves live rather than treating as a deny.
func (q *Queries) GetRepoACLEntry(ctx context.Context, arg GetRepoACLEntryParams) (RepoAclEntry, error) {
	row := q.db.QueryRow(ctx, getRepoACLEntry, arg.Provider, arg.Subject, arg.Repo)
	var i RepoAclEntry
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Subject,
		&i.Repo,
		&i.Permission,
		&i.CheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepoACLEntry = `-- name: UpsertRepoACLEntry :one
INSERT INTO repo_acl_entries (id, provider, subject, repo, permission)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (provider, subject, repo) DO UPDATE
   SET permission = EXCLUDED.permission,
       checked_at = now(),
       updated_at = now()
RETURNING id, provider, subject, repo, permission, checked_at, created_at, updated_at
`

type UpsertRepoACLEntryParams struct {
	ID         uuid.UUID `json:"id"`
	Provider   string    `json:"provider"`
	Subject    string    `json:"subject"`
	Repo       string    `json:"repo"`
	Permission string    `json:"permission"`
}

// Memoize a permission the forge just reported. checked_at is refreshed on
// EVERY upsert, including one whose permission is unchanged — the TTL clock
// tracks "when did we last ask", not "when did the answer last change".
//
// Only a resolved answer is ever written here. A forge ERROR must never reach
// this statement: memoizing a transient fault would either cache a phantom
// deny or, worse, hold a stale grant past its real revocation.
func (q *Queries) UpsertRepoACLEntry(ctx context.Context, arg UpsertRepoACLEntryParams) (RepoAclEntry, error) {
	row := q.db.QueryRow(ctx, upsertRepoACLEntry,
		arg.ID,
		arg.Provider,
		arg.Subject,
		arg.Repo,
		arg.Permission,
	)
	var i RepoAclEntry
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Subject,
		&i.Repo,
		&i.Permission,
		&i.CheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
