import type { StandardV1Plan } from '@/api/plan';
import type { Stage } from '@/api/types';
import { ApprovalPanel } from './approval-panel';
import {
  ApproachSection,
  GeneratedBySection,
  RisksSection,
  ScopeSection,
  SummarySection,
  TicketSection,
  VerificationSection,
} from './sections';

interface NavItem {
  id: string;
  label: string;
}

function buildNav(plan: StandardV1Plan): NavItem[] {
  const nav: NavItem[] = [
    { id: 'ticket', label: 'Ticket' },
    { id: 'generated-by', label: 'Generated by' },
    { id: 'summary', label: 'Summary' },
    { id: 'scope', label: 'Scope' },
    { id: 'approach', label: 'Approach' },
    { id: 'verification', label: 'Verification' },
  ];
  if (plan.risks_and_assumptions && plan.risks_and_assumptions.length > 0) {
    nav.push({ id: 'risks', label: 'Risks & assumptions' });
  }
  return nav;
}

interface Props {
  plan: StandardV1Plan;
  stage: Stage;
  runId: string;
  onStageUpdate: (next: Stage) => void;
  onStageRollback: (prev: Stage) => void;
}

/*
 * Plans-as-documents (Brand Foundations §6): structured fields with
 * anchors, not chat. The approval panel sits at the top of the doc
 * — the only state-changing surface; everything below it is the
 * read-only document the reviewer is acting on.
 */
export function PlanDocument({ plan, stage, runId, onStageUpdate, onStageRollback }: Props) {
  const nav = buildNav(plan);

  return (
    <div className="grid grid-cols-[14rem_1fr] gap-8">
      <aside className="sticky top-6 self-start">
        <nav aria-label="Plan sections" className="space-y-1 text-sm">
          {nav.map((item) => (
            <a
              key={item.id}
              href={`#${item.id}`}
              className="block rounded-md px-2 py-1 text-neutral-600 hover:bg-neutral-100 hover:text-neutral-900 dark:text-neutral-400 dark:hover:bg-neutral-800 dark:hover:text-neutral-100"
            >
              {item.label}
            </a>
          ))}
        </nav>
      </aside>

      <article className="max-w-3xl space-y-8 pb-20">
        <header className="flex items-start justify-between gap-4">
          <div>
            <p className="text-xs tracking-wide text-neutral-500 uppercase">
              Plan · {plan.plan_version}
            </p>
            <h1 className="mt-1 text-2xl font-semibold tracking-tight">Review plan</h1>
          </div>
          <ApprovalPanel
            stage={stage}
            runId={runId}
            onUpdate={onStageUpdate}
            onRollback={onStageRollback}
          />
        </header>

        <TicketSection ticket={plan.ticket_reference} />
        <GeneratedBySection by={plan.generated_by} />
        <SummarySection summary={plan.summary} />
        <ScopeSection scope={plan.scope} />
        <ApproachSection approach={plan.approach} />
        <VerificationSection v={plan.verification} />
        {plan.risks_and_assumptions && plan.risks_and_assumptions.length > 0 && (
          <RisksSection risks={plan.risks_and_assumptions} />
        )}
      </article>
    </div>
  );
}
