import { CheckCircle2, ExternalLink, FileText, MessageSquare, XCircle } from 'lucide-react';
import { Link } from 'react-router';
import { api } from '@/api/client';
import { useAsync } from '@/api/use-async';
import type { StandardV1Plan } from '@/api/plan';
import type { AuditEntry, Stage } from '@/api/types';
import { StageStateBadge } from '@/components/stage-state-badge';
import {
  ApproachSection,
  GeneratedBySection,
  RisksSection,
  ScopeSection,
  Section,
  SummarySection,
  TicketSection,
  VerificationSection,
} from './sections';

interface NavItem {
  id: string;
  label: string;
}

function buildNav(plan: StandardV1Plan, showActivity: boolean): NavItem[] {
  const nav: NavItem[] = [
    { id: 'ticket', label: 'Ticket' },
    { id: 'generated-by', label: 'Generated by' },
    { id: 'summary', label: 'Summary' },
    { id: 'scope', label: 'Scope' },
    { id: 'approach', label: 'Approach' },
    { id: 'verification', label: 'Verification' },
  ];
  if (plan.risks_and_assumptions && plan.risks_and_assumptions.length > 0) {
    nav.push({ id: 'risks', label: 'Risks & assumptions' });
  }
  if (showActivity) {
    nav.push({ id: 'activity', label: 'Activity' });
  }
  return nav;
}

interface Props {
  plan: StandardV1Plan;
  stage: Stage;
  runId: string;
}

/*
 * Plans-as-documents (Brand Foundations §6, ADR-020 / #321).
 *
 * Post-ADR-020 this page is a read-only mirror of the plan comment
 * the backend posts on the originating issue (E17.2 / #337). The
 * approval surface moved to GitHub: a typed "+1" / "lgtm" reply
 * comment (E17.3 / #338 + E17.4 / #339) writes an approval with
 * `Surface=github_reply_comment`; an explicit `/fishhawk approve`
 * slash command writes with `Surface=github_comment`. Both flows
 * advance the stage on the backend; the SPA reflects state rather
 * than driving it. (Direct precedent: ADR-018 / #314 did the same
 * flip for the review stage.)
 *
 * Header carries a "View on GitHub" affordance pointing at the
 * plan comment URL (resolved from the audit log) so reviewers can
 * jump to the conversation surface in one click.
 */
export function PlanDocument({ plan, stage, runId }: Props) {
  // Fetch the run's audit log once at the document level so the
  // header link and the activity panel share a single round-trip.
  // Limit covers a v0-scale per-run chain comfortably; pagination
  // would hide the earliest plan-comment post from the lookup.
  const audit = useAsync(() => api.listRunAudit(runId, { limit: 500 }), [runId]);

  const auditEntries: AuditEntry[] = audit.status === 'ok' ? audit.data.items : [];
  const planCommentURL = findPlanCommentURL(auditEntries);
  const activityEntries = filterPlanActivity(auditEntries);
  const showActivity = audit.status === 'loading' || activityEntries.length > 0;
  const nav = buildNav(plan, showActivity);

  return (
    <div className="grid grid-cols-[14rem_1fr] gap-8">
      <aside className="sticky top-6 self-start">
        <nav aria-label="Plan sections" className="space-y-1 text-sm">
          {nav.map((item) => (
            <a
              key={item.id}
              href={`#${item.id}`}
              className="block rounded-md px-2 py-1 text-neutral-600 hover:bg-neutral-100 hover:text-neutral-900 dark:text-neutral-400 dark:hover:bg-neutral-800 dark:hover:text-neutral-100"
            >
              {item.label}
            </a>
          ))}
        </nav>
      </aside>

      <article className="max-w-3xl space-y-8 pb-20">
        <header className="flex items-start justify-between gap-4">
          <div>
            <p className="text-xs tracking-wide text-neutral-500 uppercase">
              Plan · {plan.plan_version}
            </p>
            <h1 className="mt-1 text-2xl font-semibold tracking-tight">Plan</h1>
            <div className="mt-2 flex items-center gap-3">
              <StageStateBadge state={stage.state} />
              <Link
                to={`/runs/${runId}#audit`}
                className="text-xs text-neutral-500 hover:underline"
              >
                View audit log
              </Link>
            </div>
          </div>
          {planCommentURL && (
            <a
              href={planCommentURL}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1 self-start rounded-md border border-neutral-300 px-3 py-1.5 text-xs font-medium text-neutral-700 hover:bg-neutral-50 focus-visible:ring-1 focus-visible:ring-neutral-400 focus-visible:outline-none dark:border-neutral-700 dark:text-neutral-200 dark:hover:bg-neutral-900/50"
            >
              <ExternalLink className="size-3.5" aria-hidden />
              View on GitHub
            </a>
          )}
        </header>

        <TicketSection ticket={plan.ticket_reference} />
        <GeneratedBySection by={plan.generated_by} />
        <SummarySection summary={plan.summary} />
        <ScopeSection scope={plan.scope} />
        <ApproachSection approach={plan.approach} />
        <VerificationSection v={plan.verification} />
        {plan.risks_and_assumptions && plan.risks_and_assumptions.length > 0 && (
          <RisksSection risks={plan.risks_and_assumptions} />
        )}

        {showActivity && (
          <Section id="activity" title="Activity">
            <PlanActivity audit={audit} entries={activityEntries} />
          </Section>
        )}
      </article>
    </div>
  );
}

/*
 * PLAN_COMMENT_KINDS tracks the payload.kind values the backend
 * writes when it posts or edits the plan comment (E17.2 / #337).
 * The most-recent row's github_comment_id is the canonical comment
 * to link to — edits keep the same id, so any row in this set
 * works after the operator has stopped deleting comments.
 */
const PLAN_COMMENT_KINDS = new Set(['plan_full', 'plan_updated']);

interface PlanCommentPayload {
  kind?: string;
  repo?: string;
  issue_number?: number;
  github_comment_id?: number;
}

function asPlanCommentPayload(payload: unknown): PlanCommentPayload | null {
  if (!payload || typeof payload !== 'object') return null;
  return payload as PlanCommentPayload;
}

/*
 * findPlanCommentURL walks the audit chain newest-first (the audit
 * API returns descending by sequence on the global feed; per-run
 * scope returns ascending — see #211) and returns the most-recent
 * plan-comment URL. Returns null when no plan comment has landed
 * (CLI-only runs, or pre-E17 runs without the persistence flag).
 */
function findPlanCommentURL(entries: AuditEntry[]): string | null {
  for (let i = entries.length - 1; i >= 0; i--) {
    const e = entries[i];
    if (e.category !== 'issue_commented') continue;
    const p = asPlanCommentPayload(e.payload);
    if (!p || !p.kind || !PLAN_COMMENT_KINDS.has(p.kind)) continue;
    if (!p.repo || !p.issue_number || !p.github_comment_id) continue;
    return `https://github.com/${p.repo}/issues/${p.issue_number}#issuecomment-${p.github_comment_id}`;
  }
  return null;
}

const PLAN_ACTIVITY_CATEGORIES = new Set(['issue_commented', 'approval_submitted']);

interface ApprovalPayload {
  decision?: string;
  surface?: string;
  approver?: string;
}

function asApprovalPayload(payload: unknown): ApprovalPayload | null {
  if (!payload || typeof payload !== 'object') return null;
  return payload as ApprovalPayload;
}

/*
 * filterPlanActivity keeps the audit rows the activity panel
 * surfaces: plan-comment posts/updates and any plan-stage approval
 * decision. Closed-set membership is fast; unknown categories that
 * sneak into the chain stay invisible until the renderer
 * explicitly opts in.
 */
function filterPlanActivity(entries: AuditEntry[]): AuditEntry[] {
  return entries.filter((e) => {
    if (!PLAN_ACTIVITY_CATEGORIES.has(e.category)) return false;
    if (e.category === 'issue_commented') {
      const p = asPlanCommentPayload(e.payload);
      return p?.kind != null && PLAN_COMMENT_KINDS.has(p.kind);
    }
    return true;
  });
}

interface AuditResultLoading {
  status: 'loading';
}
interface AuditResultError {
  status: 'error';
  error: Error;
}
interface AuditResultOK {
  status: 'ok';
}

function PlanActivity({
  audit,
  entries,
}: {
  audit: AuditResultLoading | AuditResultError | AuditResultOK;
  entries: AuditEntry[];
}) {
  if (audit.status === 'loading') {
    return <p className="text-sm text-neutral-500">Loading activity…</p>;
  }
  if (audit.status === 'error') {
    return (
      <p className="text-sm text-rose-700 dark:text-rose-300">
        Couldn&apos;t load activity: {audit.error.message}
      </p>
    );
  }
  if (entries.length === 0) {
    return <p className="text-sm text-neutral-500">No plan activity yet.</p>;
  }

  // Audit rows arrive ascending-by-sequence from listRunAudit; the
  // activity panel reads top-to-bottom oldest-first, matching how
  // the operator scans the issue thread.
  return (
    <ul
      data-testid="plan-activity"
      className="overflow-hidden rounded-md border border-neutral-200 dark:border-neutral-800"
    >
      {entries.map((e) => (
        <li
          key={e.id}
          className="flex items-start gap-3 border-b border-neutral-200 px-3 py-2 text-sm last:border-b-0 dark:border-neutral-800"
        >
          <ActivityIcon entry={e} />
          <div className="flex-1">
            <ActivityLine entry={e} />
            <p className="text-xs text-neutral-500">{formatTimestamp(e.ts)}</p>
          </div>
        </li>
      ))}
    </ul>
  );
}

function ActivityIcon({ entry }: { entry: AuditEntry }) {
  if (entry.category === 'issue_commented') {
    return (
      <FileText className="mt-0.5 size-4 text-neutral-500 dark:text-neutral-400" aria-hidden />
    );
  }
  if (entry.category === 'approval_submitted') {
    const p = asApprovalPayload(entry.payload);
    if (p?.decision === 'reject') {
      return <XCircle className="mt-0.5 size-4 text-rose-600 dark:text-rose-400" aria-hidden />;
    }
    return (
      <CheckCircle2 className="mt-0.5 size-4 text-emerald-600 dark:text-emerald-400" aria-hidden />
    );
  }
  return <MessageSquare className="mt-0.5 size-4 text-neutral-500" aria-hidden />;
}

function ActivityLine({ entry }: { entry: AuditEntry }) {
  if (entry.category === 'issue_commented') {
    const p = asPlanCommentPayload(entry.payload);
    if (p?.kind === 'plan_full') {
      return (
        <p>
          Plan posted to{' '}
          <span className="font-mono text-xs">
            {p.repo}#{p.issue_number}
          </span>
        </p>
      );
    }
    if (p?.kind === 'plan_updated') {
      return (
        <p>
          Plan updated on{' '}
          <span className="font-mono text-xs">
            {p.repo}#{p.issue_number}
          </span>
        </p>
      );
    }
    return <p>Comment posted</p>;
  }
  if (entry.category === 'approval_submitted') {
    const p = asApprovalPayload(entry.payload);
    const actor = p?.approver ?? entry.actor_subject ?? 'unknown';
    const at = `@${actor}`;
    const verb = p?.decision === 'reject' ? 'rejected' : 'approved';
    const via = approvalSurfaceLabel(p?.surface);
    return (
      <p>
        <span className="font-medium">{at}</span> {verb}
        {via && <span className="text-neutral-500"> via {via}</span>}
      </p>
    );
  }
  return <p>{entry.category}</p>;
}

/*
 * approvalSurfaceLabel renders the approval.Surface value as a
 * short human-readable phrase. The discriminator lives in the
 * audit row's payload (mirrored from the approval row's column);
 * the labels keep the SPA's wording aligned with the CLI / GitHub
 * paths so a reader sees consistent surface names across tools.
 */
function approvalSurfaceLabel(surface: string | undefined): string {
  switch (surface) {
    case 'github_reply_comment':
      return 'reply comment';
    case 'github_comment':
      return '/fishhawk approve';
    case 'ui':
      return 'dashboard';
    case 'cli':
      return 'CLI';
    case 'api':
      return 'API';
    default:
      return '';
  }
}

function formatTimestamp(ts: string): string {
  try {
    const d = new Date(ts);
    if (Number.isNaN(d.getTime())) return ts;
    return d.toLocaleString();
  } catch {
    return ts;
  }
}
