import { useState } from 'react';
import { ArrowUpRight, ChevronDown, ChevronRight, FileMinus, FilePlus, FilePen } from 'lucide-react';
import type { ScopeFile, StandardV1Plan } from '@/api/plan';

/*
 * Plan-section primitives. Each section is its own component so the
 * side-nav anchors line up with discrete units that can be styled
 * (and later, individually annotated) without touching the others.
 *
 * Brand Foundations §6: plans are documents. No avatars, no chat
 * bubbles, no "agent says…" framing. Just the structured fields the
 * agent committed to.
 *
 * When `collapsible` is set, the header doubles as a toggle button —
 * the implement-stage page (#250) uses this to let reviewers fold any
 * section. The non-collapsible path stays byte-identical to the
 * original markup so plan / review consumers render unchanged.
 */

export function Section({
  id,
  title,
  collapsible,
  defaultOpen = true,
  children,
}: {
  id: string;
  title: string;
  collapsible?: boolean;
  defaultOpen?: boolean;
  children: React.ReactNode;
}) {
  const [open, setOpen] = useState(defaultOpen);
  const bodyId = `${id}-body`;

  if (!collapsible) {
    return (
      <section id={id} className="scroll-mt-8 space-y-3">
        <h2 className="text-sm font-medium tracking-wide text-neutral-600 uppercase dark:text-neutral-400">
          {title}
        </h2>
        <div>{children}</div>
      </section>
    );
  }

  return (
    <section id={id} className="scroll-mt-8 space-y-3">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        aria-expanded={open}
        aria-controls={bodyId}
        className="group inline-flex items-center gap-1.5 text-left text-neutral-600 hover:text-neutral-900 dark:text-neutral-400 dark:hover:text-neutral-100"
      >
        {open ? (
          <ChevronDown className="size-3.5" aria-hidden />
        ) : (
          <ChevronRight className="size-3.5" aria-hidden />
        )}
        <h2 className="text-sm font-medium tracking-wide uppercase">{title}</h2>
      </button>
      {open && (
        <div id={bodyId}>{children}</div>
      )}
    </section>
  );
}

export function TicketSection({ ticket }: { ticket: StandardV1Plan['ticket_reference'] }) {
  return (
    <Section id="ticket" title="Ticket">
      <a
        href={ticket.url}
        rel="noreferrer"
        target="_blank"
        className="inline-flex items-center gap-1 font-mono text-sm hover:underline"
      >
        {ticket.id}
        <ArrowUpRight className="size-3.5" aria-hidden />
      </a>
    </Section>
  );
}

export function GeneratedBySection({ by }: { by: StandardV1Plan['generated_by'] }) {
  return (
    <Section id="generated-by" title="Generated by">
      <dl className="grid grid-cols-[8rem_1fr] gap-y-1 text-sm">
        <dt className="text-neutral-500">Agent</dt>
        <dd className="font-mono">{by.agent}</dd>
        <dt className="text-neutral-500">Model</dt>
        <dd className="font-mono">{by.model}</dd>
        {by.version && (
          <>
            <dt className="text-neutral-500">Version</dt>
            <dd className="font-mono text-xs">{by.version}</dd>
          </>
        )}
        <dt className="text-neutral-500">Timestamp</dt>
        <dd className="font-mono text-xs">{by.timestamp}</dd>
      </dl>
    </Section>
  );
}

export function SummarySection({ summary }: { summary: string }) {
  return (
    <Section id="summary" title="Summary">
      <p className="text-base leading-relaxed whitespace-pre-wrap">{summary}</p>
    </Section>
  );
}

const opIcon: Record<ScopeFile['operation'], typeof FilePlus> = {
  create: FilePlus,
  modify: FilePen,
  delete: FileMinus,
};

const opStyle: Record<ScopeFile['operation'], string> = {
  create: 'text-emerald-700 dark:text-emerald-300',
  modify: 'text-blue-700 dark:text-blue-300',
  delete: 'text-rose-700 dark:text-rose-300',
};

export function ScopeSection({ scope }: { scope: StandardV1Plan['scope'] }) {
  return (
    <Section id="scope" title="Scope">
      {typeof scope.estimated_lines_changed === 'number' && (
        <p className="mb-3 text-xs text-neutral-500">
          Estimated lines changed: {scope.estimated_lines_changed}
        </p>
      )}
      <ul className="divide-y divide-neutral-200 rounded-md border border-neutral-200 dark:divide-neutral-800 dark:border-neutral-800">
        {scope.files.map((f) => {
          const Icon = opIcon[f.operation];
          return (
            <li
              key={`${f.path}-${f.operation}`}
              className="flex items-center gap-3 px-3 py-2 font-mono text-sm"
            >
              <Icon className={`size-4 ${opStyle[f.operation]}`} aria-hidden />
              <span className="w-16 shrink-0 text-xs text-neutral-500 uppercase">
                {f.operation}
              </span>
              <span className="truncate">{f.path}</span>
            </li>
          );
        })}
      </ul>
    </Section>
  );
}

export function ApproachSection({ approach }: { approach: StandardV1Plan['approach'] }) {
  return (
    <Section id="approach" title="Approach">
      <ol className="space-y-3">
        {approach.map((s) => (
          <li key={s.step} className="flex gap-3 text-sm">
            <span className="mt-0.5 inline-flex size-6 shrink-0 items-center justify-center rounded-full bg-neutral-200 font-mono text-xs dark:bg-neutral-800">
              {s.step}
            </span>
            <p className="leading-relaxed whitespace-pre-wrap">{s.description}</p>
          </li>
        ))}
      </ol>
    </Section>
  );
}

export function VerificationSection({ v }: { v: StandardV1Plan['verification'] }) {
  return (
    <Section id="verification" title="Verification">
      <dl className="space-y-3 text-sm">
        <div>
          <dt className="text-xs tracking-wide text-neutral-500 uppercase">Test strategy</dt>
          <dd className="mt-1 leading-relaxed whitespace-pre-wrap">{v.test_strategy}</dd>
        </div>
        <div>
          <dt className="text-xs tracking-wide text-neutral-500 uppercase">Rollback plan</dt>
          <dd className="mt-1 leading-relaxed whitespace-pre-wrap">{v.rollback_plan}</dd>
        </div>
      </dl>
    </Section>
  );
}

export function RisksSection({ risks }: { risks: string[] }) {
  return (
    <Section id="risks" title="Risks &amp; assumptions">
      <ul className="list-disc space-y-1 pl-5 text-sm leading-relaxed marker:text-neutral-400">
        {risks.map((r, i) => (
          <li key={i}>{r}</li>
        ))}
      </ul>
    </Section>
  );
}
