// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package signingdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSigningKey = `-- name: GetSigningKey :one
SELECT run_id, public_key, issued_at, expires_at FROM signing_keys WHERE run_id = $1
`

func (q *Queries) GetSigningKey(ctx context.Context, runID uuid.UUID) (SigningKey, error) {
	row := q.db.QueryRow(ctx, getSigningKey, runID)
	var i SigningKey
	err := row.Scan(
		&i.RunID,
		&i.PublicKey,
		&i.IssuedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const issueSigningKey = `-- name: IssueSigningKey :one

INSERT INTO signing_keys (run_id, public_key, issued_at, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING run_id, public_key, issued_at, expires_at
`

type IssueSigningKeyParams struct {
	RunID     uuid.UUID          `json:"run_id"`
	PublicKey []byte             `json:"public_key"`
	IssuedAt  pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Signing-key queries consumed by the postgres adapter for the
// signing.Repository interface (E2.3 / #24). Append-only — no Update
// or Delete queries; the schema's triggers backstop that.
func (q *Queries) IssueSigningKey(ctx context.Context, arg IssueSigningKeyParams) (SigningKey, error) {
	row := q.db.QueryRow(ctx, issueSigningKey,
		arg.RunID,
		arg.PublicKey,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	var i SigningKey
	err := row.Scan(
		&i.RunID,
		&i.PublicKey,
		&i.IssuedAt,
		&i.ExpiresAt,
	)
	return i, err
}
