// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package approvaldb

import (
	"context"

	"github.com/google/uuid"
)

const createApproval = `-- name: CreateApproval :one

INSERT INTO approvals (id, stage_id, approver_subject, decision, comment, surface)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (stage_id, approver_subject) DO NOTHING
RETURNING id, stage_id, approver_subject, decision, comment, surface, submitted_at
`

type CreateApprovalParams struct {
	ID              uuid.UUID `json:"id"`
	StageID         uuid.UUID `json:"stage_id"`
	ApproverSubject string    `json:"approver_subject"`
	Decision        string    `json:"decision"`
	Comment         *string   `json:"comment"`
	Surface         string    `json:"surface"`
}

// Approval queries consumed by the postgres adapter for the
// approval.Repository interface (E3.5 / #45). sqlc generates typed
// Go into ./db per the config in /backend/sqlc.yaml.
// ON CONFLICT DO NOTHING + COALESCE-based read makes this an
// idempotent upsert: a re-submission from the same approver
// returns the existing row's id without inserting a new one.
func (q *Queries) CreateApproval(ctx context.Context, arg CreateApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, createApproval,
		arg.ID,
		arg.StageID,
		arg.ApproverSubject,
		arg.Decision,
		arg.Comment,
		arg.Surface,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.StageID,
		&i.ApproverSubject,
		&i.Decision,
		&i.Comment,
		&i.Surface,
		&i.SubmittedAt,
	)
	return i, err
}

const getApprovalByApprover = `-- name: GetApprovalByApprover :one
SELECT id, stage_id, approver_subject, decision, comment, surface, submitted_at FROM approvals
 WHERE stage_id = $1 AND approver_subject = $2
`

type GetApprovalByApproverParams struct {
	StageID         uuid.UUID `json:"stage_id"`
	ApproverSubject string    `json:"approver_subject"`
}

func (q *Queries) GetApprovalByApprover(ctx context.Context, arg GetApprovalByApproverParams) (Approval, error) {
	row := q.db.QueryRow(ctx, getApprovalByApprover, arg.StageID, arg.ApproverSubject)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.StageID,
		&i.ApproverSubject,
		&i.Decision,
		&i.Comment,
		&i.Surface,
		&i.SubmittedAt,
	)
	return i, err
}

const listApprovalsForStage = `-- name: ListApprovalsForStage :many
SELECT id, stage_id, approver_subject, decision, comment, surface, submitted_at FROM approvals
 WHERE stage_id = $1
 ORDER BY submitted_at ASC
`

func (q *Queries) ListApprovalsForStage(ctx context.Context, stageID uuid.UUID) ([]Approval, error) {
	rows, err := q.db.Query(ctx, listApprovalsForStage, stageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Approval
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.StageID,
			&i.ApproverSubject,
			&i.Decision,
			&i.Comment,
			&i.Surface,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
